### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by Kennyc1012** [koral--/android-gif-drawable#109]
Rendering certain gifs cause weird issues in the coloring. An example can be shown below. 

This is how it is rendering in the app
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2333025/5596923/50edfe6a-9267-11e4-96dc-d60da4fbc3b7.gif)

This is how it should look
![glggo9j](https://cloud.githubusercontent.com/assets/2333025/5596924/50efa08a-9267-11e4-8935-73b85dbaf6c7.gif)

The image is displayed by downloading it from a url to a local file then setting them as a drawable as such

` GifDrawable drawable = new GifDrawable(new File("PATH TO FILE"));
    image.setDrawable(drawable);`

I've also noticed that sometimes the gifs will be in black and white opposed to color.
The device used was a nexus 5 running stock 5.0 

EDIT: This was using version 1.1.1, in version 1.1.0 they work fine.

**Comment by koral--** [comment]
That problem does not occur on v 1.1.1 (release) but on 1.1.2-SNAPSHOT. It already described in  https://github.com/koral--/android-gif-drawable/issues/105#issuecomment-68684291
