### ISSUE TITLE
compile c source files to a single .so file under Mac (version 10.10.1)

### ISSUE THREAD

**Issue by studyfordream** [koral--/android-gif-drawable#110]
hello, i am not familiar with c language,  please write some code step by step for compiling the JNI source files to .so file. please help....  Thanks a lot.

**Comment by koral--** [comment]
1. download and unpack NDK from http://dl.google.com/android/ndk/android-ndk-r10d-darwin-x86_64.bin
2. add `ndk.dir=<NDK_PATH>` to `local.properties` file in library root directory (create if not exist) alternatively NDK directory may be added to your PATH (eg. in ~/.bash_profile). <NDK_PATH> is a root directory of unpacked NDK (`ndk-build` should be there), library root directory is that one with `build.gradle` file
3. execute `./gradlew assembleRelease`
4. .so files will be placed in `build/intermediates/ndk/release/lib/` subdirectories

Note there will be one .so file per each architecture.

**Comment by studyfordream** [comment]
thank you very very much.
