### ISSUE TITLE
Add GifImageView in listview cause out of memory

### ISSUE THREAD

**Issue by lzou** [koral--/android-gif-drawable#111]
source code:
gifImage.setImageResource(id);

id is a gif picture in drawable folder.
I slide up and down the listview.then if will outofmemery.
Java.lang.OutOfMemoryError

how can i avoid it? thanks

**Comment by koral--** [comment]
You can can use `GifDrawable#recycle()` on unneeded drawables. Eg. in adapter:
```java
@Override
        public View getView(int position, View convertView, ViewGroup parent) {
//inflate view if needed
            GifImageView gifImageView = (GifImageView) convertView.findViewById(R.id.giv);
            Drawable d = gifImageView.getDrawable();
            if (d instanceof GifDrawable) {
                ((GifDrawable) d).recycle();
            }
//assign new drawable
```

**Comment by lzou** [comment]
@koral--  when setBackground for gifImageView ? i don't see where init drawable.

**Comment by koral--** [comment]
To retrieve old background just call `GifImageView#getBackground()`.

**Comment by lzou** [comment]
@koral--  That's not what I meant. in your code:
GifImageView gifImageView = (GifImageView) convertView.findViewById(R.id.giv);
            Drawable d = gifImageView.getDrawable();
            if (d instanceof GifDrawable) {
                ((GifDrawable) d).recycle();
there is no place to initialization a GIfDrawable.so the gifImageView doesn't display gif。
when initialization a GIfDrawable? My English is poor, sorry

**Comment by koral--** [comment]
Just set background below given code, eg:
```java
@Override
        public View getView(int position, View convertView, ViewGroup parent) {
//code to inflate view if needed here
            GifImageView gifImageView = (GifImageView) convertView.findViewById(R.id.giv);
            Drawable d = gifImageView.getBackground();
            if (d instanceof GifDrawable) {
                ((GifDrawable) d).recycle();
            }
gifImageView.setBackground(new GifDrawable(...));
//rest of the getView code here
```

**Comment by lzou** [comment]
@koral--   i do it like this. but if i rapid sliding back and forth the listview.it's still crash,it's outofmemoryerrors.how can i avoid outofmemory? 
i think if the listView is scrolling, then let the gifImage doesn't play,maybe it will not outofmemory.how can i do it? can you show me some code?

**Comment by koral--** [comment]
Which library version are you using? Does the problem occur on the latest one (1.1.2)?

**Comment by lzou** [comment]
@koral-- yes  release v 1.1.2

**Comment by koral--** [comment]
You can use `GifDrawableBuilder#with()` as described in #108. If that won't help then I have no idea other than reducing dimensions of source GIF files (eg. using imagemagick or so) before compiling the app.
PS. there is already a task for animation pause while scrolling (#73) but it is not directly connected with memory usage. Generally always only one frame is buffered no matter if animation is running or not. So only performance can be improved that way, not memory usage.
