### ISSUE TITLE
Gif animation speed slow

### ISSUE THREAD

**Issue by henritta** [koral--/android-gif-drawable#114]
Hi Koral,

I found the speed is much slower than PC, while playing the gif files,

Even compare with Samsung's Gallery, it still looks slower.
 
Is it limitation? Below link is my testing picture, if you need.

https://www.asuswebstorage.com/navigate/s/408CE1540B0D4D27BA37ED1E3AE58112Y

**Comment by sirvon** [comment]
what if you speed it up, using the settings...same difference?

**Comment by henritta** [comment]
Using Settings speed up? What do you mean?

Could you tell me how to do that?

**Comment by koral--** [comment]
@henritta maybe @sirvon talked about `GifDrawable#setSpeed()`. It can speed up animation but its not a solution of course, only a workaround.
Current animation flow is as follows:
1. raw data from input source is converted into pixels of the given frame and its metadata (including frame duration) - real duration of this step strongly depends on size of the frame and performance of the device
2. rendering of the next frame (step 1. of the next frame) is scheduled with delay equal to mentioned duration
3. UI redraw is requested, `GifDrawable#draw()` will be called by system in the near future (won't be called if drawable is not visible)

Problem is that delay in step 2. does not include (properly - exclude) computation time. 
I'll try to fix this ASAP.
