### ISSUE TITLE
Gif Drawable Resize to Full Screen

### ISSUE THREAD

**Issue by oalpayli** [koral--/android-gif-drawable#116]
Hi Koral,

I use your library for my splash screen. But I have a problem to resize GIF according to device screen. All widgets use  match parent property in my code but gif doesn't fit to screen? Please tell me why that can be? And I will be glad to that you can send answer to my email. (oguzhanalpayli@gmail.com)

Thank you.

**Comment by koral--** [comment]
If you are using (Gif)ImageView or (Gif)ImageButton you should set appropriate scale type. Eg. `android:scaleType="fitXY"` in xml of the layout.

**Comment by oalpayli** [comment]
I tried my friend. But it didnt work for me. At last i solved my problem. I
changed theme of splash screen activity to fullscreen and it worked.

Thank for your reply. Library works very efficient and powerful.

Have a good day friend.
31 Oca 2015 03:43 tarihinde "Karol Wrótniak" <notifications@github.com>
yazdı:

**Comment by HijasAjmal** [comment]
Thank you "koral"
its working.....

**Comment by shravanbhuyar** [comment]
android:scaleType="centerCrop" worked perfectly for me
