### ISSUE TITLE
seekToFrame not cause redraw when animation is stopped or paused

### ISSUE THREAD

**Issue by nkuznetsow** [koral--/android-gif-drawable#118]
I need ability to manually set frame which must be drawn when animation is stopped or paused, but when I call seekToFrame(int) it not cause redraw drawable.

**Comment by koral--** [comment]
Are trying to seek backward or forward? Currently only seeking forward is supported and tries to seek backward is ignored no matter if animation is started or not. It is mentioned in javadoc of `#seekTo()` (link to it in `#seekToFrame() was broken but I've corrected it just now).

In general for seeking backward animation has to be rewound and then sought forward and this is not implemented yet. I'll add ability to seek backward ASAP.

Seeking forward should work. I could not reproduce any problem with it.
