### ISSUE TITLE
How can convert project structure gradle to maven   

### ISSUE THREAD

**Issue by atulsethi** [koral--/android-gif-drawable#119]
Hi ,
   I am using android-gif-drawable library in my project and it is working fine before Lollipop android version but in Lollipop  , application throw error . I am using complete source code for this library in my  code and compile with NDK-Build .  i know this library have updated in Gradle but My project have maven structure and i have no idea about gradle .

 Please explain how can i use updated library  in my application or can you provide source code in maven structure ?

Thank you

**Comment by koral--** [comment]
You can translate `build.gradle` to `pom.xml`, `jni/Android.mk` and `Application.mk` files. You can see how it looked like when maven was used in library in older tags: https://github.com/koral--/android-gif-drawable/tree/v1.0.6. Additionally you need to deploy android framework artifact using [maven-android-sdk-deployer](https://github.com/simpligility/maven-android-sdk-deployer) to your local maven repo (see #7).
Now there is a newer version of [maven-android-plugin](https://code.google.com/p/maven-android-plugin/) so maybe some details has changed.
