### ISSUE TITLE
Build libgif.so error in eclipse

### ISSUE THREAD

**Issue by huangyikai1990** [koral--/android-gif-drawable#120]
I use the latest code to compile.But make a mistake...

[arm64-v8a] Compile        : gif <= gif.c
[arm64-v8a] Compile        : gif <= dgif_lib.c
[arm64-v8a] Compile        : gif <= gifalloc.c
[arm64-v8a] SharedLibrary  : libgif.so
D:/android-ndk-r10/samples/hello-jni//obj/local/arm64-v8a/objs/gif/gif.o: In function `Java_pl_droidsonroids_gif_GifInfoHandle_seekToTime':
D:/android-ndk-r10/samples/hello-jni//jni/gif.c:840: undefined reference to `AndroidBitmap_lockPixels'
D:/android-ndk-r10/samples/hello-jni//jni/gif.c:847: undefined reference to `AndroidBitmap_unlockPixels'
D:/android-ndk-r10/samples/hello-jni//obj/local/arm64-v8a/objs/gif/gif.o: In function `Java_pl_droidsonroids_gif_GifInfoHandle_seekToFrame':
D:/android-ndk-r10/samples/hello-jni//jni/gif.c:871: undefined reference to `AndroidBitmap_lockPixels'
D:/android-ndk-r10/samples/hello-jni//jni/gif.c:883: undefined reference to `AndroidBitmap_unlockPixels'
D:/android-ndk-r10/samples/hello-jni//obj/local/arm64-v8a/objs/gif/gif.o: In function `Java_pl_droidsonroids_gif_GifInfoHandle_renderFrame':
D:/android-ndk-r10/samples/hello-jni//jni/gif.c:918: undefined reference to `AndroidBitmap_lockPixels'
D:/android-ndk-r10/samples/hello-jni//jni/gif.c:923: undefined reference to `AndroidBitmap_unlockPixels'
collect2.exe: error: ld returned 1 exit status
make.exe: *** [D:/android-ndk-r10/samples/hello-jni//obj/local/arm64-v8a/libgif.so] Error 1

android.mk

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := gif
LOCAL_CFLAGS := -DHAVE_CONFIG_H
LOCAL_SRC_FILES := \
    gif.c \
    giflib/dgif_lib.c \
    giflib/gifalloc.c \

include $(BUILD_SHARED_LIBRARY)

**Comment by koral--** [comment]
You need to add:
`LOCAL_LDLIBS := -ljnigraphics `

**Comment by huangyikai1990** [comment]
Thank you!  Got it ! :+1: )
