### ISSUE TITLE
Run GifDrawable from on bindView

### ISSUE THREAD

**Issue by ammarhameed** [koral--/android-gif-drawable#121]
Hi Koral, 

This is not a bug, I have a question about getting a GIF from SD, I'll be using the below as shown in you usage samples, my question is should can I just use it in the bindView/CursorAdapter without a thread like below? 

                       
                               GifDrawable gifFromPath = new GifDrawable( gifFileOnDisk );
                               image.setImageDrawable(gifFromPath);

**Comment by koral--** [comment]
It depends what do you mean by 'safe'. Constructor of `GifDrawable` performs disk read operation so you will get `StrictModeDiskReadViolation` if you are using `StrictMode` with disk read detection. However only metadata is decoded there, image data is skipped at this step. Probably it is not worth doing a separate thread in most cases.
