### ISSUE TITLE
Gif freezes up after a few hours

### ISSUE THREAD

**Issue by niftynei** [koral--/android-gif-drawable#122]
We're using the GifImageView to display a gif for a long period of time.  After a few hours, it freezes on a frame.  I'm having trouble reproducing it, and looking through the code not sure where to look to debug it.  Any pointers on where to look or what the issue could be? Happy to provide code and/or thread dumps if that's helpful.

**Comment by koral--** [comment]
I assume that you are using the latest library version (1.1.2) and it is not simple I/O failure during animation rewind. Is something printed to logcat when such freezing appears?

I was able to reproduce animation freezing using large GIF on Nexus 7 with Android 5.0.2 (the same app works without freezing on another devices). In such case `OpenGLRenderer Cannot generate texture from bitmap` has been printed to the log. Workaround is to disable hardware canvas eg. by calling `View#setLayerType()` or setting `android:hardwareAccelerated="false"` in manifest.

Is it the same case as yours?

**Comment by niftynei** [comment]
Thank you for investigating. Yes, we're using version 1.1.2, running on an embedded device that's running Android 4.4.

I just confirmed that `E/OpenGLRenderer﹕ Cannot generate texture from bitmap`  is the error we're getting.  Setting the hardware layer to `View.LAYER_TYPE_SOFTWARE` fixes the issue, but seriously degrades the quality of the GIF rendering (there's noticeable tearing and bands of unrendered background (purple)).  With [hardware rendering](https://drive.google.com/a/electricobjects.com/file/d/0B5BbC2GZDCZMelFvRG5TRG9LWXc/view), vs. with [software rendering](https://drive.google.com/a/electricobjects.com/file/d/0B5BbC2GZDCZMVVM2bGdOdER0bVE/view).


I was able to reproduce the freeze a few times now, it seems to happen consistently after ~30 minutes.

**Comment by niftynei** [comment]
I did some digging around on the internet, and managed to find this (forum post)[http://www.developpez.net/forums/d1338782/java/general-java/java-mobiles/android/openglrenderer-cannot-generate-texture-from-bitmap/]. (Warning, it's in French).

**Comment by koral--** [comment]
I've found simpler solution. Please try latest snapshot.

**Comment by niftynei** [comment]
Ok, just saw this. I'll give it a try tomorrow.

**Comment by koral--** [comment]
@niftynei for some reason (bug in framework?) native function `AndroidBitmap_lockPixels` randomly returns `ANDROID_BITMAP_RESULT_ALLOCATION_FAILED`. I introduced a workaround which retries locking at native level several times. If that workaround doesn't work the same frame will be rescheduled to render in the next render pass.
