### ISSUE TITLE
 how to solve the problem of OOM,caused by supersized Gif .

### ISSUE THREAD

**Issue by guqun** [koral--/android-gif-drawable#124]
Thank you very much to maintain the valuable  code,I wonder how to solve the problem of OOM,caused by supersized Gif .example,4096 * 4096

**Comment by koral--** [comment]
There are several solutions:
* enable [largeHeap](http://developer.android.com/guide/topics/manifest/application-element.html#largeHeap) in manifest (available on API 11+)
* divide your app into several processes (using `android:process` in manifest) however it can cause some side effects
* if you have another GifDrawables, Bitmaps or another objects not needed at the same time with that huge GIF, you can try recycling (or nullifying) them

Unfortunately currently there is no feature like [inSampleSize](http://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inSampleSize) and all pixels of the GIF need to be loaded into memory.

**Comment by guqun** [comment]
thanks for your detailed reply,I consider SampleSize is a better method to avoid OOM,As well as SampleSize works great when decoding in my app.Is there have a good way to implement samplesize?

**Comment by koral--** [comment]
Subsampling is basically skipping each `n`-th column and row of the image (where `n` is integral number >=2). Eg. if `n=2` just 1st, 3rd, 5th etc. row and column is read respectively. It looks simple in single bitmap however can be a little bit tricky with GIFs. Here are some caveats:
* each frame can have size different than each other and the canvas (example: http://www.imagemagick.org/Usage/anim_basics/#gif_anim 4 small images are drawn with different offsets on the bigger canvas) so it must be calculated in each frame which rows and columns of that frame should be skipped while subsampling
* pixels can be interlaced (see: https://github.com/koral--/android-gif-drawable/blob/master/src/main/jni/gif.c#L332) so their indexes in source does not always match with final frame buffer

To implement subsampling you have to modify flow of [GifInfo#rasterBits](https://github.com/koral--/android-gif-drawable/blob/master/src/main/jni/gif.h#L77)

**Comment by koral--** [comment]
@guqun you can try (https://github.com/koral--/android-gif-drawable/blob/dev/src/main/java/pl/droidsonroids/gif/GifTextureView.java)[GifTextureView]. Bitmap is not needed there. Available on API 14+.

**Comment by guqun** [comment]
thank you very much! Although there are differences with ImageView, the GifTextureView is a effective way to avoid OOM. I will consider how to behave in the form of GifTextureView  and ImageView is consistent.

**Comment by huyduongtu** [comment]
@guqun Did you find any solution for supporting resize Gif image yet? I'm facing this problem, too.

**Comment by koral--** [comment]
Info for anyone interested in subsampling option: this feature is now available, more info in: https://github.com/koral--/android-gif-drawable/issues/239
