### ISSUE TITLE
LoopCount issue

### ISSUE THREAD

**Issue by DmitriyZaitsev** [koral--/android-gif-drawable#125]
Have a few different gifs in project. Some of them are endless and some of them have loop count = 1.
The problem is they all in app play infinite.

```drawable.getLoopCount()``` returns 0 for all of them.

[Download examples](http://dropmefiles.com/3rhEp)

**Comment by koral--** [comment]
Right, in file `simp_loopcount_1.gif` animation extension is not present so loop count should default to 1 not to infinite.
I'll fix it ASAP.
