### ISSUE TITLE
Doesn't work with Lollipop (permanent crash)

### ISSUE THREAD

**Issue by DmitriyZaitsev** [koral--/android-gif-drawable#127]
I have X-platform code in my app. When I integrated your lib I got such error at startup:

> E/AndroidRuntime( 1771): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[
    [zip file "/data/app/my.package.name-1/base.apk"],nativeLibraryDirectories=[
        /data/app/my.package.name-1/lib/arm,
        /vendor/lib, /system/lib]
    ​]​
] couldn't find "MyLib.so"
E/AndroidRuntime( 1771): at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime( 1771): at java.lang.System.loadLibrary(System.java:989)

**Comment by koral--** [comment]
> couldn't find "MyLib.so"

There is no `MyLib` in `GifDrawable` code. It seems that you somewhere in your code you are trying to load that `.so` file which does not exist.

**Comment by DmitriyZaitsev** [comment]
1) It happens only if I use this android-gif-drawable lib;
2) It happens only on devices with Lollipop installed. Other devices launch the app without problems.

**Comment by koral--** [comment]
Please post complete stacktrace.

**Comment by DmitriyZaitsev** [comment]
Karol, I found that issue is gone when i change
```
ndk {
    // ...
    abiFilter 'all'
}
```
with
```
ndk {
    // ...
    abiFilter 'armeabi'
}
```
