### ISSUE TITLE
v1.1.2 fails on bad file descriptor

### ISSUE THREAD

**Issue by MLinsanity** [koral--/android-gif-drawable#128]
i dont know what's happened,can you help me plz.
v1.1.2 fails on bad file descriptor

**Comment by koral--** [comment]
Got a stacktrace?

**Comment by MLinsanity** [comment]
error opening trace file: No such file or directory (2)
 java.lang.IllegalArgumentException: bad file descriptor
 at android.os.ParcelFileDescriptor.getStatSize(Native Method)
at android.content.res.AssetFileDescriptor.getLength(AssetFileDescriptor.java:106)
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:188)
at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:237)
at pl.droidsonroids.gif.GifImageView.setImageURI(GifImageView.java:131)
I made a condition to test if the file exist before I load gif.the file is exist.

**Comment by MLinsanity** [comment]
```if (gifFile.exists()) {
      gifImageView.setImageURI(Uri.fromFile(gifFile));
      imageViews.add(gifImageView);
} else {
     gifFiles.remove(gifFile);
}
````

**Comment by MLinsanity** [comment]
````
if (gifFile.exists()) {
gifImageView.setImageURI(Uri.fromFile(gifFile));
imageViews.add(gifImageView);
} else {
gifFiles.remove(gifFile);
}
````

**Comment by MLinsanity** [comment]
```
if (gifFile.exists()) {
gifImageView.setImageURI(Uri.fromFile(gifFile));
imageViews.add(gifImageView);
} else {
gifFiles.remove(gifFile);
}
````

**Comment by MLinsanity** [comment]
····
GifDrawable gifFromFile = new GifDrawable(gifFile);
                    gifImageView.setImageDrawable(gifFromFile);
                    imageViews.add(gifImageView);
this way is ok..
····

**Comment by MLinsanity** [comment]
···
GifDrawable gifFromFile = new GifDrawable(gifFile);
gifImageView.setImageDrawable(gifFromFile);
imageViews.add(gifImageView);
this way is ok..
····

**Comment by MLinsanity** [comment]
````  
          if (gifFile.exists()) {
                try {
                    GifDrawable gifFromFile = new GifDrawable(gifFile);
                    gifImageView.setImageDrawable(gifFromFile);
                    imageViews.add(gifImageView);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                gifFiles.remove(gifFile);
            }
````

**Comment by MLinsanity** [comment]
````
            if (gifFile.exists()) {
                try {
                    GifDrawable gifFromFile = new GifDrawable(gifFile);
                    gifImageView.setImageDrawable(gifFromFile);
                    imageViews.add(gifImageView);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                gifFiles.remove(gifFile);
            }
this way is ok.
````

**Comment by koral--** [comment]
Now `GifImageView#setImageURI()` should always work even if source file length could not be determined. In all that cases just -1 will be returned by `#getInputSourceByteCount()` it is the only purpose of source length reading.
Moreover more source kinds now support that feature.
