### ISSUE TITLE
Transparent GIF blinking

### ISSUE THREAD

**Issue by DmitriyZaitsev** [koral--/android-gif-drawable#132]
Hi Karol!
I have transparent GIF. It blinks white every time when first frame plays.

```java
final GifImageView gif = (GifImageView) findViewById(R.id.gif);
final GifDrawableBuilder builder = new GifDrawableBuilder();
final GifDrawable drawable = builder.from(getResources(), R.drawable.sticker_transparent).build();
gif.setImageDrawable(drawable);
```
[Download GIF file](http://dropmefiles.com/4GFWh)

First frame isn't transparent but white. Please review my pull request.

**Comment by koral--** [comment]
Thanks, there was a bug but more than than your changes was needed to fix it.
Erasing buffer to transparency should be done conditionally. GIFs can contain background color which should be used to fill space not covered by image (http://giflib.sourceforge.net/gif89.txt). However I see that most software ignores that color. I've tried several image viewers and web browsers on PC and Mac but only ImageView from Android framework and KDE's Gwenview displayed correct color.
There is test GIF which has green background: https://gist.github.com/koral--/928508453b9276e6be22

Secondly both clearing to transparent and setting a color requires different code than it was.

**Comment by vkedwardli** [comment]
I have got random blinking with a large gif, but issue seems to be fixed when I switched using GifTextureView but not GifImageView

**Comment by koral--** [comment]
In case of attached GIF both views was affected and both are fixed now.
