### ISSUE TITLE
The size of the drawables is changed to smaller when scrolling the ListView

### ISSUE THREAD

**Issue by DmitriyZaitsev** [koral--/android-gif-drawable#136]
Below is the code I use in my adapter's ```getView()```:
```java
if (mGifBuilder == null) {
  mGifBuilder = new GifDrawableBuilder().threadPoolSize(5);
}

try {
  mGifBuilder.from(gifFilePath);
  final Drawable oldDrawable = gifView.getDrawable();

  if (oldDrawable instanceof GifDrawable) {
    mGifBuilder.with((GifDrawable) oldDrawable);
  }

  final Drawable newDrawable = mGifBuilder.build();
  gifView.setImageDrawable(newDrawable);
  viewFlipper.setDisplayedChild(1);
} catch (IOException e) {
  gifView.setImageDrawable(null);
  viewFlipper.setDisplayedChild(0);
  Log.e(TAG, e.getMessage());
}
```
My cells are ```GifImageView```'s with **fixed** dimensions, so layout bounds are always the same. When I scroll up and down sometimes size of drawables inside views changes it's size and they are drawn smaller than before (wider or narrower).
The issue is not observed when I remove following code:
```java
  if (oldDrawable instanceof GifDrawable) {
    mGifBuilder.with((GifDrawable) oldDrawable);
  }
```
I suppose it's related to reusing of frame buffer from other drawable, but I'm not sure. I know only that if I do not use ```mGifBuilder.with((GifDrawable) oldDrawable);``` resizing isn't happen but scrolling isn't smoothy. :(
Reproduced on Nexus 3, Android 4.2, 4.3. Please take a look.
[Sample attached](http://dropmefiles.com/IDCbn)

**Comment by MohamadAtieh** [comment]
Did you try you pausing all GIF's on scroll and resuming them on finish? just a thought

**Comment by DmitriyZaitsev** [comment]
No, I didn't. How do you think these things are related?

**Comment by koral--** [comment]
Scroll is unrelated here. Reason is that custom source `Rect` in `Canvas#drawBitmap()` needs to be specified if not all contents of the `Bitmap` (buffer) is going to be drawn. I'll fix this ASAP.

**Comment by koral--** [comment]
Should work now. Thanks for the report.

**Comment by shiqieren** [comment]
I have the same problem with Android GIF- drawable:1.2.19.
How can I solve the problem of sliding listview becoming smaller.

**Comment by shiqieren** [comment]
I have the same problem with Android GIF- drawable:1.2.19.
How can I solve the problem of sliding listview becoming smaller.
@koral--

**Comment by koral--** [comment]
@shiqieren please create a separate ticket with the snippet reproducing your issue.
