### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by yanglichuan** [koral--/android-gif-drawable#138]
Thanks 
I am using your android-gif-drawable
but have no android.mk  and application.mk

and when compiling  have some errors

**Comment by koral--** [comment]
That files are generated automatically by gradle. If you don't want to use gradle you can create them yourself, see #119 and #85 for more details. All `.c` files need to be present in `LOCAL_SRC_FILES`, look at current `build.gradle` to see what should `LOCAL_LDLIBS` look like.
