### ISSUE TITLE
hi  very thanks 。 if   your android-gif-drawable   can  use in listview  with  universal-image-loader  ？

### ISSUE THREAD

**Issue by yanglichuan** [koral--/android-gif-drawable#139]
if   your android-gif-drawable   can  use in listview  with  universal-image-loader  ？

thank your  android-gif-drawable！
very good！

**Comment by koral--** [comment]
Universal Image Loader supports bitmaps (single-frame images) only so it cannot be used with custom drawables like that.
However there is a planned feature to add asynchronous loading (#113).

**Comment by yanglichuan** [comment]
I hope for it

**Comment by koral--** [comment]
Optionally if you want only display animations and target only on API level 14+ with hardware acceleration you can use `GifTextureView` it has already asynchronous loading.
