### ISSUE TITLE
First frame white when using GifDrawable.draw to draw directly on surface.

### ISSUE THREAD

**Issue by macgrr** [koral--/android-gif-drawable#143]
I'm currently using GifDrawable.draw to draw directly to a Surface.
I have a runnable that draws to a surface at a rate of gif duration / total frames.
The important parts of my code below:
private void draw() {
    SurfaceHolder surfaceHolder = getSurfaceHolder();
    Canvas canvas = surfaceHolder.lockCanvas();
    mGifDrawable.draw(canvas);
    surfaceHolder.unlockCanvasAndPost(canvas);
}

I'm seeing an issue with the attached GIF where on the first frame of the GIF it flashes a white screen.
To be more specific, I'm seeing anything from no white screen (expected behavior) to partial white screen (usually top or bottom) to full white screen.
I created this GIF using GIMP, using animated gif option, 30ms delay, and the rest are default animated gif export settings.

![001](https://cloud.githubusercontent.com/assets/3696805/6976202/1c6bf594-d95b-11e4-806f-04f3776ff82f.gif)

**Comment by koral--** [comment]
It looks like `Canvas` taken from `Surface` can display artifacts if `Bitmap` (`GifDrawable` uses `Bitmap` as frame buffer) which is drawn on it is modified from another thread in the meantime.
You can perform rendering and drawing on the canvas on the same thread by using something like this:
```java
 mExecutorService = new ScheduledThreadPoolExecutor(1);
mGifDrawable = new GifDrawableBuilder().from(<source>).taskExecutor(mExecutorService).build();
```
and schedule your `Runnable` on the same `mExecutorService`.

**Comment by macgrr** [comment]
Thanks, this worked. But I did find a bug with GifDrawableBuilder.
