### ISSUE TITLE
GifDrawableBuilder fails to open animation when passed assetmanager and string

### ISSUE THREAD

**Issue by macgrr** [koral--/android-gif-drawable#144]
Issue found when using function:
public GifDrawableBuilder from(AssetManager assetManager, String assetName)

Using the following fails to open source file:
mGifDrawable = new GifDrawableBuilder().from(assetManager, sourcePath).taskExecutor(mExecutorService).build();

Found fix in InputSource.java, mimicing how GifDrawable opens the same assetmanager/string pair:
diff --git a/src/pl/droidsonroids/gif/InputSource.java b/src/pl/droidsonroids/gif/InputSource.java
index 7808666..00d2749 100644
--- a/src/pl/droidsonroids/gif/InputSource.java
+++ b/src/pl/droidsonroids/gif/InputSource.java
@@ -148,7 +148,7 @@ public abstract class InputSource {
 
         @Override
         GifInfoHandle open() throws IOException {
-            return GifInfoHandle.openAssetFileDescriptor(mAssetManager.openNonAssetFd(mAssetName), false);
+            return GifInfoHandle.openAssetFileDescriptor(mAssetManager.openFd(mAssetName), false);
         }
     }

**Comment by koral--** [comment]
Right, thanks.
