### ISSUE TITLE
Gifs in adapter

### ISSUE THREAD

**Issue by es-andreev** [koral--/android-gif-drawable#148]
I have a listview and corresponding adapter with GifImageViews. Every time new view appears in listview, adapter's imageview is filled with new GifDrawable, and every time view goes off screen, GifDrawable is recycled. Scrolling listview fast to the bottom and back to the top multiple times, I get this in logcat:

04-11 16:33:53.353  23283-23313/com.example.app E/Parcel﹕ Parcel::writeDupFileDescriptor failed:
    fd=1023 flags=0 err=0(Success)
    dupFd=-1 dupErr=24(Too many open files) flags=-1 err=9(Bad file number)
04-11 16:33:53.364  23283-23313/com.example.app E/Surface﹕ queueBuffer: error queuing buffer to SurfaceTexture, -22
04-11 16:33:53.396  23283-23313/com.example.app E/Parcel﹕ dup failed in Parcel::read, fd 0 of 1
    dup(1023) = -1 [errno: 24 (Too many open files)]
    fcntl(1023, F_GETFD) = 1 [errno: 24 (Too many open files)]
    flat 0x0 type 0
04-11 16:33:53.399  23283-23313/com.example.app E/Parcel﹕ Parcel::writeDupFileDescriptor failed:
    fd=1023 flags=0 err=0(Success)
    dupFd=-1 dupErr=24(Too many open files) flags=-1 err=9(Bad file number)
04-11 16:33:53.411  23283-23313/com.example.app E/Surface﹕ queueBuffer: error queuing buffer to SurfaceTexture, -22
04-11 16:33:53.482  23283-23313/com.example.app E/Parcel﹕ dup failed in Parcel::read, fd 0 of 1
    dup(1023) = -1 [errno: 24 (Too many open files)]
    fcntl(1023, F_GETFD) = 1 [errno: 24 (Too many open files)]
    flat 0x0 type 0
04-11 16:33:53.482  23283-23313/com.example.app E/Parcel﹕ Parcel::writeDupFileDescriptor failed:
    fd=1023 flags=0 err=0(Success)
    dupFd=-1 dupErr=24(Too many open files) flags=-1 err=9(Bad file number)
04-11 16:33:53.493  23283-23313/com.example.app E/Surface﹕ queueBuffer: error queuing buffer to SurfaceTexture, -22
04-11 16:33:53.749  23283-23313/com.example.app E/libEGL﹕ call to OpenGL ES API with no current context (logged once per thread)
04-11 16:33:53.750  23283-23313/com.example.app A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x54 in tid 23313 (RenderThread)

**Comment by es-andreev** [comment]
Can it be related to https://github.com/koral--/android-gif-drawable/issues/134?

**Comment by es-andreev** [comment]
Eventually, that was my fault, my apologise.

**Comment by dnutcracker** [comment]
What was the problem? How did you fixed it?

**Comment by es-andreev** [comment]
The issue was related to multithreading, every time view appeared on screen, I started a new thread to show content in GifImageView, but when view gone beyond bounds, the thread did not finish it's job and was left in memory, while another thread was started when this view appeared on screen again. So I fixed the threading issue and the problem gone.

**Comment by dnutcracker** [comment]
Alright. Thanks for the quick response!
