### ISSUE TITLE
how can i show png or jpg with GifDrawable?

### ISSUE THREAD

**Issue by rexi1r** [koral--/android-gif-drawable#149]
GifDrawable not show png or jpg and i need this.i need if i pass png id the GifDrawable method return png drawable and if i pass gif id that return gif drawable.how can i that?can you add this functionality to GifDrawable method?

**Comment by koral--** [comment]
If you want only display that drawable you can just use `GifImageView`/`GifImageButton` it will show `GifDrawable` if resource id is recognized as a GIF. If you want an instance of `Drawable` you can use snippet something like this: https://gist.github.com/koral--/844fae1940dd2c692e7c
