### ISSUE TITLE
call  stop()  can't  start();

### ISSUE THREAD

**Issue by rebadi** [koral--/android-gif-drawable#152]
v1.1.5

**Comment by Kennyc1012** [comment]
I'm also experiencing this with 1.1.5, though I am calling pause(), not stop. The pause() call works however.

**Comment by koral--** [comment]
@rebadi thanks, fixed in the latest snapshot.
@Kennyc1012 only work of `pause()` is calling `stop()`, they both exist because first one is overriden from `MediaPlayerControl` while the second from `Animatable`.
