### ISSUE TITLE
android-gif-drawable no longer support eclipse project?

### ISSUE THREAD

**Issue by ruijun** [koral--/android-gif-drawable#155]
Hello, Koral, android-gif-drawable no longer support eclipse project?

**Comment by koral--** [comment]
There is no support out of the box but you can create eclipse project yourself using existing sources. See several similar issues: https://github.com/koral--/android-gif-drawable/issues/78#issuecomment-51966908 https://github.com/koral--/android-gif-drawable/issues/107#issuecomment-68480471
