### ISSUE TITLE
CRASH: SIGSEGV on particular gif

### ISSUE THREAD

**Issue by Wavesonics** [koral--/android-gif-drawable#157]
This image produces a 100% repro crash:
http://darkrockstudios.com/images/soffishdrawza1.gif

Haven't had time to investigate it my self yet.

This is all I got for the stack trace:

04-21 15:50:39.846: A/libc(18353): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 18466 (pool-7-thread-1)

Also as a note this crash doesn't seem to have been present on older versions of the lib. I'm not sure exactly when it started, but some time before 1.0 it was fine for sure.

**Comment by koral--** [comment]
This issue has been already fixed in 3468553b6c0437c5657e4cd52453efc98d21dda0 and you are right there was a regression that gifs without graphic control block has stopped working.

**Comment by Wavesonics** [comment]
Would it be possible to get a big fix release out? Ive got a release coming up that this is important for.

**Comment by koral--** [comment]
Here you are, should be propagated through maven central in 2 hours.
