### ISSUE TITLE
How can i scale the gif?

### ISSUE THREAD

**Issue by csshuai** [koral--/android-gif-drawable#158]
e.g. :
       the gif image size: 1280 * 720,
       how can i get a Bitmap with size (800 * 600)?

-------------------------
Just like this: 
GifInfoHandle : {
      width = 1280;
      height = 720;
}

Bitmap buffer =  Bitmap.createBitmap(800, 600, Bitmap.Config.ARGB_8888);
GifInfoHandle.renderFrame(buffer);

**Comment by koral--** [comment]
You can use something like this:
```java
        Bitmap currentFrame = gifDrawable.getCurrentFrame();
        Bitmap scaledFrame = Bitmap.createScaledBitmap(currentFrame, 800, 600, true);
```

**Comment by csshuai** [comment]
That used more memory.  There are ways to save memory?

**Comment by koral--** [comment]
In `GifTextureView` you can use [TextureView#getBitmap(int, int)]
(http://developer.android.com/reference/android/view/TextureView.html#getBitmap(int, int))
there is no internal bitmap in such case.

In `GifDrawable` I have no other ideas without modifying library source.
You can change `#getCurrentFrame()` implementation to not make a copy but return internal buffer directly.
Bitmap passed to `#renderFrame()` cannot be smaller than GIF dimensions unless you change native code.

**Comment by csshuai** [comment]
Whether it will provide `#renderFrame()` to get smaller Bitmap function in the future?

**Comment by koral--** [comment]
I have no plan to do such feature myself, but pull requests are welcome.

**Comment by kuabhish** [comment]
> You can use something like this:
> 
> ```java
>         Bitmap currentFrame = gifDrawable.getCurrentFrame();
>         Bitmap scaledFrame = Bitmap.createScaledBitmap(currentFrame, 800, 600, true);
> ```

Hey @koral-- 
Where should I write this code snippet to resize the gif???

**Comment by kuabhish** [comment]
Hey @koral-- 

I made a new class which extends your GifDrawable

```
    public MyGifDrawable(@NonNull File file, int width , int height) throws IOException {
        super(file);
        this.width = width;
        this.height = height;
        this.mDstRect = new Rect(0, 0, this.width, this.height);
    }

    @Override
    public void draw(@NonNull Canvas canvas) {
//        super.draw(canvas);
        Bitmap bmp = getCurrentFrame();
        Rect mSrcRect = new Rect(0, 0, this.width, this.height);
        Bitmap scaledFrame = Bitmap.createScaledBitmap(bmp, this.width, this.height, true);
        canvas.drawBitmap(scaledFrame, mSrcRect, this.mDstRect, mPaint);
    }
```
It looks like this. I am unable to fulfil my needs actually. My code can only resize the image.
How should I resize the canvas?
