### ISSUE TITLE
How to get a bitmap thumbnail from a GifDrawable

### ISSUE THREAD

**Issue by crowbarsolutions** [koral--/android-gif-drawable#161]
Hi,

I am using the latest release 1.1.6 and up until recently I have been using the following code to get a Bitmap so that I can have a preview thumbnail for my GIFs:

        // my GifDrawable
        GifDrawable gifFromBytes = new GifDrawable(fetchGif(Integer.parseInt(imagename), getDbImageBytes(Integer.parseInt(imagename))));
        // I create a new blank Bitmap with the same dimensions as the gif
        Bitmap bs = Bitmap.createBitmap(gifFromBytes.getMinimumWidth(), gifFromBytes.getMinimumHeight(), Bitmap.Config.RGB_565);
        // I create a new canvas and add my bitmap to it
        Canvas c = new Canvas(bs);
        // I start playing my GIF and draw it to the canvas, then get rid of the gifdrawable
        gifFromBytes.start();
        gifFromBytes.draw(c);
        gifFromBytes.recycle();

        ByteArrayOutputStream bAOSThumbnail = new ByteArrayOutputStream();
        // I then compress the resulting bitmap into a ByteArrayOutputStream
        bs.compress(CompressFormat.JPEG, 90 /* ignored for PNG */, bAOSThumbnail);
        // At this point the bitmap will contain the first frame of the Gif

This works in all versions of Android *except* for Android 5.1 where I am returned a blank (completely black) bitmap. I was wondering if there was perhaps a different way of getting a preview bitmap thumbnail from a GifDrawable, or is this a bug in Android?

**Comment by agrajaghh** [comment]
why don't you use `getCurrentFrame()` (I'm not sure if you can call it right after new GifDrawable, or if you have to wait async until the buffer is written) or `seekToFrameAndGet(0)` (which should always work) which will return a `Bitmap`?

**Comment by koral--** [comment]
@crowbarsolutions if you just need a bitmap with particular frame then do as @agrajaghh said, `GifDrawable#seekToFrameAndGet()` is dedicated to do that.
Code from your snippet may not work for at least 2 reasons:
- `gifFromBytes` has no bounds, so will draw nothing on the canvas even if frame buffer contains rendered frame. Initially bounds `Rect` is empty and is set by framework automatically when drawable is assigned to `View`. Bounds can be set explicitly by calling `Drawable#setBounds()`.
- by default rendering is triggered on draw, so when `GifDrawable#draw()` is called first time, nothing is rendered yet so nothing is drawn. First frame is scheduled to be rendered in background thread, after rendering is finished, drawable is invalidated so (if it is visible) draw is called again and rendered frame is drawn.
