### ISSUE TITLE
Unable to work with android-gif-drawable library

### ISSUE THREAD

**Issue by Kris9527** [koral--/android-gif-drawable#163]
Hi,
     I am trying to use android-gif-drawable for my Android project. I downloaded the android-gif-drawable-1.1.6.aar file and unzip it, added classes.jar and .so files to my Eclipse's libs folder. However, I still get the exception. How can I add that to my project correctly?

05-06 12:20:18.737: E/AndroidRuntime(16680): FATAL EXCEPTION: main
05-06 12:20:18.737: E/AndroidRuntime(16680): Process: com.example.test, PID: 16680
05-06 12:20:18.737: E/AndroidRuntime(16680): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.example.test.MainActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.ActivityThread.access$800(ActivityThread.java:141)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.os.Looper.loop(Looper.java:136)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.ActivityThread.main(ActivityThread.java:5047)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at dalvik.system.NativeStart.main(Native Method)
05-06 12:20:18.737: E/AndroidRuntime(16680): Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class pl.droidsonroids.gif.GifImageView
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:710)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.Activity.setContentView(Activity.java:1947)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at com.example.test.MainActivity.onCreate(MainActivity.java:13)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.Activity.performCreate(Activity.java:5249)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	... 11 more
05-06 12:20:18.737: E/AndroidRuntime(16680): Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.GifImageView" on path: DexPathList[[zip file "/data/app/com.example.test-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.test-2, /vendor/lib, /system/lib]]
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.view.LayoutInflater.createView(LayoutInflater.java:562)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:699)
05-06 12:20:18.737: E/AndroidRuntime(16680): 	... 21 more

**Comment by agrajaghh** [comment]
best way is to add this to `build.gradle`:
```` 
dependencies {
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.6'
}
````

**Comment by Kris9527** [comment]
Thanks for your reply, but my IDE is eclipse, I want to use the classes.jar and lib.so to support my project as simple as possible, How can I add that to my project correctly?

**Comment by koral--** [comment]
See #155.

**Comment by Kris9527** [comment]
Thank you for your help！
