### ISSUE TITLE
Gif Loop

### ISSUE THREAD

**Issue by GiusWhite** [koral--/android-gif-drawable#164]
Hi all.
The gif is shown properly, but is not looped.
How I can make it indeterminate?

**Comment by koral--** [comment]
Loop count from GIF file should be respected.
Could you post example of file which is not looping properly?

**Comment by GiusWhite** [comment]
I have this simple layout element:
```
<pl.droidsonroids.gif.GifImageView
                android:id="@+id/gif_home"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentTop="true"
                android:adjustViewBounds="true"
                android:elevation="6dp"
                android:layout_marginTop="12dp"
                android:layout_centerHorizontal="true"
                android:src="@drawable/video_home" />
```

The file video_home.gif is a normal gif :confused:

**Comment by koral--** [comment]
Please attach that `video_home.gif` file here.

**Comment by koral--** [comment]
There is no loop count defined in that file so it defaults to 1. This is intended behavior and most software like image viewers or web browsers behave the same.

However I can add method like `GifDrawable#setLoopCount(int)` which can be used to overwrite loop count from GIF file. 0 means infinite loop.

**Comment by GiusWhite** [comment]
I think it may be useful to other people

**Comment by DmitriyZaitsev** [comment]
@GiusWhite, you can use ```GifDrawable.addAnimationListener()``` method and restart playing the GIF when ```onAnimationCompleted()``` callback is called.

**Comment by koral--** [comment]
Right, restart in `onAnimationCompleted()` is a solution available in current release. Additionally `GifDrawable#setLoopCount(int)` is availiable from the current snapshot.

**Comment by DoM4** [comment]
I am using the gif view in a view pager. I can see it but cannot loop it.
This is my code 

GifDrawable tooltips_add = null;
        GifDrawable tooltips_drag = null;
        GifDrawable tooltips_dashboard = null;
        try {


            if(page.equalsIgnoreCase("my_channels")) {
                System.out.println("tooltips position: " + position);

                if(position == 0)
                {
                    tooltips_add = new GifDrawable(context.getResources(), R.drawable.tooltip_add);
                }else
                {
                    tooltips_drag = new GifDrawable(context.getResources(), R.drawable.tooltip_drag);
                }
             }else if(page.equalsIgnoreCase("dashboard"))
            {
                tooltips_dashboard = new GifDrawable(context.getResources(), R.drawable.tooltip_channels);
            }
        } catch (IOException e) {
            System.out.println("error tooltips : " + e.getMessage().toString());
        }

        if(tooltips_dashboard != null)
        {

            final GifDrawable finalTooltips_dashboard = tooltips_dashboard;
            tooltips_dashboard.addAnimationListener(new AnimationListener() {
                @Override
                public void onAnimationCompleted() {
                    System.out.println("onAnimationCompleted");
                    finalTooltips_dashboard.start();
                }
            });
        }

onAnimationCompleted doesn't get called

**Comment by koral--** [comment]
@DoM4 I reopened #166 for your issue.

**Comment by SubhashGaikwad** [comment]
How to write code for feting gif url from network using GifDrawable ? I am unable see in you docs ? I am new in Android dev. Please help me! at lease pseudo code steps.

**Comment by koral--** [comment]
@SubhashGaikwad there is an example in sample project: https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.kt

**Comment by SubhashGaikwad** [comment]
okay! thank you sir ! but i want play gif in recyclerview as an cell item. for that which is the best approach.
