### ISSUE TITLE
How to make an endless cycle

### ISSUE THREAD

**Issue by DoM4** [koral--/android-gif-drawable#166]
Is there a way to make the gif image restart when animation finish?

**Comment by koral--** [comment]
See https://github.com/koral--/android-gif-drawable/issues/164#issuecomment-99534606

**Comment by koral--** [comment]
https://github.com/koral--/android-gif-drawable/issues/164#issuecomment-101311629

**Comment by koral--** [comment]
@DoM4 code similar to yours is working for me. 
To restart animation you have to call `reset()` not `start()` in `onAnimationCompleted()`.
If it does not help please attach `tooltip_channels` GIF here.

**Comment by DoM4** [comment]
It doesn't work for me. I've fixed the problem by asking the designer to make the gif endless.

**Comment by koral--** [comment]
As can be see here: https://github.com/koral--/android-gif-drawable/blob/master/src/main/java/pl/droidsonroids/gif/RenderTask.java#L35 `onAnimationCompleted()` is fired after last frame is rendered. 
If it isn't then for some reason either last frame is not reached for some reason or listener is removed.

Post more info and reopen this issue if you are interested in explaining that.

**Comment by SinghLucky** [comment]
Hi Koral
 i want to repeat gif in GIFImageView

**Comment by koral--** [comment]
@SinghLucky, assuming that you want infinite repeat count, you can do something like this:
```java
GifDrawable gifDrawable = (GifDrawable) gifImageView.getDrawable();
gifDrawable.setLoopCount(0);
```
BTW that should be located in separate issue.

**Comment by bhavik0919** [comment]
GifDrawable gifDrawable = (GifDrawable) gifImageView.getDrawable();
gifDrawable.setLoopCount(0);   
i used this two line but it is not working

**Comment by bhavik0919** [comment]
GifDrawable gifDrawable = (GifDrawable) gifImageView.getDrawable();
gifDrawable.setLoopCount(0);  
Thank's It Working Fine
