### ISSUE TITLE
the latest version has visual issue with animated GIF drawable

### ISSUE THREAD

**Issue by raylee4204** [koral--/android-gif-drawable#167]
I use a GIFDrawable as a menu item in the actionbar, and the latest version has the visual issue you can see in the screenshot when animating. 

![screenshot_2015-05-15-11-14-24](https://cloud.githubusercontent.com/assets/2085389/7657994/750c8a04-fb04-11e4-8419-7f851deb51c5.png)

**Comment by koral--** [comment]
Could you attach that affected GIF?

**Comment by raylee4204** [comment]
![soundwave](https://cloud.githubusercontent.com/assets/2085389/7660008/771fbe32-fb14-11e4-99b2-972defd9061d.gif)

**Comment by koral--** [comment]
Fixed, thanks for the report.

**Comment by raylee4204** [comment]
@koral-- I noticed this issue is also in 1.1.5. In what version did the issue appear?

**Comment by koral--** [comment]
It seems that affected versions are 1.1.3 to 1.1.6. Bug is fixed in 1.1.7.
