### ISSUE TITLE
FATAL EXCEPTION: main in Android 5.0.2

### ISSUE THREAD

**Issue by lindesu** [koral--/android-gif-drawable#170]
I run the sample, it seem to lost something.

I'm tracking down a crash in the native side.

05-26 08:08:47.350: E/AndroidRuntime(22222): android.view.InflateException: Binary XML file line #2: Error inflating class pl.droidsonroids.gif.GifTextView
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at pl.droidsonroids.gif.sample.GifTextViewFragment.onCreateView(GifTextViewFragment.java:12)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:486)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.View.measure(View.java:17810)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.View.measure(View.java:17810)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:963)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.View.measure(View.java:17810)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5625)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2668)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.View.measure(View.java:17810)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2371)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1386)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1610)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6487)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.Choreographer.doFrame(Choreographer.java:572)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.os.Handler.handleCallback(Handler.java:815)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.os.Handler.dispatchMessage(Handler.java:104)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.os.Looper.loop(Looper.java:194)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.app.ActivityThread.main(ActivityThread.java:5576)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at java.lang.reflect.Method.invoke(Native Method)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
05-26 08:08:47.350: E/AndroidRuntime(22222): Caused by: java.lang.reflect.InvocationTargetException
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at java.lang.reflect.Constructor.newInstance(Native Method)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	... 42 more
05-26 08:08:47.350: E/AndroidRuntime(22222): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lpl/droidsonroids/gif/R$styleable;
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at pl.droidsonroids.gif.GifViewUtils.isFreezingAnimation(GifViewUtils.java:66)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at pl.droidsonroids.gif.GifTextView.init(GifTextView.java:112)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at pl.droidsonroids.gif.GifTextView.<init>(GifTextView.java:44)
05-26 08:08:47.350: E/AndroidRuntime(22222): 	... 45 more
05-26 08:08:47.350: E/AndroidRuntime(22222): Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.R$styleable" on path: DexPathList[[zip file "/data/app/pl.droidsonroids.gif.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/pl.droidsonroids.gif.sample-1/lib/arm64, /vendor/lib64, /system/lib64]]
05-26 08:08:47.350: E/AndroidRuntime(22222): 	at dalvik.syste

**Comment by koral--** [comment]
It looks like you have outdated submodule. Try running `git submodule update`.

**Comment by lindesu** [comment]
I can't compile the source. I download the release 1.1.7

**Comment by lindesu** [comment]
I think the problem is in the "GifViewUtils.isFreezingAnimation". Can you check the method in line 66 ? You use the R file that is in your project's .

crashing...

05-26 14:10:30.112: E/AndroidRuntime(29644): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lpl/droidsonroids/gif/R$styleable;
05-26 14:10:30.112: E/AndroidRuntime(29644): 	at pl.droidsonroids.gif.GifViewUtils.isFreezingAnimation(GifViewUtils.java:66)
05-26 14:10:30.112: E/AndroidRuntime(29644): 	at pl.droidsonroids.gif.GifTextView.init(GifTextView.java:112)
05-26 14:10:30.112: E/AndroidRuntime(29644): 	at pl.droidsonroids.gif.GifTextView.<init>(GifTextView.java:44)
05-26 14:10:30.112: E/AndroidRuntime(29644): 	... 45 more
05-26 14:10:30.112: E/AndroidRuntime(29644): Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.R$styleable" on path: DexPathList[[zip file "/data/app/pl.droidsonroids.gif.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/pl.droidsonroids.gif.sample-1/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by koral--** [comment]
What did you download? sources jar or aar? That styleable referneced in `GifViewUtils.java:66` is located here https://github.com/koral--/android-gif-drawable/blob/master/src/main/res/values/attrs.xml and present in AAR.

**Comment by lindesu** [comment]
I download aar. And I put the values.xml into res/values. When I put the attrs.xml into res/values. It report error "error: Attribute "freezesAnimation" has already been defined"

**Comment by lindesu** [comment]
I think the values.xml and attrs.xml is the same file with different name

**Comment by koral--** [comment]
Interesting, what version of gradle and android gradle plugin (that defined in top-level `build.gradle` file) are you using?
In my last post, I didn't say it precisely but I meant that file with that styleable is present. In sources it is called `attrs.xml` but after compiling, in AAR it is `values.xml` (content is the same).

**Comment by lindesu** [comment]
I don't use android studio. I use eclipse with adt. Is it the problem? I don't know why crash <Didn't find class "pl.droidsonroids.gif.R$styleable">. It seems can't find pl.droidsonroids.gif.R. I don't know how to do... Are you sure it doesn't matter?

**Comment by koral--** [comment]
Yes, it definitely matters. With android studio/gradle everything is working.
It looks like that XML is not compiled into R class and/or that class lands in wrong package. I don't use eclipse now but AFAIK you should create eclipse library project and place that XML file in `res/values`, package name in library manifest should be `pl.droidsonroids.gif`

**Comment by lindesu** [comment]
well , it work , thanks

**Comment by koral--** [comment]
I see that many people is still using eclipse, maybe some tutorial for it should be made? I'll create issue for that.

**Comment by lindesu** [comment]
OK. As you say, create eclipse library project and place that XML file in res/values, package name in library manifest should be pl.droidsonroids.gif, then it works

**Comment by yqpan1991** [comment]
I encounter problem like this , then I solved by myself, When using eclipse,
1. please import folder after you unzipped  aar as a project
2.move jni to libs 
3. clean this project 
4. make it as a library
5. import this library to your project
6. done!

**Comment by jiangchao1987** [comment]
yeah, it works.@yqpan1991

**Comment by yuanfangCBC** [comment]
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 31598 (f_drawable_demo)  
5.0 android How to do?

**Comment by koral--** [comment]
@yuanfangCBC please post full stacktrace in another issue

**Comment by tabishhussain** [comment]
what is jni ??? @yqpan1991

**Comment by koral--** [comment]
How to for eclipse: https://github.com/koral--/android-gif-drawable-eclipse-sample

**Comment by yuanfangCBC** [comment]
@koral--  Has been solved,thank you.
