### ISSUE TITLE
how to build the jni source to ".so" file

### ISSUE THREAD

**Issue by naiyu** [koral--/android-gif-drawable#172]
I try to build the jni source to ".so" file, but failed, because there is no any Android.mk or Application file, and I don't know how to edit them.

**Comment by koral--** [comment]
`Android.mk` is generated by gradle plugin. Assuming that it is placed in `jni` folder, It should look like this:
```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := pl_droidsonroids_gif
LOCAL_CFLAGS := -fvisibility=hidden -Ofast -finline-functions
LOCAL_LDLIBS := \
	-ljnigraphics \
	-landroid \

LOCAL_SRC_FILES := \
	bitmap.c \
	decoding.c \
	memset32_neon.S \
	drawing.c \
	memset.arm.S \
	metadata.c \
	time.c \
	open_close.c \
	surface.c \
	gif.c \
	control.c \
	exception.c \
	giflib/gifalloc.c \
	giflib/dgif_lib.c \

include $(BUILD_SHARED_LIBRARY)
```

**Comment by Catherine0728** [comment]
Similar to the upstairs, I do not know how to create the Android.mk file in the project, each time it was copied from other projects! There is no weapon?

**Comment by koral--** [comment]
Gradle is a weapon, it automatically creates `Android.mk` based on contents of `src/main/jni` and `build.gradle`.
