### ISSUE TITLE
Cannot load library on 2.2.x

### ISSUE THREAD

**Issue by arielch** [koral--/android-gif-drawable#173]
The library cannot be loaded on some devices, all reports so far are on devices with Froyo, Android 2.2.x, API Level 8.
This is also reproducible on the emulator with Nexus 4 API Level 8 armeabi:

05-26 22:26:44.253      324-324/org.arielch.gifdrawabledemo I/dalvikvm﹕ Could not find method android.graphics.Bitmap.getAllocationByteCount, referenced from method pl.droidsonroids.gif.GifDrawable.getAllocationByteCount
05-26 22:26:44.253      324-324/org.arielch.gifdrawabledemo W/dalvikvm﹕ VFY: unable to resolve virtual method 475: Landroid/graphics/Bitmap;.getAllocationByteCount ()I
05-26 22:26:44.253      324-324/org.arielch.gifdrawabledemo D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x000e
05-26 22:26:44.253      324-324/org.arielch.gifdrawabledemo D/dalvikvm﹕ VFY: dead code 0x0011-0013 in Lpl/droidsonroids/gif/GifDrawable;.getAllocationByteCount ()J
05-26 22:26:44.263      324-324/org.arielch.gifdrawabledemo D/dalvikvm﹕ Trying to load lib /data/data/org.arielch.gifdrawabledemo/lib/libpl_droidsonroids_gif.so 0x4a69ac90
05-26 22:26:44.263      324-324/org.arielch.gifdrawabledemo I/dalvikvm﹕ Unable to dlopen(/data/data/org.arielch.gifdrawabledemo/lib/libpl_droidsonroids_gif.so): Cannot load library: link_image[1995]: failed to link libpl_droidsonroids_gif.so
05-26 22:26:44.263      324-324/org.arielch.gifdrawabledemo W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown during Lpl/droidsonroids/gif/GifInfoHandle;.<clinit>
05-26 22:26:44.263      324-324/org.arielch.gifdrawabledemo D/AndroidRuntime﹕ Shutting down VM
05-26 22:26:44.263      324-324/org.arielch.gifdrawabledemo W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4001d800)
05-26 22:26:44.283      324-324/org.arielch.gifdrawabledemo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
            at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:145)
            at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:83)
            at org.arielch.gifdrawabledemo.EmoticonManager.getDrawable(EmoticonManager.java:112)

**Comment by koral--** [comment]
OK, current library version is working on API 9+ only. I'll try to fix it ASAP.

**Comment by koral--** [comment]
API 8 is supported in version 1.1.8-SNAPSHOT.
