### ISSUE TITLE
android textview.setText(spanned) unsupported!

### ISSUE THREAD

**Issue by treasure-lau** [koral--/android-gif-drawable#174]
gif image put in &lt;img&gt; tag,no effect.thanks!

**Comment by koral--** [comment]
If your `Spanned` contains `ImageSpan` with `GifDrawable`(s) and you set `Callback` to that drawables, it will work, see #83 and gist linked there.

**Comment by koral--** [comment]
There was a lack in linked sample, now it is updated, see #175 for more details.
