### ISSUE TITLE
GifDrawable as a ImageSpan in Textview

### ISSUE THREAD

**Issue by dss886** [koral--/android-gif-drawable#175]
I noticed [issues #83](83) and the [Example for issues #83](https://gist.github.com/koral--/accde6deea1c59d58481), but it didn't work when I tried. 

I use the same code as the example in the adapter of my listview, but it only shows "tst" ('e' disappeared)

debug after initial the GifDrawable, I found the bounds is "0, 0, -0, 0", Did I do something wrong?

![image](https://cloud.githubusercontent.com/assets/5170950/7901317/39294394-07b4-11e5-9b00-4eca2222269a.png)

**Comment by koral--** [comment]
That example has been written some time ago and did not match current rules, I forgot to update it. I've updated sample project ([ImageSpanFragment](https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/ImageSpanFragment.java) added) and code in linked gist.

Now `GifDrawable` initially has no bounds like drawables from Android framework (eg. `BitmapDrawable`). In most cases bounds are set by container in which drawable is located eg. `ImageView` and are based also on factors other than image size (eg. scale type).

In custom usage cases like that with `ImageSpan` you need to set bounds on your own eg. like this: `gifDrawable.setBounds(0, 0, gifDrawable.getIntrinsicWidth(), gifDrawable.getIntrinsicHeight());` (you can use different values to achieve scaling etc.).

**Comment by dss886** [comment]
It works, thanks~
