### ISSUE TITLE
Activity Not Responding

### ISSUE THREAD

**Issue by Kennyc1012** [koral--/android-gif-drawable#178]
I have been experiencing issues lately within my app that I believe is caused by this library, but I am unable to pin point the exact issue. 

In my scenario, a user can swipe between pages (view pager pattern) of gifs. When the fragments are not visible, a thumbnail is used before the gif is loaded for display purposes. Once the fragment becomes visible, the gif is then loaded and displayed. The ANR occurs after swiping through many pages (I was testing on an album of 43 gifs) and the GC attempts to runs. I can confirm this is the GC causing the ANR as if I try to force a GC in Android Studio, the same result occurs. The output from the logs stated that there was a thread thread timeout libart.so and libc.so, I didn't grab logs, but I will try to replicate it again and attach.

If I stop the gifs from loading in the viewpager, this issue does not exist which leads me to believe they are the root cause of it. 

Edit: This was experienced on a Nexus 6 running 5.1.1

**Comment by Kennyc1012** [comment]
Logs:

06-04 20:54:59.907     888-1100/? I/InputDispatcher﹕ Application is not responding: Window{9be8050 u0 com.kennyc.open.imgur/com.kenny.openimgur.activities.FullScreenPhotoActivity}.  It has been 5006.0ms since event, 5005.6ms since wait started.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 7.  Wait queue head age: 23040.7ms.
06-04 20:54:59.910     888-1100/? I/WindowManager﹕ Input event dispatching timed out sending to com.kennyc.open.imgur/com.kenny.openimgur.activities.FullScreenPhotoActivity.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 7.  Wait queue head age: 23040.7ms.
06-04 20:54:59.931      888-908/? I/Process﹕ Sending signal. PID: 22744 SIG: 3
06-04 20:54:59.931  22744-22753/com.kennyc.open.imgur I/art﹕ Thread[5,tid=22753,WaitingInMainSignalCatcherLoop,Thread*=0xaef0e400,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3
06-04 20:54:59.931  22744-22753/com.kennyc.open.imgur I/art﹕ [ 06-04 20:54:59.999   888: 1099 V/AlarmManager ]
    findRtcWakeupBatchLocked false
06-04 20:55:00.008     888-1099/? D/PowerManagerService﹕ acquireWakeLockInternal: lock=505418080, flags=0x40000001, tag="*alarm*", ws=WorkSource{1000}, uid=1000, pid=888
06-04 20:55:00.131      888-908/? I/Process﹕ Sending signal. PID: 888 SIG: 3
06-04 20:55:00.132      888-896/? I/art﹕ Thread[5,tid=896,WaitingInMainSignalCatcherLoop,Thread*=0xaef0e400,peer=0x12c02080,"Signal Catcher"]: reacting to signal 3
06-04 20:55:00.132      888-896/? I/art﹕ [ 06-04 20:55:01.025 23314:23314 E/QCOMSysDaemon ]
    Can't open /dev/block/platform/msm_sdcc.1/by-name/bootselect: (No such file or directory)
06-04 20:55:01.025  23314-23314/? I/QCOMSysDaemon﹕ Starting qcom system daemon
06-04 20:55:01.025  23314-23314/? E/Diag_Lib﹕ Diag_LSM_Init: Failed to open handle to diag driver, error = 2
06-04 20:55:01.025  23314-23314/? E/QCOMSysDaemon﹕ Diag_LSM_Init failed : 0
06-04 20:55:01.337     888-2581/? E/WifiHAL﹕ Error polling socket
06-04 20:55:01.474      888-908/? I/Process﹕ Sending signal. PID: 1476 SIG: 3
06-04 20:55:01.474    1476-1494/? I/art﹕ Thread[5,tid=1494,WaitingInMainSignalCatcherLoop,Thread*=0xaef0e400,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3
06-04 20:55:01.475    1476-1494/? I/art﹕ [ 06-04 20:55:01.484   888:  896 I/art      ]
    Wrote stack traces to '/data/anr/traces.txt'
06-04 20:55:01.484      888-908/? I/Process﹕ Sending signal. PID: 1453 SIG: 3
06-04 20:55:01.484    1453-1482/? I/art﹕ Thread[5,tid=1482,WaitingInMainSignalCatcherLoop,Thread*=0xaef0e400,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3
06-04 20:55:01.484    1453-1482/? I/art﹕ [ 06-04 20:55:01.585  1476: 1494 I/art      ]
    Wrote stack traces to '/data/anr/traces.txt'
06-04 20:55:01.585      888-908/? I/Process﹕ Sending signal. PID: 1442 SIG: 3
06-04 20:55:01.585    1442-1462/? I/art﹕ Thread[5,tid=1462,WaitingInMainSignalCatcherLoop,Thread*=0xaef0e400,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3
06-04 20:55:01.585    1442-1462/? I/art﹕ [ 06-04 20:55:01.693  1442: 1462 I/art      ]
    Wrote stack traces to '/data/anr/traces.txt'
06-04 20:55:01.694      888-908/? I/Process﹕ Sending signal. PID: 1427 SIG: 3
06-04 20:55:01.694    1427-1438/? I/art﹕ Thread[5,tid=1438,WaitingInMainSignalCatcherLoop,Thread*=0xaef0e400,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3
06-04 20:55:01.694    1427-1438/? I/art﹕ [ 06-04 20:55:01.717  1453: 1482 I/art      ]
    Wrote stack traces to '/data/anr/traces.txt'
06-04 20:55:01.717      888-908/? I/Process﹕ Sending signal. PID: 1263 SIG: 3
06-04 20:55:01.717    1263-1284/? I/art﹕ Thread[5,tid=1284,WaitingInMainSignalCatcherLoop,Thread*=0xaef0e400,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3
06-04 20:55:01.717    1263-1284/? I/art﹕ [ 06-04 20:55:01.762  1427: 1438 I/art      ]
    Wrote stack traces to '/data/anr/traces.txt'
06-04 20:55:02.084    1263-1284/? I/art﹕ Wrote stack traces to '/data/anr/traces.txt'
06-04 20:55:03.719      888-908/? I/art﹕ Explicit concurrent mark sweep GC freed 73872(3MB) AllocSpace objects, 14(545KB) LOS objects, 33% free, 18MB/27MB, paused 944us total 61.598ms
06-04 20:55:04.283      888-908/? E/ActivityManager﹕ ANR in com.kennyc.open.imgur (com.kennyc.open.imgur/com.kenny.openimgur.activities.FullScreenPhotoActivity)
    PID: 22744
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 7.  Wait queue head age: 23040.7ms.)
    Load: 11.31 / 11.23 / 14.08
    CPU usage from 9689ms to 0ms ago:
    97% 22744/com.kennyc.open.imgur: 97% user + 0% kernel
    1.7% 888/system_server: 0.9% user + 0.8% kernel / faults: 90 minor
    1% 278/adbd: 0% user + 1% kernel / faults: 1355 minor
    0.9% 476/sensors.qcom: 0.3% user + 0.6% kernel / faults: 4 minor
    0.5% 22947/kworker/u:5: 0% user + 0.5% kernel
    0.3% 1866/mpdecision: 0% user + 0.3% kernel
    0.3% 1910/RX_Thread: 0% user + 0.3% kernel
    0.3% 32248/kworker/u:2: 0% user + 0.3% kernel
    0.2% 2132/kworker/0:0: 0% user + 0.2% kernel
    0.2% 18961/kworker/u:1: 0% user + 0.2% kernel
    0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
    0.1% 7/kworker/u:0H: 0% user + 0.1% kernel
    0.1% 125/irq/636-LCD_TE: 0% user + 0.1% kernel
    0% 196/mmcqd/0: 0% user + 0% kernel
    0.1% 228/logd: 0.1% user + 0% kernel
    0% 229/healthd: 0% user + 0% kernel
    0.1% 233/surfaceflinger: 0% user + 0.1% kernel
    0.1% 1263/com.android.systemui: 0% user + 0.1% kernel / faults: 3 minor
    0% 1587/com.google.android.gms: 0% user + 0% kernel / faults: 5 minor
    0% 3245/com.google.android.youtube: 0% user + 0% kernel / faults: 29 minor
    0.1% 7063/kworker/0:2H: 0% user + 0.1% kernel
    0.1% 19131/ksoftirqd/3: 0% user + 0.1% kernel
    53% TOTAL: 50% user + 3% kernel
    CPU usage from 3802ms to 4323ms later:
    96% 22744/com.kennyc.open.imgur: 96% user + 0% kernel
    98% 22759/GCDaemon: 98% user + 0% kernel
    7.5% 888/system_server: 0% user + 7.5% kernel
    5.6% 908/ActivityManager: 0% user + 5.6% kernel
    1.8% 899/FinalizerDaemon: 1.8% user + 0% kernel
    1.3% 278/adbd: 0% user + 1.3% kernel / faults: 83 minor
    1.3% 278/adbd: 0% user + 1.3% kernel
    1.3% 476/sensors.qcom: 1.3% user + 0% kernel
    1.3% 909/sensors.qcom: 1.3% user + 0% kernel
    1.5% 7063/kworker/0:2H: 0% user + 1.5% kernel
    1.5% 19133/kworker/3:1H: 0% user + 1.5% kernel
    1.6% 32248/kworker/u:2: 0% user + 1.6% kernel
    53% TOTAL: 50% user + 2.9% kernel
06-04 20:55:04.292    888-23348/? E/ActivityManager﹕ Error reading /data/anr/traces.txt
    java.io.FileNotFoundException: /data/anr/traces.txt: open failed: ENOENT (No such file or directory)
            at libcore.io.IoBridge.open(IoBridge.java:456)
            at java.io.FileInputStream.<init>(FileInputStream.java:76)
            at android.os.FileUtils.readTextFile(FileUtils.java:228)
            at com.android.server.am.ActivityManagerService$20.run(ActivityManagerService.java:12052)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
            at libcore.io.IoBridge.open(IoBridge.java:442)
            at java.io.FileInputStream.<init>(FileInputStream.java:76)
            at android.os.FileUtils.readTextFile(FileUtils.java:228)
            at com.android.server.am.ActivityManagerService$20.run(ActivityManagerService.java:12052)


Here is a screen shot of the memory heap, as you can see, there is very little memory that has been allocated, the device (one plus one in this case) can easily handle another 50+ mb of memory

![screen shot 2015-06-04 at 8 54 36 am](https://cloud.githubusercontent.com/assets/2333025/7984472/a2b9a0fc-0a97-11e5-83a0-1a98244f92a7.png)

**Comment by koral--** [comment]
I could not reproduce ANR with ViewPager. Could you post ANR trace? It looks like that: `https://github.com/nostra13/Android-Universal-Image-Loader/issues/848#issue-52219935`

**Comment by Kennyc1012** [comment]
The ANR trace is posted above,

 06-04 20:54:59.910 888-1100/? I/WindowManager﹕ Input event dispatching timed out sending to com.kennyc.open.imgur/com.kenny.openimgur.activities.FullScreenPhotoActivity. Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 7. Wait queue head age: 23040.7ms.

**Comment by koral--** [comment]
As trace I mean call stack. Eg. from linked example:
```
 at java.lang.Object.wait(Native Method)
 (...)
  at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:259)
  at com.taole.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
(...)```
The last line is the key part. Because it contains the last call in library code.
It is important to determine where exactly (at which line of library code) ANR occured. That what you posted does not contain such infromation.

**Comment by Kennyc1012** [comment]
I can't seem to reproduce this anymore, and there are have been no reports of ANRS or user feedback suggesting such for my app so I will close this, thanks for your help.
