### ISSUE TITLE
Gif Jni NDK-BUILD

### ISSUE THREAD

**Issue by 10045125** [koral--/android-gif-drawable#179]
Hello,How to compile JNI, no Android.mk?Thanks.

**Comment by androidbyxj** [comment]
I am downloading *android-gif-drawable-1.1.7.aar
<https://github.com/koral--/android-gif-drawable/releases/download/v1.1.7/android-gif-drawable-1.1.7.aar>,*Then
unzip the file, access to the JNI documentation and class.jar.And then
imported into eclipse projects.The structure of the lib screenshots are as
follows:

​I didn't use the NDK to compile.Thank you for your reply





2015-06-09 11:39 GMT+08:00 伍中联 <notifications@github.com>:

**Comment by koral--** [comment]
See #172
