### ISSUE TITLE
seekToFrame when paused isn't paused

### ISSUE THREAD

**Issue by dangalg** [koral--/android-gif-drawable#180]
I want to be able to control seeking backwards and forwards by by passing the frame number. is this possible?

my code:

        contourLineGif = new GifDrawable(getResources(), R.drawable.contour_line);
        GifHandler.showGifDrawable(contourLineGif, contourLine, mMultiCallback);
          
        contourLineGif.stop();
        setContourLine(0);

    private void setContourLine(final int seek) {
        contourLineGif.seekToFrame(seek);

    }

    public static void showGifDrawable(GifDrawable gif, ImageView imageView, MultiCallback        mMultiCallback) {
           final Drawable item = gif;
           imageView.setImageDrawable(item);
           mMultiCallback.addView(imageView);
            if(item != null) {
                item.setCallback(mMultiCallback);
            }
        }

    if(status == BGStatusEnum.LOOKING_GOOD.getValue()){
            // advance green silhouette according to bgSameBGStatusCounter number
            contourLineFrame++;
            if(contourLineFrame > contorLineMaxFrame){contourLineFrame = contorLineMaxFrame;}
            else{
                if(contourLineFrame < contorLineMaxFrame) {
                    setContourLine(contourLineFrame);
                }
            }
        }else{
            // advance green silhouette according to bgSameBGStatusCounter number
            // by the percentage of how many times this has been the same
            contourLineFrame--;
            if(contourLineFrame < 0){contourLineFrame = 0;}
            else{
                if(contourLineFrame > 0) {
                    setContourLine(contourLineFrame);
                }
            }

        }
this causes flashes and looks like a big mess...

**Comment by koral--** [comment]
Seeking when paused should be possible. I'll check this.

**Comment by dangalg** [comment]
Do you need anymore info from me on this issue?

**Comment by koral--** [comment]
I think no, I was able to reproduce it and will fix it ASAP.

**Comment by dangalg** [comment]
Great!

**Comment by koral--** [comment]
Seeking when paused should work properly in 1.1.8-SNAPSHOT.

**Comment by dangalg** [comment]
I'm testing it

**Comment by dangalg** [comment]
I put compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.8-SNAPSHOT' in the gradle, gave me an error

**Comment by koral--** [comment]
You need to add maven snapshot repository in `build.gradle`:
`maven{ url('https://oss.sonatype.org/content/repositories/snapshots')}`
