### ISSUE TITLE
Support resizing according to device density

### ISSUE THREAD

**Issue by dors** [koral--/android-gif-drawable#181]
Placing the gif in drawable-xxhdpi and running on an hdpi device does not scale down the gif.

For example, placing a 600x600 image in xxhdpi and running the apk on an hdpi device should load the image as a 300x300 image.
However, using the lib, placing a 600x600px gif in drawable-xxhdpi and running the app on an hdpi device will load and show a 600x600px gif.

**Comment by shawjak3** [comment]
I am running into the exact same issue. Placed an image in xxxhdpi and on an hdpi device its still huge.

**Comment by smoothdvd** [comment]
same issue

**Comment by koral--** [comment]
It should work in version 1.0.10-SNAPSHOT, sorry for the delay.
When `GifDrawable` is created from resource then density is taken into account and drawable size is scaled appropriately.
Note that only visible size is affected (values reported using Android graphic API - intrinsic, minimum width and height), but not the frame buffer.
