### ISSUE TITLE
Release from memory on listview

### ISSUE THREAD

**Issue by dangalg** [koral--/android-gif-drawable#182]
I am using this library in my listview. Every list item has a gifdrawable running an animated gif. It is working fantastic. But i am noticing that the memory goes up and up reaching almost 200 on my lg g3. And the biggest problem is that when I click an item which moves me to a new activity, the memory is not released. What am I doing wrong?

**Comment by koral--** [comment]
Java heap is freed when java object is garbage collected and native heap is freed after it when running finalizer. It is not deterministic when exactly garbage collector will run, VM decides about it. So maybe nothing is wrong. 
Object can be garbage collected only when it is not reachable by strong references. You can dump java heap and analyze it with tools like MAT to see if you have reachable references to unneeded objects.
You can use `GifDrawable#recycle()` to manually free memory. See also https://github.com/koral--/android-gif-drawable/issues/124.

**Comment by dangalg** [comment]
Ok thanks!

**Comment by dangalg** [comment]
Ok thanks!
