### ISSUE TITLE
5.1 Can't display properly

### ISSUE THREAD

**Issue by zzhopen** [koral--/android-gif-drawable#187]
Gratitude can find so good content
5.1 Can't display properly,I"not find  important error message

**Comment by koral--** [comment]
Please post your code.

**Comment by zzhopen** [comment]
//								This Way,load Native gifFile normal operation:
								
								GifDrawable gifFromPath = new GifDrawable(gif_path);
								gifView.setImageDrawable(gifFromPath);
								
//								But load Network Data Image not Show:
								
								asyncHttpClient.get(newImage,new AsyncHttpResponseHandler() {
									
											public void onSuccess(int arg0, Header[] arg1,byte[] arg2) {
												InputStream myInputStream = new ByteArrayInputStream(arg2); 
												BufferedInputStream bis = new BufferedInputStream(myInputStream);
												GifDrawable drawable = null;
												try {
													drawable = new GifDrawable(bis);
												} catch (IOException e) {
													e.printStackTrace();
												}
												vh.iv_new_gif.setImageDrawable(drawable);
											}
											public void onFailure(int arg0, Header[] arg1,byte[] arg2, Throwable arg3) {
												Toast.makeText(mContext,"加载网络图片出错", Toast.LENGTH_SHORT).show();
											}
									});

**Comment by zzhopen** [comment]
May be I have a problem of the way get ImageData,If there support load Netdata path,very well.

**Comment by koral--** [comment]
I assume that it is confirmed that `onSuccess()` is being called. If so:
- is there any `IOException` thrown by `GifDrawable` constructor?
- is `vh.iv_new_gif` `GifImageView` or `GifImageButton`?

**Comment by nuoyan2** [comment]
Hi,Thank you very much koral，My 5.0 problem solved，The reason is not compiled a 64 - bit so package，Before the interrupt you。

**Comment by koral--** [comment]
OK I assume that @nuoyan2 and @zzhopen ar both your accounts.
