### ISSUE TITLE
native codes compilation problem

### ISSUE THREAD

**Issue by Sophiexuer** [koral--/android-gif-drawable#189]
Hi,

I try to compile native codes in the jni directory. However, I got an error:

jni/gif.c: In function 'JNI_OnLoad':
jni/gif.c:387:23: error: 'CLOCK_MONOTONIC_RAW' undeclared (first use in this function)
jni/gif.c:387:23: note: each undeclared identifier is reported only once for each function it appears in
/cygdrive/d/android-ndk-r9-windows-x86_64/android-ndk-r9/build/core/build-binary.mk:345: recipe for target 'obj/local/x86/objs/gif/gif.o' failed
make: *** [obj/local/x86/objs/gif/gif.o] Error 1

And my Android.mk is:

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := gif
LOCAL_SRC_FILES := bitmap.c \
					control.c \
					decoding.c \
					drawing.c \
					exception.c \
					gif.c \
					memset.arm.S \
					memset32_neon.S \
					metadata.c \
					open_close.c \
					surface.c \
					time.c \
					giflib/dgif_lib.c \
					giflib/gifalloc.c

LOCAL_CFLAGS := $(L_CFLAGS)

LOCAL_C_INCLUDES := \
		    $(call include-path-for)

LOCAL_SHARED_LIBRARIES := libutils

LOCAL_LDLIBS := -ljnigraphics

include $(BUILD_SHARED_LIBRARY)

Application.mk is:

APP_ABI := x86 mips armeabi
APP_PLATFORM := android-8

Both Android.mk and Application.mk are in the jni directory.

Should I include some headers manually or modify any options in the mk files?

Thank you! : )

**Comment by koral--** [comment]
mk files workinng on ndk r10-e are located in dev branch: https://github.com/koral--/android-gif-drawable/tree/dev/src/main/jni
You can use options from it and update your ndk.
