### ISSUE TITLE
crash in android 5.0

### ISSUE THREAD

**Issue by hexin1979wei** [koral--/android-gif-drawable#190]
on android 5.0 platform ,gif can not load ,and go to crash

**Comment by koral--** [comment]
Check if it is not a duplicate of #170, if not please post your stacktrace.

**Comment by hexin1979wei** [comment]
has error when compile to make .so file,on android studio,log is:Error:Execution failed for task ':compileDebugNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android-ndk-r9\ndk-build.cmd'' finished with non-zero exit value 2
how to solve it???

**Comment by hexin1979wei** [comment]
can you give me jar file  and so file from 1.1.7 version?

**Comment by hexin1979wei** [comment]
I have resolve it
