### ISSUE TITLE
Unable to work with android-gif-drawable library in eclipse

### ISSUE THREAD

**Issue by yqpan1991** [koral--/android-gif-drawable#191]
Hello,author , I appricate your contribution for sharing this project
Here is my problem:
I did as your instruction : 
1. download aar file
2. move classes.jar and so to eclipse libs folder 
when I run my project,the crash log as follows: 
07-22 19:45:11.643: E/AndroidRuntime(3893): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test/com.test.demo.GifViewActivity}: android.view.InflateException: Binary XML file line #6: Error inflating class pl.droidsonroids.gif.GifImageView
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.ActivityThread.access$800(ActivityThread.java:142)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.os.Looper.loop(Looper.java:136)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.ActivityThread.main(ActivityThread.java:5241)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at java.lang.reflect.Method.invoke(Method.java:515)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at dalvik.system.NativeStart.main(Native Method)
07-22 19:45:11.643: E/AndroidRuntime(3893): Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class pl.droidsonroids.gif.GifImageView
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:307)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.Activity.setContentView(Activity.java:1943)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at com.test.demo.GifViewActivity.onCreate(GifViewActivity.java:13)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.Activity.performCreate(Activity.java:5266)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1091)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
07-22 19:45:11.643: E/AndroidRuntime(3893): 	... 11 more
07-22 19:45:11.643: E/AndroidRuntime(3893): Caused by: java.lang.ClassNotFoundException: Didn't find class "pl.droidsonroids.gif.GifImageView" on path: DexPathList[[zip file "/data/app/com.test-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.test-1, /vendor/lib, /system/lib]]
07-22 19:45:11.643: E/AndroidRuntime(3893): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

**Comment by koral--** [comment]
See #170

**Comment by koral--** [comment]
How to for eclipse: https://github.com/koral--/android-gif-drawable-eclipse-sample
