### ISSUE TITLE
Unable to play Gif

### ISSUE THREAD

**Issue by Kennyc1012** [koral--/android-gif-drawable#196]
This gif has not been able to play for me. http://i.imgur.com/36ao1fY.gif

The way it is played is its downloaded from the URL and a GifDrawable is created by calling new GifDrawable("path to downloaded file") and passing to the ImageView. When it loads, it starts to play and pauses after the first frame. If trying to replay it, it sometimes throw a segfault crash. 

It only fails when it is downloaded from the URL. I downloaded it and re-uploaded it and it played fine after that so I can't pin point it. 

Edit: Observed this on a OnePlusOne/Nexus 6 Running cm 12.1 and a Nexus 9 Running M Preview2

**Comment by koral--** [comment]
OK, I was able to reproduce that and I'll fix it ASAP.

**Comment by koral--** [comment]
Fixed, if you are interested in bug details see https://github.com/koral--/android-gif-drawable/issues/194#issuecomment-129097433
Case is the same as in #194 but GIF from this issue extends canvas by one pixel only.
