### ISSUE TITLE
How to make gif picture Rounded

### ISSUE THREAD

**Issue by cloudsoar** [koral--/android-gif-drawable#202]

**Comment by koral--** [comment]
That should be possible using `BitmapShader`. Namely: create a `BitmapShader` using frame buffer, set it in `Paint` and draw rounded rectangle with that Paint.
I'll try to prepare code doing that ASAP.

**Comment by koral--** [comment]
See commit linked above. `GifDrawable#setCornerRadius()` has been added. Pass radius=0 to remove rounding.
I think it will be good idea to add that method to the next version of the library, so I am leaving this issue open.

**Comment by sachindsilva16** [comment]
Is that possible through mark up?

**Comment by koral--** [comment]
Please create a new issue and elaborate on what "mark up" means.
