### ISSUE TITLE
Drawing cache from GifImageView

### ISSUE THREAD

**Issue by Nihilus13** [koral--/android-gif-drawable#203]
Using this http://stackoverflow.com/a/28963226 gifdecoder, for creating bitmap from the entire gifimageview(gif is transformed, rotated etc.), I've got some problem. Some of the frames have black/other color part of frames, just like here.
https://cloud.githubusercontent.com/assets/9919633/9706074/ea5d04ee-54d9-11e5-9a27-f8316d11962b.png
original gif is here http://i.imgur.com/aknjW6J.gif
In gifimageview when gif animates, everything is shown correctly. To create bitmap from gifimageview, I simly use  view method buildDrawingCache(). Is there an easy way to get bitmaps of entire gifimageview with frame by frame animations, without this decode problem(I want to omit gifdecoder and base my code only on gifimageview)?

**Comment by koral--** [comment]
To just get currently displayed frame as a bitmap you can use `GifDrawable#getCurrentFrame()`. 
To get particular frames as bitmaps you can use `GifDrawable#seekToFrameAndGet(int index)` in a loop.

**Comment by Nihilus13** [comment]
I have already seen this methods, but tested them in different way. Now is everything alright. I have one more question. How can I get gif delay between frames from GifDrawable? Is there aby method to obtain mNextFrameRenderTime variable?I suppose this is the value that, I'm looking for.

**Comment by koral--** [comment]
You can use `GifDrawable#getFrameDuration(int index)`.

**Comment by Nihilus13** [comment]
I am so blind... Thanks for help!
