### ISSUE TITLE
Set GifInfoHandle's visbility to public/add ability to get frames without creating drawable

### ISSUE THREAD

**Issue by Saren-Arterius** [koral--/android-gif-drawable#206]
Currently I am using koush/ion's GifDecoder to decode GIFs and animate the ImageSpan. However GIF corruption occurs in some GIFs, while gif-drawable don't. As a result, I am migrating from GifDecoder to gif-drawable.

I need access to GifInfoHandle, please set GifInfoHandle's visbility to public.

**Comment by koral--** [comment]
Sorry, but `GifInfoHandle` is intentionally package-private. What do you exactly want to to?

**Comment by Saren-Arterius** [comment]
I originally intended to implement this interface
```
public interface GifWrapping {
        GifFrame nextFrame();

        void restart();

        void recycle();

        int getTotalFrames();
    }
```
And later I came to this
```
static class GifDrawableWrapper implements GifWrapping {

        GifDrawable drawable;
        private int nof;
        private int currentIndex;

        public GifDrawableWrapper(byte[] data) {
            try {
                drawable = new GifDrawable(data);
                drawable.pause();
                nof = drawable.getNumberOfFrames();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        public GifFrame nextFrame() {
            if (drawable == null) {
                return null;
            }
            int duration = drawable.getFrameDuration(currentIndex);
            Bitmap bitmap = drawable.seekToFrameAndGet(currentIndex);
            if (currentIndex + 1 >= nof) {
                currentIndex = 0;
            } else {
                currentIndex++;
            }
            return new GifFrame(bitmap, duration);
        }

        public void restart() {
            if (drawable != null) {
                drawable.reset();
            }

        }

        public void recycle() {
            if (drawable != null) {
                drawable.recycle();
            }
        }

        @Override
        public int getTotalFrames() {
            return nof;
        }
    }
```

**Comment by jonasasx** [comment]
How can I decode file/stream to `android.graphics.Bitmap`, using this library?

**Comment by koral--** [comment]
@Saren-Arterius what is the problem? Which method from `GifInfoHandle` do you need exactly?
@jonasasx generally please fill new Github issue for new questions, but you can see in listing above that there is a method: `GifDrawable#seekToFrameAndGet()`.

**Comment by jonasasx** [comment]
@koral--, I have to make `GifInfoHandle` public in my code to decode gif image to bitmap without drawable. My question was about this issue.

**Comment by koral--** [comment]
OK, I understand now. Interesting use case. I'll consider it.

**Comment by Saren-Arterius** [comment]
It's just about animating ImageSpan in a TextView. It's messy, I have written a GifThread for each gif url, it will replace the drawable inside a drawable wrapper with a next frame over time, but it just works.

**Comment by Saren-Arterius** [comment]
Without using GifInfoHandle, I will have to pause the new GifDrawable immediately. Don't know whether this will cause extra overhead (A new gif animating has been already submited to an executor?).

**Comment by koral--** [comment]
If you just want animated GIF inside `ImageSpan` you can use `GifDrawable` with custom callback which invalidates `TextView`. Like that in sample project: [ImageSpanFragment](https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/ImageSpanFragment.java). But drawable needs to manually paused if you don't want it to start automatically.
By default if `GifDrawable` is paused before drawing first frame nothing should be submitted to executor.

**Comment by Saren-Arterius** [comment]
@koral-- I am currently having greater control that I can let my users to limit the GIF fps. Also, the code in my app is too fixed that it's very hard to change. Anyway, thanks for letting me know that.

**Comment by koral--** [comment]
Lightweight wrapper of `GifInfoHandle` - `GifDecoder` added in 8aded2db73141a122e20c6bafbf8ec61fa0882ef
