### ISSUE TITLE
Lint error for annotations in the constructor with android gradle 1.4.0-beta1

### ISSUE THREAD

**Issue by raylee4204** [koral--/android-gif-drawable#207]
Running proguard with android gradle 1.4.0-beta1 throws "Error: Expected resource of type raw [ResourceType] " on usage of drawable resource id for one of the GifDrawable contructors. I believe it's because of using 2 annotations for the id parameter, which is the following:
public GifDrawable(@NonNull Resources res, @DrawableRes @RawRes int id)

**Comment by koral--** [comment]
It looks like bug in lint. Drawable and raw resources ids are supported but not eg. string or dimen. So 2 annotations needs to be specified but not eg. AnyRes.
I haven't used 1.40-beta yet but in 1.3.1 it is working as described above.
This issue should be reported to android bugtracker: https://code.google.com/p/android/

**Comment by raylee4204** [comment]
Alright thanks.

It's been reported
https://code.google.com/p/android/issues/detail?id=187181&thanks=187181&ts=1442932491
