### ISSUE TITLE
Restart animation

### ISSUE THREAD

**Issue by dochathuc** [koral--/android-gif-drawable#209]
Hi,
I have a listview of gifs. I also setLoop =3 for each item. At the first time, I stop it, then override setOnClickItem on listview to restart a gif. However, it just restart for the first click (after that never restart).

The solution is that I have to renew GifDrawable. How can I restart without renewing this.

Please help me.

**Comment by dochathuc** [comment]
https://github.com/koral--/android-gif-drawable/issues/208

**Comment by koral--** [comment]
Right, looks like it is the same issue.

**Comment by koral--** [comment]
Now it should work as expected.

**Comment by dochathuc** [comment]
thanks
