### ISSUE TITLE
stop() is not working

### ISSUE THREAD

**Issue by elsennov** [koral--/android-gif-drawable#210]
I called .stop() but the animated gif is still running? I am using:
`compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.10'`

Here is my code:
```Gradle
        try {
            mDiscoveringGif = new GifDrawable(getResources(), R.drawable.logo_animated);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        mDiscoveringGif.start();

        mDiscoveringGif.stop();
```

Could you please help why? Thanks

**Comment by koral--** [comment]
Yesterday's commit cf2ad6c3fdf36a834feda052c4efd679b49ecd1e should fix also that bug.

**Comment by elsennov** [comment]
Has it been merged to master?

**Comment by koral--** [comment]
Not yet, I'll merge it ASAP.

**Comment by elsennov** [comment]
Thank you @koral-- , waiting for next release.

**Comment by koral--** [comment]
Done.

**Comment by elsennov** [comment]
It is still not working :(
Did i miss something?

**Comment by koral--** [comment]
Are you using library version 1.1.10?

**Comment by elsennov** [comment]
Yes.

**Comment by koral--** [comment]
OK, I'll investigate it.

**Comment by koral--** [comment]
@elsennov how do use `mDiscoveringGif` later in your code?

**Comment by elsennov** [comment]
It is the same as i mentioned above.

**Comment by koral--** [comment]
I meant what code is next lines.
You must assign that newly created drawable to some view, span or something else eg.
```
someImageView.setImageDrawable(mDiscoveringGif);
```
And I'm asking what it is.

**Comment by elsennov** [comment]
Oh, here is the next code:
```Gradle
mDiscoveringImage.setImageDrawable(mDiscoveringGif);
```
Where mDiscoveringImage is GifImageView

**Comment by elsennov** [comment]
And here is the manifest
```Gradle
<pl.droidsonroids.gif.GifImageView
            android:id="@+id/discovering_image"
            android:layout_width="64dp"
            android:layout_height="64dp"
            android:layout_centerInParent="true"
            android:src="@drawable/logo_animated" />
```
Where logo_animated is .gif

**Comment by koral--** [comment]
In such case you don't need to create second `GifDrawable` instance. Just get existing, and call `stop()` on it.
Something like:
```java
GifDrawable gifDrawable = (GifDrawable) mDiscoveringImage.getDrawable();
gifDrawable.stop();
```
Sample project contains similar code:
https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/AnimationControlFragment.java#L27
https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/AnimationControlFragment.java#L43

**Comment by elsennov** [comment]
Yes, i have followed it, but it is still not working :(
It looks like the animation is reset, instead of stopped.
Did i miss something? The NDK itself, should i do something with it?

**Comment by koral--** [comment]
Could you make example project demonstrating your issue?

**Comment by elsennov** [comment]
Ok wait~

**Comment by elsennov** [comment]
Hi @koral-- 
I found why it is not working, so there is these line in my code:
```Gradle
public void stop() {
        mDiscoveringImage.setImageResource(R.drawable.logo_animated);
        mDiscoveringGif.start();
        mDiscoveringGif.stop();
        mRippleBackground.stopRippleAnimation();
 }
```
The stop is not working because `mDiscoveringImage` is reassigned using the .gif. So, i need to reassigned the `mDiscoveringGif` as well.
```Gradle
public void stop() {
        mDiscoveringImage.setImageResource(R.drawable.logo_animated);
        mDiscoveringGif = (GifDrawable) mDiscoveringImage.getDrawable();
        mDiscoveringGif.start();
        mDiscoveringGif.stop();
        mRippleBackground.stopRippleAnimation();
}
```
Phew, finally. Thanks for assisting me @koral-- . This library is amazing :+1:

**Comment by emretekin** [comment]
> I called .stop() but the animated gif is still running? I am using:
> `compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.10'`
> 
> Here is my code:
> 
> ```groovy-gradle
>         try {
>             mDiscoveringGif = new GifDrawable(getResources(), R.drawable.logo_animated);
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
> 
>         mDiscoveringGif.start();
> 
>         mDiscoveringGif.stop();
> ```
> 
> Could you please help why? Thanks

Actually this is work for me. Thanks :)
