### ISSUE TITLE
Unable to getDrawingCache() from GifTextureView

### ISSUE THREAD

**Issue by Bryanli910** [koral--/android-gif-drawable#211]
Hi, when I call the getDrawingCache() from a GifTextureView, the result is a black screen. Can you please advise?

Bitmap bitmap = Bitmap.createBitmap(getWindow().getDecorView().findViewById(R.id.myGifTexture).getDrawingCache());

**Comment by koral--** [comment]
`TextureView` (and its subclasses as well) uses different rendering mechanism than other `View`s and drawing cache does not apply to them.
Similar effect can be achieved using [TextureView#getBitmap()](http://developer.android.com/reference/android/view/TextureView.html#getBitmap()).
