### ISSUE TITLE
Waiting for task finish on main thread

### ISSUE THREAD

**Issue by jonasasx** [koral--/android-gif-drawable#214]
When I call GifDrawable.stop(), these lines hangs the main thread:

	try {
		mSchedule.get();
	} catch (InterruptedException | ExecutionException ignored) {
		//no-op
	}

I have many drawables on the screen. And when I stop all of them, main thread hangs.
May be, *ScheduledFuture.cancel(true)* will be better in this case?

**Comment by koral--** [comment]
I has been already changed. Version 1.1.10 uses `ScheduledFuture#cancel()` there.
