### ISSUE TITLE
Where to find .so file

### ISSUE THREAD

**Issue by kymjs** [koral--/android-gif-drawable#217]
Where to find .so file ?
I use AndroidStudio by gradle reference library.    
My new demo project run success, but include my work project throw:   
```java.lang.UnsatisfiedLinkError: Couldn't load pl_droidsonroids_gif from loader xxxx  findLibrary returned null```    
like to [Issue 201](https://github.com/koral--/android-gif-drawable/issues/201) and [Issue 51](https://github.com/koral--/android-gif-drawable/issues/51)

**Comment by koral--** [comment]
So file should be in one of the directories of `nativeLibraryDirectories` (like in #201). But on some devices (ROMs) it does not contain required directory. Is your device one of listed in linked issues?

Could you try inserting the following one-liner before using `GifDrawable` in your code?:
`System.load(context.getApplicationInfo().nativeLibraryDir+"/libpl_droidsonroids_gif.so");`
where `context` can be any instance of `android.content.Context` eg. Application, Activity, etc.

**Comment by kymjs** [comment]
Thank you for your prompt. I unzipped apk, can not find lib folder.    
Because in my app module build.gradle, to write
```gradle
task copyNativeLibs(type: Copy) {
    from fileTree(dir: 'libs', include: 'armeabi/*.so') into 'build/lib'
}

clean.dependsOn 'cleanCopyNativeLibs'

tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask ->
    pkgTask.jniFolders = [new File(buildDir, 'lib')]
}
```  
When I delete them to fix the problem.
