### ISSUE TITLE
Hi, I want add Text to gif,and can you tell me how to do it?

### ISSUE THREAD

**Issue by tianqiujie** [koral--/android-gif-drawable#219]
Hi, I want add Text to gif,and can you tell me how to do it? thank you

**Comment by tianqiujie** [comment]
And I just want the gifImageView to display the edited Bitmaps. How to ?

**Comment by koral--** [comment]
This library does not support GIF editing, so you cannot modify GIF files, but maybe 2 following options will be helpful:
* you can extract bitmap of each frame eg. using `GifDrawable#seekToFrameAndGet()`, modify that bitmaps and assemble your own animation
* you can create custom `Drawable.Callback` which apart from normal action (invalidating `View` with `GifDrawable`) will appropriately change text displayed eg. in `TextView` which overlaps with `View` displaying animation
