### ISSUE TITLE
 Failed to resolve: pl.droidsonroids.gif:android-gif-drawable:1.1.+

### ISSUE THREAD

**Issue by ayyb1988** [koral--/android-gif-drawable#221]
Error:(157, 13) Failed to resolve: pl.droidsonroids.gif:android-gif-drawable:1.1.+
<a href="openFile:/home/xxx/work/xxx/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by koral--** [comment]
It looks like an error in your `build.gradle` files and/or Internet connection. You don't have correct repository configured in your repositories block (must be `mavenCentral()` and/or `jcenter()`) or request to repository has failed.
If you have closure like this in `build.gradle` of your project (NOT inside `buildscript`):
```
repositories {
    jcenter()
}
```
and your Internet connection is fine but dependency still cannot be resolved you can use gradle `--stacktrace` option to reveal exact reason, eg. by launching ` ./gradlew tasks --stacktrace`.

**Comment by shirishhrw** [comment]
for ./gradlew tasks --stacktrace. command gives me 'The system cannot find the path specified.' eror

**Comment by koral--** [comment]
@shirishhrw please post complete output.
