### ISSUE TITLE
how to use this aar into apk? My project based maven and create apk missing .so

### ISSUE THREAD

**Issue by sherryein** [koral--/android-gif-drawable#223]

**Comment by koral--** [comment]
It looks like your `pom.xml` is incorrect. Look at [README](https://github.com/koral--/android-gif-drawable#maven-dependency).
I've modified one of the sample projects of `android-maven-plugin` to include `android-gif-drawable` dependency:
https://github.com/koral--/android-maven-plugin/blob/android-gif-drawable/src/test/projects/helloflashlight/pom.xml#L22
In that case .so files are present in `apk`.
