### ISSUE TITLE
How to exclude arm64-v8a, mips, mips64, x86, x86_64?

### ISSUE THREAD

**Issue by shewenbiao** [koral--/android-gif-drawable#225]
Hi, @koral-- 

Thanks for providing an awesome library!

I used android-gif-drawable library in my project through gradle dependency. I build my project, then I reversed my apk file and found some folders in lib folder, these folder are arm64-v8a, mips, mips64, x86, x86_64, armeabi, armeabi-v7a, but my project only need armeabi and armeabi-v7a. So how to exclude these folders except armeabi and armeabi-v7a when building project ?

**Comment by koral--** [comment]
Assuming that you are using stable (non-experimental) android gradle plugin:
* add `android.useDeprecatedNdk=true` to your `gradle.properties` file
* add ```        ndk {
            abiFilters 'armeabi-v7a', 'armeabi'
        }``` to `android.defaultConfig` closure (it maybe located also inside flavor or buildType configuration) of `build.gradle`

If you are using experimental gradle plugin, syntax is a little bit different. Look here: http://tools.android.com/tech-docs/new-build-system/gradle-experimental#TOC-Ndk-Integration

**Comment by shewenbiao** [comment]
@koral-- 
 
Thanks for your help!
