### ISSUE TITLE
Multi emotion gif not Animation in SpannableStringBuilder

### ISSUE THREAD

**Issue by axeon** [koral--/android-gif-drawable#228]
I want to display multi emotion gif in chat activity，so I use SpannableStringBuilder, and wrote code like sample to auto start ainimation and looped  ,but it run once or twice..., then stoped。

the code like this:

    private SpannableStringBuilder handleEmotion(final TextView gifTextView, String content) {
        SpannableStringBuilder sb = new SpannableStringBuilder(content);
        String regex = "\\[(.+?)\\]";
        Pattern p = Pattern.compile(regex);
        Matcher m = p.matcher(content);
        Drawable.Callback gifCallback = null;

        if (m.groupCount() > 0) {
            gifCallback = new Drawable.Callback() {

                @Override
                public void invalidateDrawable(Drawable drawable) {
                    gifTextView.invalidate();
                }

                @Override
                public void scheduleDrawable(Drawable who, Runnable what, long when) {
                    gifTextView.postDelayed(what, when);
                }

                @Override
                public void unscheduleDrawable(Drawable who, Runnable what) {
                    gifTextView.removeCallbacks(what);
                }
            };
        }
        while (m.find()) {
            String tempText = m.group(1);
            String emotionFile = EmotionUtils.getFileByText(tempText);
            try {
                if (emotionFile != null) {
                    String gif = "emotion/" + emotionFile + ".gif";
                    GifDrawable gifDrawable = new GifDrawable(mContext.getAssets(), gif);
                    gifDrawable.setLoopCount(Integer.MAX_VALUE);
                    gifDrawable.setBounds(0, 0, gifDrawable.getIntrinsicWidth(), gifDrawable.getIntrinsicHeight());
                    sb.setSpan(new ImageSpan(gifDrawable), m.start(), m.end(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
                    gifDrawable.setCallback(gifCallback);
                }
            } catch (Exception e) {

            }
        }
        return sb;
    }

**Comment by koral--** [comment]
`GifDrawable#setLoopCount()` accepts values in range <0, 65535>. Where 0 means infinite number of loops. Info is included in javadoc: https://github.com/koral--/android-gif-drawable/blob/master/src/main/java/pl/droidsonroids/gif/GifDrawable.java#L393

**Comment by funorpain** [comment]
Callback is weak referenced by Drawable and will be garbage collected soon.

```java
public abstract class Drawable {
   public final void setCallback(Callback cb) {
        mCallback = new WeakReference<Callback>(cb);
    }
}
```

**Comment by axeon** [comment]
@funorpain yes, maybe the problem caused by weak referenced callback。
but what shoud i do?
how to auto play multi gif?
@koral--

**Comment by koral--** [comment]
@funorpain is right, callback can be GC'ed. Here is the code which fixes 2 found bugs: https://gist.github.com/koral--/815ff6303e04b074386d
