### ISSUE TITLE
Library can not be loaded

### ISSUE THREAD

**Issue by afaucogney** [koral--/android-gif-drawable#229]
I'm not sure this is different or identique to other issues:

I'm in a MultiDex context (FYI)

1/ I'm just try using the lib in a first basic usage:
- added with gradle

I coded the following:

`gifFromAssets = new GifDrawable(getActivity().getAssets(), "glass_shaking.gif");`

I got this error:

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/fr.xxxxx.u.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/fr.xxxxx.u.debug-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libpl_droidsonroids_gif.so"`

2/ Then I added the following code before:

`System.load(getActivity().getApplicationInfo().nativeLibraryDir+"/libpl_droidsonroids_gif.so");``

This triggers the following error: 
`dlopen("/data/app/fr.xxxxx.u.debug-2/lib/arm/libpl_droidsonroids_gif.so", RTLD_LAZY) failed: dlopen failed: library "/data/app/fr.xxxxx.u.debug-2/lib/arm/libpl_droidsonroids_gif.so" not found`

`java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/fr.xxxx.u.debug-2/lib/arm/libpl_droidsonroids_gif.so" not found`

**Comment by koral--** [comment]
That should be already fixed in version 1.0.11-SNAPSHOT, but adding one line to code is needed. See here for more details: https://github.com/koral--/android-gif-drawable/issues/51#issuecomment-156285451

**Comment by afaucogney** [comment]
you mean 1.1.11-SNAPSHOT !

**Comment by koral--** [comment]
Right, I'll correct previous post. Actually current version is 1.1.11 (no SNAPSHOT).

**Comment by afaucogney** [comment]
Just for info, if you gradle the 1.1.++ (as writtent in Readme), you'll get the r2-SNAPSHOT

**Comment by koral--** [comment]
Just below that section with mentioned compile dependency, there is another with repositories. Snapshot versions are available only in snapshot repository but not on central one which is the only listed in readme.
However to be clear I'll change + to exact version number and info about snapshot repo to readme.
