### ISSUE TITLE
direct stream of gif

### ISSUE THREAD

**Issue by tzaccai** [koral--/android-gif-drawable#230]
is there a way to stream an animated gif directly from the internet, without downloading it?

p.s.
I'm using `GifTextureView` for rendering via **openGL** `Texture`.

**Comment by koral--** [comment]
Yes it possible, you have to buffer all GIF eg. in byte array or wrap your source `InputStream` with `BufferedInputStream`. I've added example with OkHttp and byte array in sample project: https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.java#L52

**Comment by klkgogo** [comment]
Is it ok to play the gif from internet while is buffering.
In the HttpFragment  example, you have to buffer all gif before you can play.
