### ISSUE TITLE
GIF doesn't play when textview is been set selectable

### ISSUE THREAD

**Issue by dss886** [koral--/android-gif-drawable#234]
I am using this project to show emotion gifs in Textview, everything works right at first. But when I set textView.setTextIsSelectable(true)(to select text by long press), gifs don't play unless touch the textview. Here is my code:

set GifDrawable in a span:

```
GifDrawable gifFromAssets = new GifDrawable(context.getAssets(), "ems/" + matcher.group(1) + ".gif");
int bound = DisplayUtil.dip2px(context, 32);
gifFromAssets.setBounds(0, 0, bound, bound);
gifFromAssets.setCallback(new GifCallback(textView));
ss.setSpan(new ImageSpan(gifFromAssets, ImageSpan.ALIGN_BASELINE), 
        matcher.start(),matcher.end(),Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
```

GifCallback:
```
private static class GifCallback implements Drawable.Callback {

        private final TextView tv;

        public GifCallback(TextView tv) {
            this.tv = tv;
        }

        @Override
        public void invalidateDrawable(android.graphics.drawable.Drawable who) {
            tv.invalidate();
        }

        @Override
        public void scheduleDrawable(android.graphics.drawable.Drawable who, Runnable what, long when) {
            tv.postDelayed(what, when);
        }

        @Override
        public void unscheduleDrawable(android.graphics.drawable.Drawable who, Runnable what) {
            tv.removeCallbacks(what);
        }
    }
```

**Comment by koral--** [comment]
Calling `TextView#invalidate()` will not cause redrawing if `TextView` has editor associated (which is true eg. when `#setTextIsSelectable(true)` has been called).
One of the solution is to perform manually particular actions related to selection, eg. if you just want all text to be selected after long press, you can use something like this:
```java
		textView.setFocusableInTouchMode(true);
		textView.setClickable(true);
		textView.setMovementMethod(ArrowKeyMovementMethod.getInstance());
		textView.setText(ss, TextView.BufferType.SPANNABLE);
		textView.setOnLongClickListener(new View.OnLongClickListener() {
			@Override
			public boolean onLongClick(View v) {
				Selection.selectAll((Spannable) textView.getText());
				return true;
			}
		});
```

**Comment by koral--** [comment]
@dss886 Workaround is to use software layer on `TextView`. Eg. `textView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);`

**Comment by BuYishi** [comment]
A Drawable **doesn't hold a strong reference** to the Drawable.Callback.
So **the anonymous GifCallback object** in 'gifFromAssets.setCallback(**new GifCallback(textView)**);' may be garbage collected quickly.
You have to **make a strong reference** to the Drawable.Callback.
