### ISSUE TITLE
Could not read input channel file descriptors from parcel

### ISSUE THREAD

**Issue by liuf518** [koral--/android-gif-drawable#245]
If a activity have gif, when a dialog show, there may be the problem
This is a small probability event

**Comment by liuf518** [comment]
if delete this library,this problem will disappear.

**Comment by liuf518** [comment]
java.lang.RuntimeException
Could not read input channel file descriptors from parcel.
android.view.InputChannel.nativeReadFromParcel(Native Method)
android.view.InputChannel.readFromParcel(InputChannel.java:148)
android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:736)
android.view.ViewRootImpl.setView(ViewRootImpl.java:503)
android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
android.app.Dialog.show(Dialog.java:286)
com.ppcall.ppcall.tencent.im.HiBarActivity.showExitDialog(HiBarActivity.java:1809)
com.ppcall.ppcall.tencent.im.HiBarActivity.onKeyDown(HiBarActivity.java:1789)
android.view.KeyEvent.dispatch(KeyEvent.java:2640)
android.app.Activity.dispatchKeyEvent(Activity.java:2458)
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2002)
android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3850)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3824)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3397)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3447)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3416)
android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3523)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3424)
android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3580)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3397)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3447)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3416)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3424)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3397)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3447)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3416)
android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3556)
android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3716)
android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2037)
android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1731)
android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1722)
android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2014)
android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
android.os.MessageQueue.nativePollOnce(Native Method)
android.os.MessageQueue.next(MessageQueue.java:138)
android.os.Looper.loop(Looper.java:123)
android.app.ActivityThread.main(ActivityThread.java:5241)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
dalvik.system.NativeStart.main(Native Method)

**Comment by liuf518** [comment]
java.lang.RuntimeException
Could not read input channel file descriptors from parcel.
android.view.InputChannel.nativeReadFromParcel(Native Method)
android.view.InputChannel.readFromParcel(InputChannel.java:148)
android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
com.android.internal.view.InputBindResult.<init>(InputBindResult.java:62)
com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:102)
com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:99)
com.android.internal.view.IInputMethodManager$Stub$Proxy.windowGainedFocus(IInputMethodManager.java:713)
android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1172)
android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1397)
android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3146)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:136)
android.app.ActivityThread.main(ActivityThread.java:5241)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
dalvik.system.NativeStart.main(Native Method)

**Comment by koral--** [comment]
Which android version are you using and how exactly GIF is embedded , in `GifImageView`?

**Comment by koral--** [comment]
I am unable to reproduce that. 
It looks like that exception may occur due to completely unrelated reason: http://stackoverflow.com/questions/25132509/java-lang-runtimeexception-could-not-read-input-channel-file-descriptors-from-p

**Comment by sc1992** [comment]
I have the same problem...

**Comment by sc1992** [comment]
@liuf518 Do you solve this problem?
