### ISSUE TITLE
OutOfMemory with 1.1.11 not with 1.1.10

### ISSUE THREAD

**Issue by monossido** [koral--/android-gif-drawable#248]
On a Nexus 7 with Android 5.1.1 (cyanogenmod 13)

```
Process: xxx PID xxxx java.lang.OutOfMemoryError: Failed to allocate native memory android
```

Only with android-gif-drawable version 1.1.11 not with 1.1.10

**Comment by koral--** [comment]
Could you post full stacktrace?

**Comment by monossido** [comment]
oh...it doesn't happen anymore, sorry

thank you anyway
