### ISSUE TITLE
All devices crashing 

### ISSUE THREAD

**Issue by pecabum** [koral--/android-gif-drawable#252]
01-25 11:03:42.122 15893-15893/? E/Zygote: MountEmulatedStorage()
01-25 11:03:42.122 15893-15893/? E/Zygote: v2
01-25 11:03:42.132 15893-15893/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
01-25 11:03:42.322 15893-15932/ E/GMPM: getGoogleAppId failed with status: 10
01-25 11:03:42.332 15893-15932/ E/GMPM: Uploading is not possible. App measurement disabled

**Comment by koral--** [comment]
It looks like a duplicate of #250.
