### ISSUE TITLE
failed: dlopen failed: "/system/app/xxx/lib/arm64/libpl_droidsonroids_gif.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by kaka2009** [koral--/android-gif-drawable#255]
hi
   android-gif-drawable-1.1.10  on android 6.2 show error as follow：（how to solve？ thank you）

Rejecting re-init on previously-failed class java.lang.Class<pl.droidsonroids.gif.GifInfoHandle>
02-22 10:47:23.905 E/System  ( 6340): Uncaught exception thrown by finalizer
02-22 10:47:23.905 E/System  ( 6340): java.lang.NoClassDefFoundError: pl.droidsonroids.gif.GifInfoHandle
02-22 10:47:23.905 E/System  ( 6340): 	at pl.droidsonroids.gif.GifInfoHandle.finalize(Unknown Source)
02-22 10:47:23.905 E/System  ( 6340): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
02-22 10:47:23.905 E/System  ( 6340): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
02-22 10:47:23.905 E/System  ( 6340): 	at java.lang.Thread.run(Thread.java:818)

**Comment by koral--** [comment]
Inside AAR available in maven central repository 64-bit libraries are located properly in `jni/arm64-v8a`.
It looks like a packaging problem on your side. Are you compiling library from source or using gradle dependency fetched from maven repository?

**Comment by kaka2009** [comment]
ok，thank you koral。it has been resolved！

**Comment by RishabhSRS** [comment]
hello , @koral-- I am facing same issue can you please suggest what should I do

**Comment by koral--** [comment]
Please create a new issue with the reproducer project.
