### ISSUE TITLE
How to load gif from website?

### ISSUE THREAD

**Issue by dasmikko** [koral--/android-gif-drawable#256]
I have been playing a bit with the library.

But i'm struggling with showing a gif from a external source, like a website.

What is the solution to this?

**Comment by koral--** [comment]
By now this library does not contain any external source-specific features.
There are 2 groups of solutions:
* save GIF locally either to file, byte array, `ByteBuffer` etc. 
* assuming that you have `InputStream` to read GIF data from you can wrap it with `BufferedInputStream` or any other which supports marking.

I am consolidating this issue into #113.
