### ISSUE TITLE
"drawable".equals(resourceTypeName) || "raw".equals(resourceTypeName)

### ISSUE THREAD

**Issue by CodingZh** [koral--/android-gif-drawable#263]
i have used mipmap for the resource file , would you like contain this situation. i have changed the by my shelf ...

**Comment by koral--** [comment]
Mipmap support has been added several months ago: https://github.com/koral--/android-gif-drawable/commit/f8734c87ca781dcc5568d6db3f20f3c803590b2a
please use the latest version (1.1.15)
