### ISSUE TITLE
java.lang.NoClassDefFoundError: pl.droidsonroids.gif.R$styleable

### ISSUE THREAD

**Issue by phanvanduc** [koral--/android-gif-drawable#265]
hi guy
when i run app on device galasy s3, version 4.1.2, but on htc 826 android 5.1 havent error
Thanks

**Comment by koral--** [comment]
Are you using multidex? If so, is it the same issue as #224? If not please attach complete stacktrace.

**Comment by koral--** [comment]
Closed due to inactivity, may be reopened if info is provided.
