### ISSUE TITLE
Stop gif from playing when the gif is loaded at the first time

### ISSUE THREAD

**Issue by MeiYi2** [koral--/android-gif-drawable#266]
Good day.    

I tried to stop the gif from loading when it is loaded at the first time. I do not want the gif to animate until the user clicks on the gif. But the gif does continue to animate eventhough I have put gifFromPath.stop();. Below is my code.

            final File file = getMyFile();

            viewHolder.gifImageView.setImageURI(Uri.fromFile(new File(file.getPath())));

            GifDrawable gifFromPath = (GifDrawable) viewHolder.gifImageView.getDrawable();

            gifFromPath.stop();

            viewHolder.gifImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    if (gifFromPath.isPlaying()) {
                        gifFromPath.stop();
                    } else {
                        gifFromPath.start();
                    }

                }
            });

Please advice.

Thank you.

**Comment by koral--** [comment]
Are you using the latest version of the library (1.1.15)?

**Comment by koral--** [comment]
Closed due to inactivity, may be reopened if info is provided.
