### ISSUE TITLE
Play and stop numerous gif in list view adapter

### ISSUE THREAD

**Issue by meeheng** [koral--/android-gif-drawable#268]
I wish to implement that when the user clicks on the gif it will start animating and when the user presses it again the gif will stop playing.

I've loaded numerous gif to my ListView adapter. But when the user clicks on the item in my listview adapter, only one gif can be played and stopped while the other gif cannot be controlled. Only one gif can be control in the list view. Below is my code snippet.

    private void loadGifImage(final ViewHolder viewHolder) {
            File myGifFile = getGifFile();
            GifDrawable gifFromPath = new GifDrawable( myGifFile.getPath() );
            viewHolder.gifImageView.setImageDrawable(gifFromPath);

            viewHolder.gifImageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    if (gifFromPath.isPlaying) {
                         gifFromPath.stop();
                   } else{
                         gifFromPath.start();
            });
    }

Thank you.

**Comment by koral--** [comment]
Mentioned code should work. I've just added something similar to sample project: https://github.com/koral--/android-gif-drawable-sample/commit/fd940658596ddc68a738733b2e98b7908b4b5030
It uses `RecyclerView` but there should be no difference from `ListView`. There should be nothing in library which prevents animation controls.

Looks like reason is located somewhere in your code. Could you post more code? eg. how are you calling `loadGifImage()` from adapter's `getView()`.

**Comment by koral--** [comment]
Closed due to inactivity, may be reopened if info is provided.
