### ISSUE TITLE
Is glTexImage2D still just a placeholder or an usable method?

### ISSUE THREAD

**Issue by frmz** [koral--/android-gif-drawable#269]
Checking the source i saw the glTexImage2D method but it does not have any parameter to specify the buffer or anything else, is that just a stub? Really looking forward to that functionality, that's something definitely missing on Android, great job!

**Comment by koral--** [comment]
It is usable, however only start, stop and draw features available now. Subsampling, seeking, speed changing etc. like in `GifDrawable` is not yet done.

Buffer in terms of [`data` in glTexImage2D](https://www.khronos.org/opengles/sdk/docs/man3/html/glTexImage2D.xhtml) is managed internally.
You need to manage OpenGL texture yourself (generate, set parameters, activate, bind etc.).

Sample usage may look like this:
fields declarations:
```java
int[] mTextures = new int[1];
GifTexImage2D mGifTexImage2D
```
in thread with OpenGL context eg. in `onSurfaceCreated()`
```java
glGenTextures(1, mTextures, 0);
glBindTexture(GL_TEXTURE_2D, mTextures[0]);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
//set other texture parameters
```
in any thread:
```
mGifTexImage2D = new GifTexImage2D(new InputSource.ResourcesSource(mResources, R.raw.animation));
mGifTexImage2D.startDecoderThread();
```
in `onDrawFrame()`:
```java
mGifTexImage2D.glTexImage2D();
//glActiveTexture(), glBindTexture(GL_TEXTURE_2D, mTextures[0]) etc.
//use texture in shader, glDraw... etc.
```

I'll add complete example to sample project, so I'm leaving this issue open until it is ready.

**Comment by frmz** [comment]
Wow, this is already very very good, thanks, will test it asap, pause / stop i assume can be easily managed by stopping the decoding thread. I assume you are loading more than one frame on the mapped texture so given a max texture of 2048x2048 i shouldn't load anything bigger than 512x512 yo leave space for at least 8 frames, is that more or less correct?

**Comment by frmz** [comment]
PS is this working on gles20 too?

**Comment by aixiaoyi123** [comment]
In accordance with the above method, opengles2.0 will become black block

**Comment by frmz** [comment]
@aixiaoyi123 ???

**Comment by aixiaoyi123** [comment]
@frmz You successful?

**Comment by aixiaoyi123** [comment]
![device-2016-04-14-100252](https://cloud.githubusercontent.com/assets/7221622/14515079/fe045284-0228-11e6-96ae-c72b74d7f125.png)
@koral--

**Comment by koral--** [comment]
@aixiaoyi123 I've just added sample code: https://github.com/koral--/android-gif-drawable-sample/blob/57926214022abf1ecaefd44ee164b50ed8a5de53/sample/src/main/java/pl/droidsonroids/gif/sample/GifTexImage2DFragment.java

**Comment by aixiaoyi123** [comment]
@koral-- Thank you. You've been a great help already.But under the camera or the wrong black block, only to close the camera to show.
