### ISSUE TITLE
Not working when rendering in canvas.

### ISSUE THREAD

**Issue by manoj99** [koral--/android-gif-drawable#270]
when try to rendering  gif in canvas. gif not moving rather it shows only one image.

**Comment by koral--** [comment]
Could you post code snippet?

**Comment by manoj99** [comment]
public void draw(Canvas canvas) {
			canvas.save();
			float dx = (maxX + minX) / 2;
			float dy = (maxY + minY) / 2;
			drawable.setBounds((int) minX, (int) minY, (int) maxX, (int) maxY);

			 
			canvas.translate(dx, dy);
			canvas.rotate(angle * 180.0f / (float) Math.PI);

			canvas.translate(-dx, -dy);
			drawable.draw(canvas);//here drawable as GifDrawable object.

			canvas.restore();

		}

**Comment by koral--** [comment]
I guess that is custom View. In such case you need to set `Callback` on the drawable. That may be custom callback like in span sample: https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/ImageSpanFragment.java
or you can use `MultiCallback` like this:
```java
final MultiCallback callback = new MultiCallback(true);
callback.addView(view); //view = instance of your custom View
drawable.setCallback(callback);
```
