### ISSUE TITLE
[Optimization] Allow usage of glTexSubImage2D in GifTexImage2D 

### ISSUE THREAD

**Issue by frmz** [koral--/android-gif-drawable#272]
When redrawing a frame on the very same texture it is much more efficient to use glTexSubImage2D instead of glTexImage2D, can you provide this method as well? Caller will have off course to know in advance if texture has been already initialized once.

**Comment by koral--** [comment]
OK, I can add method like `GifTexImage2D#glTexSubImage2D(int xoffset, int yoffset)`. I see that `target` and `level` parameters can also be exposed giving more flexibility to callers.

**Comment by koral--** [comment]
Done
