### ISSUE TITLE
Add subsampling and speed to GifTexImage2D

### ISSUE THREAD

**Issue by frmz** [koral--/android-gif-drawable#273]
Speed shouldn't bee too complex maybe you can just record last update timestamp on the thread and slow it down/up. Subsampling might be more complex.

**Comment by koral--** [comment]
In general all features already available in `GifDrawable` should be easily transplantable. Subsampling and speed control is already there.

**Comment by frmz** [comment]
I think there should also be a way to pause / resume the decoder thread or a way to start the thread at a specific frame (with also a way to get the current frame being shown maybe as a return value of glTexImage2D call), because otherwise its not possible to pause the rendering (unless "speed" is implemented and maybe one sets speed to 0f)

**Comment by koral--** [comment]
Setting speed factor to 0 is disallowed in `GifDrawable` and other gif wrappers, but pause/resume is available there.
Another feature available now is seeking to given frame: https://github.com/koral--/android-gif-drawable/blob/dev/src/main/java/pl/droidsonroids/gif/GifTexImage2D.java#L55

**Comment by frmz** [comment]
Wow seek is a great addition, only issue i see is that it requires to be run in the GL thread, it would be much more useful to have it just fill the framebuffer with a separate call to render the FB in the texture via glTexImage2D / glTexSubImage2D. This would allow the user to implement its own speed control and decoding threads without losing native code performance (by doing so you could even move the thread out of the native code into the GifTexImage2D.java file since i don't think there would be any real performance difference)

**Comment by koral--** [comment]
OK, LGTM. `renderFrame` can be refactored to `seekToFrame` which can only seek input source and refresh internal framebuffer.

**Comment by frmz** [comment]
Perfect and then a glTexImage2D  / glTexSubImage2D will draw the FB

**Comment by koral--** [comment]
`seekToFrame` is done in the latest snapshot.

**Comment by frmz** [comment]
great!!! only sumsampling missing!

**Comment by frmz** [comment]
Sorry closed by mistake

**Comment by koral--** [comment]
Subsampling added in 551a841cde74e86e6f0688480d0a422a42f23de5 along with option to specify opacity (if set to opaque then alfa byte is ignored when rendering).

**Comment by frmz** [comment]
It would be nice to be able to detect if alpha is in use, since GIF has very specific palette definitions blocks it might be done quickly by scanning those only. 

Anyway, i think this can be closed, speed can already be implemented by using seek for every frame together with frame length. Awesome job!

**Comment by koral--** [comment]
Theoretically it is tricky to check if GIF is actually opaque, but we can introduce some simplified algorithm:

1. If there is background color defined then GIF has to be opaque.

2. If there is a frame which covers entire canvas and it has no transparent flag set then GIF has to be opaque.

Theoretically cases when transparency flag is set but transparent color index is not actually used anywhere can also exist. It seems that it is not worth detecting them.

**Comment by frmz** [comment]
I think a "greedy" approach is more than enough and would save CPU in most cases. I assume this speeds up the decoding algorithm but you can still use an RGBA texture in OpenGL for example
