### ISSUE TITLE
NativeScript Plugin: remote url support question

### ISSUE THREAD

**Issue by bradmartin** [koral--/android-gif-drawable#278]
I can't find a definitive answer, with my limited Android knowledge, how I would use a remote http url and assign it correctly do a `GifDrawable()`. I've tried using *InputStream* but I wanted to make sure there wasn't some simple way to pass in a remote url

- https://media4.giphy.com/media/BgBf6pW9qOgQU/200.gif

and things just work.

I've went through the source and checked the previously closed issues asking for url support, but the answer didn't help me out much. Apologies, I'm not a native android developer, which is why I use NativeScript, I just know the bare minimum Android/Java 😄 . I have a working plugin with local files but can't figure out how to use something programmatically with a remote url.

An example in Java on how to construct a *GifDrawable* with a remote url would be great. Thanks.

**Comment by koral--** [comment]
This library currently does not provide direct support for loading GIFs from remote URLs. There is an open issue for such feature: #113.
I'm not sure yet how API for this will look like. Callers may want to specify authorization headers, caching options etc. not only URL. 

Currently you have to buffer your GIF. Eg. this is one of the simplest examples (assumes that `Content-Length` header is present and its value is positive):
```java
String url = "https://media4.giphy.com/media/BgBf6pW9qOgQU/200.gif";
URLConnection urlConnection = new URL(url).openConnection();
urlConnection.connect();
final int contentLength = urlConnection.getContentLength();
ByteBuffer buffer = ByteBuffer.allocateDirect(contentLength);
ReadableByteChannel channel = Channels.newChannel(urlConnection.getInputStream());
while (buffer.remaining() > 0)
	channel.read(buffer);
channel.close();
GifDrawable drawable = new GifDrawable(buffer);
```

**Comment by bradmartin** [comment]
Thank you for that sample code. I think I can work with that 👍 . Would you support adding a link to the NativeScript-Gif plugin repo on the README? If so, I'll submit a PR for that once I finish it up.

**Comment by koral--** [comment]
Sure, PR is welcome.
