### ISSUE TITLE
Optimization cache first frame in opengl.c using double framebuffer

### ISSUE THREAD

**Issue by frmz** [koral--/android-gif-drawable#279]
I think having 2 framebuffers, one static with the first (0) frame and one dynamic with current one currently drawing on GL texture would reduce the CPU usage drastically. With current implementation having full screen animated GIFs is not possible, CPU usage is too high and most of the work is done on frame 0.

**Comment by frmz** [comment]
A probably even better solution for OpenGL would be keeping the last key frame (0 or whatever) in the framebuffer and then replace DGifGetLine calls with [GlTexSubImage2D](https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexSubImage2D.xml) which can replace only a region of the image, this would allow to work directly on the GL FB

**Comment by koral--** [comment]
It seems that everything from this issue is covered by final version of #287, so I'm closing this one.
