### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file

### ISSUE THREAD

**Issue by kaka2009** [koral--/android-gif-drawable#282]
some devices encountered problems such as:
Caused by: java.lang.IllegalStateException: Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file

I only use the armeabi folder，Should be down compatible

**Comment by koral--** [comment]
Is it the same case as in #237? see especially https://github.com/koral--/android-gif-drawable/issues/237#issuecomment-168169705

**Comment by kaka2009** [comment]
solved
