### ISSUE TITLE
GifError 103: Data is not in GIF format

### ISSUE THREAD

**Issue by xiongcen** [koral--/android-gif-drawable#286]
gif path ：http://dingyue.nosdn.127.net/iWg8lN5i5jFj4My8Qs5sDuYbuk9t6bVcS7UBTNRzn5fns1460621552294.gif
exception：

04-26 00:31:18.120 11576-11576/  W/System.err: pl.droidsonroids.gif.GifIOException: GifError 103: Data is not in GIF format
04-26 00:31:18.120 11576-11576/  W/System.err:     at pl.droidsonroids.gif.GifInfoHandle.openFile(Native Method)
04-26 00:31:18.120 11576-11576/  W/System.err:     at pl.droidsonroids.gif.GifInfoHandle.<init>(GifInfoHandle.java:49)
04-26 00:31:18.120 11576-11576/  W/System.err:     at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:123)

**Comment by koral--** [comment]
That link points to webp image, only last 3 charcaters is '.gif':
```
iWg8lN5i5jFj4My8Qs5sDuYbuk9t6bVcS7UBTNRzn5fns1460621552294.gif: RIFF (little-endian) data, Web/P image, VP8 encoding, 600x399, Scaling: [none]x[none], YUV color, decoders should clamp
```
This library does not support webp, however there is plan to add it in the future: https://github.com/koral--/android-gif-drawable/issues/147

**Comment by xiongcen** [comment]
I think the picture is a special picture. https://en.wikipedia.org/wiki/GIF  #Example GIF file introduce this special type.It only has one frame.

**Comment by koral--** [comment]
First file in that section: https://upload.wikimedia.org/wikipedia/commons/1/19/GifSample.gif is GIF and it supported correctly. If you meant another one please post a link in comment.

**Comment by xiongcen** [comment]
Your first answer say：That link points to webp image, only last 3 charcaters is '.gif'. Fresco support method to decide whether a GIF image is animated or not, through checks if source contains more than one frame header in it.But I don't know how  to distinguish between gif and webp. So I think it is a special GIF.May be I made a mistake. I will take a closer look at gif and webp. Thank you~

**Comment by koral--** [comment]
WebP is newer image format, distinct from GIF: https://en.wikipedia.org/wiki/WebP
