### ISSUE TITLE
Proguard UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Ewg777** [koral--/android-gif-drawable#289]
Version 1.1.15 and 1.1.16-snapshot
```java
java.lang.UnsatisfiedLinkError: Native method not found: pl.droidsonroids.gif.GifInfoHandle.a:(Ljava/io/FileDescriptor;JZ)J
    at pl.droidsonroids.gif.GifInfoHandle.a(Native Method)
    at pl.droidsonroids.gif.GifInfoHandle.<init>(SourceFile:61)
    at pl.droidsonroids.gif.a.<init>(SourceFile:159)
    at pl.droidsonroids.gif.a.<init>(SourceFile:94)
```
Usage:
```java
GifDrawable gifDrawable = null;
try {
    gifDrawable = new GifDrawable(getResources(), R.drawable.giiif);
} catch (IOException e) {
}
gifImageView.setImageDrawable(gifDrawable);
```
How to solve this issue?
@koral--

**Comment by koral--** [comment]
It seems that native method has been obfuscated. Default proguard rules (those one applied by eg. `getDefaultProguardFile('proguard-android-optimize.txt')` in `build.gradle` already contains rule to keep native methods. If you are not using default rules from android sdk or you modified them then you have to add custom rule like that:
```
-keepclasseswithmembernames class * {
    native <methods>;
}
```
That is rule from `proguard-android-optimize.txt`.
