### ISSUE TITLE
[Question] Initialization Step And Repeat Step

### ISSUE THREAD

**Issue by TurKurT656** [koral--/android-gif-drawable#294]
Hi,
TnQ for this great lib. its amazing and happy to see this lib.
I have a question:
i have 2gifs. i want first gif plays one time and exactly after that in the same view other gif start to play repeatly.
how can i do that?

best regards

**Comment by koral--** [comment]
You can add `AnimationListener` to `GifDrawable`. `onAnimationCompleted()` will be called when animation loop is finished. There is an [example in sample project](https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/AnimationControlFragment.java#L59). There you can change `Drawable` in `View`.
If that second GIF has loop count different than infinity, you can change it using `GifDrawable.setLoopCount(0)`.
