### ISSUE TITLE
Sample compile error - sample:compileDebugJavaWithJavac failed

### ISSUE THREAD

**Issue by speedpursuer** [koral--/android-gif-drawable#296]
Hello Koral,

I wanted to see how the sample works but got several compile errors as below:

__________________________________________________________________

1 ~/sample/src/main/java/pl/droidsonroids/gif/sample/GifTexImage2DFragment.java:121:Methods getWidth() and getHeight() not found;

glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, mGifTexImage2D.getWidth(), mGifTexImage2D.getHeight(), 0, GL_RGBA, GL_UNSIGNED_BYTE, null);

2 ~/sample/src/main/java/pl/droidsonroids/gif/sample/GifTexImage2DFragment.java:131: Methods glTexSubImage2D() not found;

mGifTexImage2D.glTexSubImage2D(GL_TEXTURE_2D, 0);

3 ~/sample/src/main/java/pl/droidsonroids/gif/sample/sources/GifSourceItemHolder.java:22: Not suitable constructor with parameter found;

multiCallback= new MultiCallback(true);

__________________________________________________________________

I checked the related classes and the problems do exists. Would you please help advice how I can get them resolved?

Thank you!

**Comment by koral--** [comment]
It seems that submodule is not at the correct revision.
Check if `.gitmodules` file contents is like that:
```
[submodule "android-gif-drawable"]
        branch = dev
        path = android-gif-drawable
        url = https://github.com/koral--/android-gif-drawable.git
```
and then call `git submodule update --remote`.

**Comment by speedpursuer** [comment]
Thanks for your help! I did what you said but the compile errors remain. 

Let me take this for example - class 'GifTexImage2D'. There is no method "glTexSubImage2D" mentioned in the javadoc (http://www.javadoc.io/doc/pl.droidsonroids.gif/android-gif-drawable/1.1.15) either. 

Is it because the class 'GifTexImage2DFragment' that calls 'glTexSubImage2D' is not at the currect revison?

I copied the entire class content as follows:

package pl.droidsonroids.gif.sample;

import android.content.pm.FeatureInfo;
import android.opengl.GLSurfaceView;
import android.os.Bundle;
import android.support.design.widget.Snackbar;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.FloatBuffer;

import javax.microedition.khronos.egl.EGLConfig;
import javax.microedition.khronos.opengles.GL10;

import pl.droidsonroids.gif.GifTexImage2D;
import pl.droidsonroids.gif.InputSource;

import static android.opengl.GLES20.GL_FLOAT;
import static android.opengl.GLES20.GL_FRAGMENT_SHADER;
import static android.opengl.GLES20.GL_LINEAR;
import static android.opengl.GLES20.GL_RGBA;
import static android.opengl.GLES20.GL_TEXTURE_2D;
import static android.opengl.GLES20.GL_TEXTURE_MIN_FILTER;
import static android.opengl.GLES20.GL_TRIANGLE_STRIP;
import static android.opengl.GLES20.GL_UNSIGNED_BYTE;
import static android.opengl.GLES20.GL_VERTEX_SHADER;
import static android.opengl.GLES20.glAttachShader;
import static android.opengl.GLES20.glBindTexture;
import static android.opengl.GLES20.glCompileShader;
import static android.opengl.GLES20.glCreateProgram;
import static android.opengl.GLES20.glCreateShader;
import static android.opengl.GLES20.glDrawArrays;
import static android.opengl.GLES20.glEnableVertexAttribArray;
import static android.opengl.GLES20.glGenTextures;
import static android.opengl.GLES20.glGetAttribLocation;
import static android.opengl.GLES20.glGetUniformLocation;
import static android.opengl.GLES20.glLinkProgram;
import static android.opengl.GLES20.glShaderSource;
import static android.opengl.GLES20.glTexImage2D;
import static android.opengl.GLES20.glTexParameteri;
import static android.opengl.GLES20.glUniform1i;
import static android.opengl.GLES20.glUseProgram;
import static android.opengl.GLES20.glVertexAttribPointer;

public class GifTexImage2DFragment extends BaseFragment {

	private static final String VERTEX_SHADER_CODE =
			"attribute vec4 position;" +
					"attribute vec4 coordinate;" +
					"varying vec2 textureCoordinate;" +
					"void main()" +
					"{" +
					"    gl_Position = position;" +
					"    textureCoordinate = vec2(coordinate.s, 1.0 - coordinate.t);" +
					"}";

	private static final String FRAGMENT_SHADER_CODE =
			"varying vec2 textureCoordinate;" +
					"uniform sampler2D texture;" +
					"void main() { " +
					"    gl_FragColor = texture2D(texture, textureCoordinate);" +
					"}";

	private GifTexImage2D mGifTexImage2D;

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		try {
			mGifTexImage2D = new GifTexImage2D(new InputSource.ResourcesSource(getResources(), R.drawable.anim_flag_chile));
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		if (!isOpenGLES2Supported()) {
			Snackbar.make(container, R.string.gles2_not_supported, Snackbar.LENGTH_LONG).show();
			return null;
		}
		final GLSurfaceView view = (GLSurfaceView) inflater.inflate(R.layout.opengl, container, false);
		view.setEGLContextClientVersion(2);
		view.setRenderer(new Renderer());
		mGifTexImage2D.startDecoderThread();
		return view;
	}

	@Override
	public void onDestroyView() {
		mGifTexImage2D.recycle();
		super.onDestroyView();
	}

	class Renderer implements GLSurfaceView.Renderer {

		@Override
		public void onSurfaceCreated(GL10 gl, EGLConfig config) {
			int[] texNames = {0};
			glGenTextures(1, texNames, 0);
			glBindTexture(GL_TEXTURE_2D, texNames[0]);
			glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

			final int vertexShader = loadShader(GL_VERTEX_SHADER, VERTEX_SHADER_CODE);
			final int pixelShader = loadShader(GL_FRAGMENT_SHADER, FRAGMENT_SHADER_CODE);
			final int program = glCreateProgram();
			glAttachShader(program, vertexShader);
			glAttachShader(program, pixelShader);
			glLinkProgram(program);
			int position = glGetAttribLocation(program, "position");
			int texture = glGetUniformLocation(program, "texture");
			int coordinate = glGetAttribLocation(program, "coordinate");
			glUseProgram(program);

			FloatBuffer textureBuffer = createFloatBuffer(new float[]{0, 0, 1, 0, 0, 1, 1, 1});
			FloatBuffer verticesBuffer = createFloatBuffer(new float[]{-1, -1, 1, -1, -1, 1, 1, 1});
			glVertexAttribPointer(coordinate, 2, GL_FLOAT, false, 0, textureBuffer);
			glEnableVertexAttribArray(coordinate);
			glUniform1i(texture, 0);
			glVertexAttribPointer(position, 2, GL_FLOAT, false, 0, verticesBuffer);
			glEnableVertexAttribArray(position);
			glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, mGifTexImage2D.getWidth(), mGifTexImage2D.getHeight(), 0, GL_RGBA, GL_UNSIGNED_BYTE, null);
		}

		@Override
		public void onSurfaceChanged(GL10 gl, int width, int height) {

		}

		@Override
		public void onDrawFrame(GL10 gl) {
			mGifTexImage2D.glTexSubImage2D(GL_TEXTURE_2D, 0);
			glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
		}
	}

	static int loadShader(int shaderType, String source) {
		int shader = glCreateShader(shaderType);
		glShaderSource(shader, source);
		glCompileShader(shader);
		return shader;
	}

	static FloatBuffer createFloatBuffer(float[] floats) {
		FloatBuffer fb = ByteBuffer
				.allocateDirect(floats.length * 4)
				.order(ByteOrder.nativeOrder())
				.asFloatBuffer();
		fb.put(floats);
		fb.rewind();
		return fb;
	}

	private boolean isOpenGLES2Supported() {
		FeatureInfo[] featureInfos = getContext().getPackageManager().getSystemAvailableFeatures();
		if (featureInfos != null) {
			for (FeatureInfo featureInfo : featureInfos) {
				if (featureInfo.name == null) {
					return ((featureInfo.reqGlEsVersion & 0xffff0000) >> 16) >= 2;
				}
			}
		}
		return false;
	}

}

**Comment by koral--** [comment]
`glTexSubImage2D()` has been added in version 1.1.16, which is currently SNAPSHOT and is not uploaded yet to maven central repository. So the latest javadoc is for 1.1.15.
Submodule should be at revision `650c0` (the latest commit in dev branch). Current sample code requires that revison. 
It seems that you have not switched successfully to the correct revision or clean build is required.
First check if your submodule is at the correct revison eg. using `git log`. The topmost commit should be `commit 650c0ccdd2bed7264fed4863bec9a69ef9d123e2`. If it isn't you can manually checkout it: `git checkout 650c0`. Then do a clean build.

**Comment by speedpursuer** [comment]
Thank you! The sample works by following your guidance to manually get the right revision. BTW, I noticed some other build errors show up in console that they don't seem to matter. I attached a screenshot for your reference.
![Uploading screen.jpg…]()

Can I also check if you are going to integrate any load/cache lib (e.g fresco or Android-Universal-Image-Loader) just like what PINRemoteImage does for iOS that combines itself with FLAnimatedImages to become a more comprehensive animated image solution?

Thanks again for your help!

**Comment by koral--** [comment]
Those errors are caused by leakcanary (external library to detect memory leaks). They are harmless. Here is an issue about in leakcanary repo: https://github.com/square/leakcanary/issues/491. You can remove leakcanary from sample project or fix it to get rid of them.
Asynchronous GIF loading is planned to be done in the future.
