### ISSUE TITLE
Fatal Error!  Gif drawable crashes all the time .

### ISSUE THREAD

**Issue by hopein** [koral--/android-gif-drawable#297]
Hi, thanks for your gif-drawable project.  Now, I need your help.   I meet a gif-drawable that crashes all the time when using gif-drawable.  Get the native crash log  below:
#0
Crashed: ex.omomo
SIGSEGV SEGV_MAPERR 0x7fffffffffffffff
"Crashed: ex.omomo
0  libpl_droidsonroids_gif.so     0x89bbab4c (Missing)"

This is the gif resource url : 
http://image.baidu.com/search/detail?z=0&ipn=d&word=%E7%B2%89%E8%89%B2%E5%B0%8F%E7%8C%AAgif%E5%9B%BE&step_word=&pn=3&spn=0&di=0&pi=&tn=baiduimagedetail&istype=0&ie=utf-8&oe=utf-8&cs=2402111992%2C394379305&os=3796511364%2C307899831&simid=&adpicid=0&fr=&fm=&sme=&cg=&bdtype=14&simics=3095129420%2C3797481844&oriquery=&objurl=http%3A%2F%2F2b.zol-img.com.cn%2Fproduct%2F97_500x2000%2F287%2FcejA3mM6Nk1uc.gif&fromurl=ippr_z2C%24qAzdH3FAzdH3Fn2_z%26e3Bz5s_z%26e3Bv54_z%26e3BvgAzdH3Fp57viAzdH3Fw6ptvsjAzdH3FdldmAzdH3Fndnmmcl_8_8_z%26e3Bip4s&gsm=0&cardserver=1

Hope your reguards, It's very urgent.

**Comment by koral--** [comment]
OK, I'll check this ASAP.

**Comment by koral--** [comment]
Fixed, thanks for the report.
