### ISSUE TITLE
Question: is per frame duration really used or i can assume all frames have equal one

### ISSUE THREAD

**Issue by frmz** [koral--/android-gif-drawable#299]
This is not about the library but more about the standard, i read through the GIF docs but didn't find a proper answer. So, question is, i see that every frame has a duration when you decode them but is that really used anywhere? Can i assume that all frames are the same length or it really happens to have different lengths in the real world?

**Comment by koral--** [comment]
It seems that the vast majority of GIFs in the the real world has the same duration for all its frames. But examples with variable durations also exist, eg: http://i.stack.imgur.com/SU9iR.gif. That one comes from this thread on SO: http://stackoverflow.com/questions/9812589/how-to-determine-the-length-of-a-gif-animation-in-milliseconds which is at the 1st page of search results for phrase "gif duration" in google at the time of writing.
So I would say that is not safe to assume that all the GIFs has constant frame duration.
