### ISSUE TITLE
Class cast exception 

### ISSUE THREAD

**Issue by uzghun** [koral--/android-gif-drawable#303]
Some times app crashes with class cast exception.

java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to pl.droidsonroids.gif.GifViewSavedState

**Comment by koral--** [comment]
One of the possible reasons is that you have extended one of the library `View`s like `GifTextView` and overrode onSave/onRestoreInstanceState method(s) in a way that saved state received in `onRestoreInstanceState` is not an instance of `GifViewSavedState`.
To restore view state correctly pattern with passing superclass state has to be followed, eg. this is how [CompoundButton](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/widget/CompoundButton.java#544) from Android framework implements it. As you can see `ClassCastException` will also occur in analogous case with `CompoundButton`.

However I just discovered that some framework classes eg. [TextView](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/widget/TextView.java#4061) uses more lenient rules.

I can add similar behavior to library classes, so if you pass something which is not an instance of `GifViewSavedState` then state restoration will be ignored (except for calling superclass method).

If it is not the case please post more info including complete stacktrace and code snippet how you are using library classes.
