### ISSUE TITLE
Avoiding OutOfMemoryError

### ISSUE THREAD

**Issue by jaredrummler** [koral--/android-gif-drawable#304]
I want to save each frame to local storage. When I get a list of `Bitmap`s for a GIF that has many frames I am getting an `OutOfMemoryError`.

Example code:

```java
GifDrawable gif = new GifDrawable(getAssets(), "test.gif");

int numberOfFrames = gif.getNumberOfFrames();

List<Bitmap> bitmaps = new ArrayList<>(numberOfFrames);

for (int i = 0; i < numberOfFrames; i++) {
  Bitmap bitmap = gif.seekToFrameAndGet(i);
  bitmaps.add(bitmap);
}

// .. do stuff with the frames

```

There is a lot on this topic on StackOverflow and elsewhere. Adding `android:largeHeap="true"` to the application tag in the `AndroidManifest` helps. However, I'm sure there is a better way to do this.

What would be an optimal way to extract each frame of a GIF and avoid an `OutOfMemoryError`? Hopefully this question isn't beyond the scope of this library. Thanks.

**Comment by koral--** [comment]
If you don't actually need all the bitmaps at the same time but can process them sequentially then you can create one bitmap and use it for all frames, there is an API for that case: [GifDecoderl#seekToFrame](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.1.15/pl/droidsonroids/gif/GifDecoder.html#seekToFrame-int-android.graphics.Bitmap-).

If you really need all frames at same time you can reduce amount of needed memory by subsampling (also available in library) and/or transforming them eg. to config RGB_565.
