### ISSUE TITLE
Gif render issue with transparent pixels

### ISSUE THREAD

**Issue by mmin18** [koral--/android-gif-drawable#305]
This gif is not rendering correctly. (It renders correctly on iOS and other libraries)
![a](https://cloud.githubusercontent.com/assets/748883/15467141/80200f4c-210f-11e6-84bf-51026665c61e.gif)

The first frame is correct, but on second frame there are some transparent pixels.
The first frame's bitmap need to be kept when rendering the second frame.
![0](https://cloud.githubusercontent.com/assets/748883/15467152/9027911c-210f-11e6-8111-8e4a9cb2282b.png)
![1](https://cloud.githubusercontent.com/assets/748883/15467151/901eec42-210f-11e6-84e7-2f32bcd8cced.png)

**Comment by koral--** [comment]
Fixed, thanks for the report.
BTW actually first frame was incorrect and that was the reason why several next was also affected.
