### ISSUE TITLE
ImageLoader

### ISSUE THREAD

**Issue by Fisherman91** [koral--/android-gif-drawable#307]
不支持ImageLoader吗，有没有好的方案，自己去做缓存？

**Comment by koral--** [comment]
According to current translation from Google translate: "ImageLoader do not support, there is no good solution to do their own cache?"
There is currently no built-in support for asynchronous loading nor for caching, but it is planned to add such in the future.
You can implement those features yourself. If HTTP responses contains cache-related headers then you can use library like okhttp and few lines of code similar to that snippet: https://github.com/koral--/android-gif-drawable/issues/278#issuecomment-212223617

PS 
Please write in English.
