### ISSUE TITLE
Can't play this gif

### ISSUE THREAD

**Issue by kakai248** [koral--/android-gif-drawable#309]
It only shows the first frame but doesn't play. But it says it has 122 frames.

https://s-media-cache-ak0.pinimg.com/originals/01/06/fa/0106fabc5834b727e84f60ed81911ab0.gif

Thanks!

**Comment by koral--** [comment]
I've managed to reproduce this issue, will fix it ASAP.

**Comment by koral--** [comment]
Fixed in `1.1.17-SNAPSHOT`. Thanks for the report.

**Comment by kakai248** [comment]
That was fast! Thank you for your work.
