### ISSUE TITLE
java.io.FileNotFoundException on Android Studio 2.2 Preview 3

### ISSUE THREAD

**Issue by AndroidGecko** [koral--/android-gif-drawable#310]
getting stacktrace
```
System.err  W  java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
                         W      at android.content.res.AssetManager.openAssetFd(Native Method)
                         W      at android.content.res.AssetManager.openFd(AssetManager.java:329)
                         W      at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:110)
```
on Android Studio 2.2 Preview 3
unzipped apk to check if gifs were manipulated but they are the same. Even without using :
```
android {
    aaptOptions {
        noCompress "gif"
    }
}
```
Went back to AS 2.1.2 and everything works.

Anyone else having this issue?

**Comment by koral--** [comment]
I've managed to reproduce this issue in AS 2.1.2 when using current alpha android gradle plugin (version `2.2.0-alpha3`).
Workaround is to use earlier working version of the plugin eg.:
`classpath 'com.android.tools.build:gradle:2.2.0-alpha2'`.

**Comment by DanielS1980** [comment]
Hi, 

I see the thread is closed but the bug ate a few of my project's days so i feel like sharing the solution a little in detail.
1) Goto your project folder "...\MyProject\".
2) Search for "build.gradle" file.
3) Replace
classpath 'com.android.tools.build:gradle:2.2.0-alpha3'
with
classpath 'com.android.tools.build:gradle:2.1.0'

2.1.0 worked for me.

**Comment by koral--** [comment]
All versions below `2.2.0-alpha3` should work. The newest stable (non-alpha) is currently `2.1.2`.

**Comment by faruktoptas** [comment]
I faced the same problem. Downgrading gradle version from 2.2.0 to 2.1.2 solved the problem.

**Comment by koral--** [comment]
It seems that `2.2.0` (final, no alpha nor beta) and `2.2.1` are not affected by this issue.
