### ISSUE TITLE
GIF does not get effect while adding in to editext

### ISSUE THREAD

**Issue by manoj99** [koral--/android-gif-drawable#311]
Hi im used image-span to add gif into editext  but problem is that it cant get move.it is just get stuck.
--here is my snippet
-----------------------------------------------------------------------
GifDrawable d = null;
			try {
				// d = new GifDrawable(getAssets(), strcomman);
				d = new GifDrawable("/data/data/" + packagename
						+ "/asset_goods/" + strcomman);
			} catch (IOException e) {
				e.printStackTrace();
			}
			_calulcatewidth = (d.mSrcRect.right * 1f / d.mSrcRect.bottom * 1f);

			d.setBounds(0, 0, (int) (_calulcatewidth * _scale), _scale);

			ImageSpan span = new ImageSpan(d, ImageSpan.ALIGN_BASELINE);
			ss.setSpan(span, 0, 1, Spannable.SPAN_INCLUSIVE_EXCLUSIVE);
			cs = ss;
			stringbuilder.insert(i, cs);
			textflag.setText(stringbuilder);//this is editext where i set gif.

**Comment by koral--** [comment]
You have to assign callback to your `GifDrawable`. Here is an example: https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/ImageSpanFragment.java
