### ISSUE TITLE
ImageSpan in TextView not playing

### ISSUE THREAD

**Issue by guytkix** [koral--/android-gif-drawable#312]
Hi,

I have a TextView with an ImageSpan inside of an adapter which contains a GifDrawable and it is not playing. Weirdly enough it sometimes plays a few frames when the there is some screen invalidation but it is not consistent. I have used the same code as you - added callbacks and then your MultiCallback but it is still not working. I have looked at the sample app and it seems like it is not working as well, source_item.xml contains three views, the image views work fine but the TextView shows no drawable. I have managed to show the drawable by setting its width and height like this:

subsampledDrawable.setBounds(0, 0, subsampledDrawable.getIntrinsicWidth(), subsampledDrawable.getIntrinsicHeight());

and now the drawable is visible but does not animate.

Am I missing something?

many thanks,
Guy

**Comment by koral--** [comment]
Could you post your code? It seems that callback is garbage collected. You need to keep strong reference to callback.

**Comment by guytkix** [comment]
Wow... made a few more attempts to understand the issue and just figured it. My TextView has a property of  android:textIsSelectable="true" and this is what is causing the problem. I need to have the text selectable and with animated Gifs, any ideas?

**Comment by guytkix** [comment]
Saw your answer in issue #234
