### ISSUE TITLE
Can I chose .so file I need?

### ISSUE THREAD

**Issue by tinybright** [koral--/android-gif-drawable#313]
I need only armeabi.But you provide def flavors = ['armeabi', 'armeabi-v7a', 'x86', 'mips', 'arm64-v8a', 'mips64', 'x86_64'].

**Comment by koral--** [comment]
Just add `ndkConfig.abiFilters 'armeabi'` to your `build.gradle` inside `defaultConfig`, build type or product flavor configuration closure eg:
```
defaultConfig {
    ndkConfig.abiFilters 'armeabi'
}
```

Those flavors are not used normally, they are only added as a workaround for bug in Nokia X SDK.
