### ISSUE TITLE
the same filepath on different phone one catch GifIOException: GifError 102: Failed to read from given input when new GifDrawable(path);

### ISSUE THREAD

**Issue by lekenny** [koral--/android-gif-drawable#314]
W/System.err: pl.droidsonroids.gif.GifIOException: GifError 102: Failed to read from given input

one phone samsungA7
author one samsung galaxy s5

path:/storage/emulated/0/gif/d9376524ce2bc8d9fd9e0b7b58a56303

**Comment by koral--** [comment]
Error 102 occurs when file has been opened successfully but its contents is not recognized as a GIF. Are you sure that file content is the same on both devices?

**Comment by lekenny** [comment]
After check i see it's Null bytes . thanks!
