### ISSUE TITLE
How to reduce cpu usage?

### ISSUE THREAD

**Issue by tuzhao** [koral--/android-gif-drawable#315]
I have clone the sample project and run it.I found it seems let cpu usage a little high.Is that normal?
[
![2016-06-30 10 53 46](https://cloud.githubusercontent.com/assets/9989910/16475463/63cbdd5c-3eb1-11e6-8270-05a0720a251f.png)
](url)

**Comment by tuzhao** [comment]
it's my fault,just cause a little cpu usage.it is very nice library,thanks author!

**Comment by MartinLi2015** [comment]
I meet the same problem.how did you to solve it?

**Comment by MartinLi2015** [comment]
![image](https://user-images.githubusercontent.com/7964562/76040219-c0eae800-5f89-11ea-8bd0-03e6147bdbcb.png)
