### ISSUE TITLE
Crash on recycled bitmap

### ISSUE THREAD

**Issue by EugineKidoz** [koral--/android-gif-drawable#316]
Exception java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@426abb10
android.graphics.Canvas.throwIfCannotDraw (Canvas.java:1084)
android.view.GLES20Canvas.drawBitmap (GLES20Canvas.java:844)
pl.droidsonroids.gif.GifDrawable.draw (GifDrawable.java:730)
android.widget.ImageView.onDraw (ImageView.java:1019)
android.view.View.draw (View.java:14728)
android.view.View.getDisplayList (View.java:13588)
android.view.View.getDisplayList (View.java:13635)
android.view.View.draw (View.java:14430)
android.view.ViewGroup.drawChild (ViewGroup.java:3252)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3070)
android.view.View.getDisplayList (View.java:13580)
android.view.View.getDisplayList (View.java:13635)

Happens some time, unable to reproduce it manually.

**Comment by koral--** [comment]
Only way (excluding access to private fields via reflection) to recycle bitmap inside `GifDrawable` is to call `GifDrawable#recycle()` but it is never invoked from library code. It seems that you are recycling drawable from somewhere in your code when it is still associated with `ImageView`.
Throwing exception when trying to access pixels from recycled bitmap is not a bug. Drawable must not be drawn after recycling.

**Comment by liauli** [comment]
Hi koral,
I didn't call any recycle() yet it's still crashing. I am sure it's from this library because when I tried to hide it, nothing happen. in my app the gif might interrupted many times and need to start a gif again from beginning after interruption. I tried to call stop() and invalidateSelf() when it's interrupted but still crashing. do you have any idea why?

**Comment by koral--** [comment]
Could you share the minimal code sample which reproduces this issue?
