### ISSUE TITLE
How can i remove mips

### ISSUE THREAD

**Issue by zlm54585652** [koral--/android-gif-drawable#318]
jniLibs clash mips  folder.

**Comment by zlm54585652** [comment]
And i can't open it in my Android Studio

**Comment by koral--** [comment]
I'm not sure what you are asking. What is error message?

**Comment by zlm54585652** [comment]
def flavors = ['armeabi', 'armeabi-v7a', 'x86', 'mips', 'arm64-v8a', 'mips64', 'x86_64']
    I just want armeabi  armeabi-v7a  x86  In my project  , I can't use 64 bit jni .
so can I let View 32 bit compatible use in my project .

**Comment by koral--** [comment]
This exactly the same question: https://github.com/koral--/android-gif-drawable/issues/313#issuecomment-226994594
