### ISSUE TITLE
in some phone Error inflating class 

### ISSUE THREAD

**Issue by lekenny** [koral--/android-gif-drawable#320]
`I/dalvikvm: Could not find method pl.droidsonroids.gif.GifViewUtils.initImageView, referenced from method pl.droidsonroids.gif.GifImageView.<init>`
`W/dalvikvm: VFY: unable to resolve static method 64823: Lpl/droidsonroids/gif/GifViewUtils;.initImageView (Landroid/widget/ImageView;Landroid/util/AttributeSet;II)Lpl/droidsonroids/gif/GifViewUtils$InitResult;`

` android.view.InflateException: Binary XML file line #24: Error inflating class pl.droidsonroids.gif.GifImageView`
`Caused by: java.lang.reflect.InvocationTargetException`
`Caused by: java.lang.NoClassDefFoundError: pl.droidsonroids.gif.GifViewUtils`

**Comment by koral--** [comment]
Are you using multidex and/or proguard?

**Comment by lekenny** [comment]
@koral--    I've set  `multiDexEnabled true`

**Comment by lekenny** [comment]
but  in another phone it's ok

**Comment by koral--** [comment]
Multidex misconfiguration may be the cause. See this comment: https://github.com/koral--/android-gif-drawable/issues/224#issuecomment-154769230 
Do you have complete configuration?
Android >= 5.0 has native multidex support while lower versions require multidex support library. This may be source of behavior differences.
What is the model and android version of affected device?

In general this kind of errors look like a packaging issue on app side. Class `GifViewUtils` is present in library sources (https://github.com/koral--/android-gif-drawable/blob/master/src/main/java/pl/droidsonroids/gif/GifViewUtils.java) and artifacts in maven repos.

**Comment by lekenny** [comment]
thanks
