### ISSUE TITLE
java.lang.OutOfMemoryError?

### ISSUE THREAD

**Issue by yanglichuan** [koral--/android-gif-drawable#321]
java.lang.OutOfMemoryError
解析原始
}
1 android.graphics.Bitmap.nativeCreate(Native Method)
2 android.graphics.Bitmap.createBitmap(Bitmap.java:669)
3 android.graphics.Bitmap.createBitmap(Bitmap.java:649)
4 pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:229)
5 pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:160)
6 pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:110)

**Comment by koral--** [comment]
It seems that GIF size in pixels is too large. You can construct `GifDrawable` using builder and set sample size: `GifDrawableBuilder#sampleSize()`. It works like [`BitmapFactory.Options#inSampleSize`](https://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inSampleSize).
