### ISSUE TITLE
Can we have a callback function when GifDrawable switch the frame 

### ISSUE THREAD

**Issue by bearprada** [koral--/android-gif-drawable#322]
I like this library because the performance is better. but we don't want to apply it into a `ImageView`. because I want to render the GIF image by Canvas.draw(), so I need to trigger `View.postInvalidate()` when the encoder try to switch the next frame.

I know it's not a normal case for this library, I just workaround this in this commit 
https://github.com/bearprada/android-gif-drawable/commit/5c2177035dcb83f3507829d61707188009e6682d

do you guys have any suggestion for this use case ?

**Comment by koral--** [comment]
If I understand correctly you have custom `View` and want to draw animated `GifDrawable` on its `Canvas`.
One of the easiest solutions is to set that `View` as a callback: `drawable.setCallback(view);`. You have to override `View.verifyDrawable()` to return `true` for your drawable.
Does it answer your question?

**Comment by bearprada** [comment]
thanks @koral-- it works for me :)
