### ISSUE TITLE
How can i use this in Android.mk?

### ISSUE THREAD

**Issue by godguy213** [koral--/android-gif-drawable#325]
hi, koral, How can i use this lib in my Android.mk?

**Comment by koral--** [comment]
If you want to use this lib as a sources then you need to add `LOCAL_SHARED_LIBRARIES := pl_droidsonroids_gif` and/or `pl_droidsonroids_gif_surface`. Of course all the native sources and content of `Android.mk` lib have to be also included in your sources. Here is the example how `pl_droidsonroids_gif_surface` module is linked with `pl_droidsonroids_gif`: https://github.com/koral--/android-gif-drawable/blob/f1d2a922b55699ea8e4a1b253d9f23185d08a2a7/src/main/jni/Android.mk

If you want to use prebuilt binaries (`.so` files in case of dynamically linked library) you can follow this official guide: https://developer.android.com/ndk/guides/prebuilts.html
You need to copy library header file(s) into your sources.

**Comment by godguy213** [comment]
thanks man.
