### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by TheMelody** [koral--/android-gif-drawable#326]
java.lang.OutOfMemoryError: Could not get bitmap info
	at pl.droidsonroids.gif.GifInfoHandle.renderFrame(Native Method)
	at pl.droidsonroids.gif.GifInfoHandle.a(GifInfoHandle.java:147)
	at pl.droidsonroids.gif.n.a(RenderTask.java:17)
	at pl.droidsonroids.gif.c.<init>(GifDrawable.java:235)
	at pl.droidsonroids.gif.c.<init>(GifDrawable.java:123)

**Comment by koral--** [comment]
This is not a bug in library, basically your app runs out of memory. You need to modify your code to reduce memory consumption.

Here are some tips:
- If you are working with large-sized GIFs you can subsample them, see: https://github.com/koral--/android-gif-drawable/issues/284#issuecomment-214376600
- You can use tools like MAT, or [Memory Monitor in Android Studio](https://developer.android.com/studio/profile/am-memory.html) to locate potential causes.
- You can increase available heap space by using `android:largeHeap="true"` in `AndroidManifest.xml` or dividing app to separate processes (by adding `android:process` tags) but those workarounds may cause side-effects
