### ISSUE TITLE
Gif stop, don't play anymore

### ISSUE THREAD

**Issue by huyduongtu** [koral--/android-gif-drawable#328]
I try with this gif http://cgif.zp.zdn.vn/l0MYtUrKPWCWX2rjq_n.gif. When rendering to a specific frame, the render delay value is nagative. So Gif stops.
But I try it with app Telegram. It's ok.
It happens similarly to many Gif files. Please fix it. Thanks

**Comment by koral--** [comment]
OK, I'll check this.

**Comment by koral--** [comment]
This is not a bug, that GIF file has loop count set to `1` which means that it should play once and this library respects it.
You can override value from file and set your own loop count eg.: `GifDrawable#setLoopCount(0)`, `0` means infinite looping. See here for more info: http://giflib.sourceforge.net/whatsinagif/animation_and_transparency.html

**Comment by huyduongtu** [comment]
Thanks.
