### ISSUE TITLE
GifImageView does not work with GifDrawable

### ISSUE THREAD

**Issue by linhnguyen106** [koral--/android-gif-drawable#329]
I've created GifDrawable from a url 
[https://raw.githubusercontent.com/koral--/android-gif-drawable-sample/cb2d1f42b3045b2790a886d1574d3e74281de743/sample/src/main/assets/Animated-Flag-Hungary.gif;
](url)
then set to GifImageView, it does not work

**Comment by koral--** [comment]
To open GIF from http(s) URL you have to download it yourself. There is a snippet for that in sample project, relevant classes:
https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/GifLoadTask.java
https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.java

`GifDrawable(ContentResolver resolver, Uri uri)` supports URI schemes supported by installed content providers eg. `content://` and `file://`.
