### ISSUE TITLE
First frame overlap to next frames

### ISSUE THREAD

**Issue by kimsg0617** [koral--/android-gif-drawable#330]
hi

I have two gifs.. left.gif and right.gif.

right.gif works very well, but left.gif is strange.

On Web and PC(mac) it doesn't overlap. But on Android, first frame overlap to next frames.. 

Can you explain to me what happens..?

source links :
left.gif - https://www.dropbox.com/s/6iebps0q37mgoza/left.gif?dl=0
right.gif - https://www.dropbox.com/s/rfg4vops7hfkwaz/right.gif?dl=0

**Comment by koral--** [comment]
@kimsg0617 could you attach GIFs to your post? Dropbox links are not working because account is disabled.

**Comment by kimsg0617** [comment]
Oh sorry, I attach file here.

Please check this GIFs. Thank you.

![left](https://cloud.githubusercontent.com/assets/11498807/17543557/6632e812-5f0c-11e6-8d4a-d09bb3d50d65.gif)
![right](https://cloud.githubusercontent.com/assets/11498807/17543558/663e0c2e-5f0c-11e6-8fe4-6eeb78fa7a61.gif)

**Comment by koral--** [comment]
OK, I'll check it ASAP.

**Comment by koral--** [comment]
Fixed. Changes available in `1.1.18-SNAPSHOT`.
Interesting case - in the `left.gif` first frame uses disposal to previous but... there is no previous frame before first one.
I fixed it treating such case as disposal to background, it seems that's how web browsers do. On the other hand, several image viewers both desktop and Android ones also has this bug.

**Comment by kimsg0617** [comment]
Thank you !! 

It works very well.
