### ISSUE TITLE
gif.h:29:10: fatal error: 'sys/eventfd.h' file not found

### ISSUE THREAD

**Issue by huyduongtu** [koral--/android-gif-drawable#331]
My app supports android from version 8 to the lastest. So that I change in `Application.mk` like below:
`APP_PLATFORM := android-8`

I run `ndk-build` and throws compiled error:
```
fatal error: 'sys/eventfd.h' file not found
#include <sys/eventfd.h>

```     
How can I fix it?
Edit: I don't find file `eventfd.h` in android-ndk for platform android 8.

**Comment by koral--** [comment]
Possible solutions:

- If you don't use `GifTextureView` nor `GifTexImage2D` you can exclude files requiring that header from compilation (`opengl.c` and `surface.c`).
- If you use mentioned classes (conditionally if API level at runtime is higher) split native code into 2 modules: one using `APP_PLATFORM := android-9` for that 2 files and `android-8` for the rest

**Comment by huyduongtu** [comment]
Ok. Thanks
