### ISSUE TITLE
LibraryLoader can't be accessed from outside package

### ISSUE THREAD

**Issue by rashadsookram** [koral--/android-gif-drawable#333]
It looks like the access level of `LibraryLoader` was changed to package private as of v1.1.16 in [this commit](https://github.com/koral--/android-gif-drawable/commit/c9923c0cfdf5b2b298f25746512f5d6f61a643c2#diff-04289b7b920eaf658f4990a7c2f4ac4eR13). So now `LibraryLoader#initialize` can't be accessed. It remains this way in the [current master](https://github.com/koral--/android-gif-drawable/blob/b6804650666ea1fd647d2186ef9974b8d9e28a27/src/main/java/pl/droidsonroids/gif/LibraryLoader.java#L13).

Was this an intentional change? If so, is there any other way of enabling the workaround for loading native libraries which don't rely on reflection?

For now, I'm going to use 1.1.15, but it would be great to get this clarified.

**Comment by koral--** [comment]
It wasn't intended change. Fixed in `1.1.18-SNAPSHOT`. Thanks for the report.

**Comment by rashadsookram** [comment]
Thanks for getting to this so quickly!

**Comment by koral--** [comment]
Released in `1.2.0`
