### ISSUE TITLE
Can i set gif image's max size ?

### ISSUE THREAD

**Issue by SwordBearer** [koral--/android-gif-drawable#337]
I have a gif-image ,it's resolution is 2000*2500, but it takes too long time (about 300ms) when i new a GifDrawable with this gif-image, can i set the gif-drawable's max size ?

**Comment by koral--** [comment]
It is partially possible but not directly using size in pixels. You can set [sampleSize](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.0/pl/droidsonroids/gif/GifDrawableBuilder.html#sampleSize-int-). Eg. `sampleSize=2` will give halve both width and height so 2000*2500  px will be reduced to 1000*1250 px.

**Comment by SwordBearer** [comment]
How can I get the gif-image size before new GifDrawable() ?

**Comment by koral--** [comment]
You can create [GifAnimationMetaData](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.0/pl/droidsonroids/gif/GifAnimationMetaData.html) first and then use [#getWidth()](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.0/pl/droidsonroids/gif/GifAnimationMetaData.html#getWidth--), [#getHeight()](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.0/pl/droidsonroids/gif/GifAnimationMetaData.html#getHeight--)
