### ISSUE TITLE
Change src programmatically.

### ISSUE THREAD

**Issue by hirani89** [koral--/android-gif-drawable#339]
I could not find any examples on changing the GIF source from java.

**Comment by koral--** [comment]
Do you mean `android:src` of `GifImageView`/`GifImageButton`? It uses the same API as [ImageView](https://developer.android.com/reference/android/widget/ImageView.html). So you can use [#setImageResource()](https://developer.android.com/reference/android/widget/ImageView.html#setImageResource(int)), [#setImageDrawable()](https://developer.android.com/reference/android/widget/ImageView.html#setImageDrawable(android.graphics.drawable.Drawable)) or so.
