### ISSUE TITLE
Execution failed for task ‘:buildNative’

### ISSUE THREAD

**Issue by androidsihai1** [koral--/android-gif-drawable#341]
Android studio give me a tip  :  A problem ocurred starting process 'command' 'null/ndk-build.cmd' ,I don't know why?I just want to user the demo

**Comment by koral--** [comment]
Path to your NDK installation is missing or invalid. The easiest way to fix it is to set correct path in `local.properties` file in the project root directory (create one if it does not exist). It should look like that `ndk.dir=<path>` where `<path>` should point to NDK installation root directory (one containing `ndk-build.cmd` file).
Alternatively you can use environment variable `ANDROID_NDK_HOME` with that path in value.
Of course you need NDK installed (either standalone or installed from SDK manager in Android Studio).

**Comment by androidsihai1** [comment]
Yor are right ,thank you very much!
