### ISSUE TITLE
Recycle seems to fail silently if GIF is added via XML as android:src

### ISSUE THREAD

**Issue by jacobminer** [koral--/android-gif-drawable#346]
```
<pl.droidsonroids.gif.GifImageView
            android:id="@+id/status_image"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:adjustViewBounds="true"
            android:scaleType="fitCenter"
            android:layout_centerInParent="true"
            android:src="@drawable/other_awesome_gif"
            tools:src="@drawable/awesome_gif"
            tools:visibility="visible" />
```

This is what the flow looks like with `android:src` set.
<img width="878" alt="screen shot 2016-09-22 at 4 57 19 pm" src="https://cloud.githubusercontent.com/assets/13003765/18769936/2a6f996e-80e6-11e6-8a27-3667f62d98ac.png">

<img width="954" alt="screen shot 2016-09-22 at 4 58 01 pm" src="https://cloud.githubusercontent.com/assets/13003765/18769941/2d590ec6-80e6-11e6-8ad3-3dc76a1ee89a.png">

Removing the `android:src="@drawable/other_awesome_gif"` line from my XML dropped my memory usage from ~50MB to ~15MB after cycling through a number of GIFs.

<img width="1100" alt="screen shot 2016-09-22 at 4 59 48 pm" src="https://cloud.githubusercontent.com/assets/13003765/18769956/5976905a-80e6-11e6-8fd0-fb7f0e53d22d.png">

<img width="949" alt="screen shot 2016-09-22 at 5 00 15 pm" src="https://cloud.githubusercontent.com/assets/13003765/18769960/5ddbc12e-80e6-11e6-9884-01e79ba94909.png">

Each of the 9 GIFs is 640x1000 8 bit colour. 

I'm setting the gifs like so 
```
if (drawable != null) {
    drawable.removeAnimationListener(this);
    drawable.stop();
    drawable.recycle();
    drawable = null;
}

status_image.setImageResource(STATE.ID);
drawable = (GifDrawable) status_image.getDrawable();
drawable.addAnimationListener(this);
status_image.setImageDrawable(drawable);
drawable.reset();
drawable.start();
```

I also included this in my Activity's onDestroy
```
@Override
    protected void onDestroy() {
        if (drawable != null) {
            drawable.recycle();
            drawable = null;
        }
        super.onDestroy();
    }
```

Tested this on a Galaxy S7 Edge, Android 6.0.1.

**Comment by koral--** [comment]
`android:src` in `GifImageView` is just an equivalent of `setDrawable(new GifDrawable(...))`. You can get and recycle that drawable before setting new one. 
When your first snippet is executed 1st time (and assumming that `drawable` is null) drawable set from XML stays on heap and is subject to garbage collection. `recycle()` will called by finalizer which is invoked after that drawable is garbage collected, but it may never happen.

I don't see any library error here.
