### ISSUE TITLE
GIfDrawable is not rendering under custom View

### ISSUE THREAD

**Issue by iAlex97** [koral--/android-gif-drawable#347]
Hello,
I need to play an animated GIF on the background of my canvas, but I can't get it to render anything.

I'm loading it like this:

```
AssetFileDescriptor afd = getAssets().openFd( "gifs/anim.gif" );
GifDrawable gifFromAfd = new GifDrawable(afd);

MultiCallback callback = new MultiCallback(true);
callback.addView(mView);

gifFromAfd.setBounds(0, 0, width, height);
gifFromAfd.setCallback(callback);
```

And in my custom view I'm overriding the `verifyDrawable` method like this:

```
@Override
protected boolean verifyDrawable(@NonNull Drawable who) { //by setting a breakpoint I sawthat  this method never gets called
    if (who instanceof GifDrawable) {
        return true;
    }
    return super.verifyDrawable(who);
}
```

Also, calling `start()`, `reset()`, isn't helping, but  `gifFromAfd.isPlaying()` returns `true`

**Comment by koral--** [comment]
Could you post `onDraw()` method of your custom View?

**Comment by iAlex97** [comment]
Here it is:

`@Override
    protected void onDraw(Canvas canvas) {
        if(height == 0 || width == 0) {
            initDimensions(canvas);
        }

        //do the drawing of the current frame
        super.onDraw(canvas) //shouldn't this draw the "background"
        canvas.drawArc(oval, currentStartAngle, currentSweepAngle, true, mArchPaint);
        drawUserText(canvas);

        printDrawLog();
    }`

**Comment by koral--** [comment]
If as "background" you mean background in terms of Android Views then it should work even without call to super but you need to call `setBackground()`/`setBackGroundDrawable()`.
If you mean just first phase of `onDraw()` then call to super is needed but you need to extend `GifImageView` or some other library class.

If conditions above are met then it probably means that content drawn after call to super covers completely all the background. Eg. the following code works for me:
```
		GifDrawable gifFromAfd = //...

		MultiCallback callback = new MultiCallback(true);

		gifFromAfd.setBounds(0, 0, gifFromAfd.getIntrinsicWidth(), gifFromAfd.getIntrinsicHeight());
		gifFromAfd.setCallback(callback);
		final View view = new GifImageView(this) {

			private final RectF mOval = new RectF(0, 0, 20, 20);
			public Paint mArchPaint = new Paint();

			@Override
			protected void onDraw(Canvas canvas) {
				mArchPaint.setStrokeWidth(4);
				mArchPaint.setColor(Color.RED);
				super.onDraw(canvas);
				canvas.drawArc(mOval, 0, 100, true, mArchPaint);
			}

			@Override
			protected boolean verifyDrawable(@NonNull Drawable who) {
				if (who instanceof GifDrawable) {
					return true;
				}
				return super.verifyDrawable(who);
			}
		};
		view.setBackground(gifFromAfd);
		callback.addView(view);
```

**Comment by iAlex97** [comment]
It's working great now! 
Thank you!
