### ISSUE TITLE
GifTextureView - placeholder?

### ISSUE THREAD

**Issue by alexb-geronimo** [koral--/android-gif-drawable#350]
I did not find a way to add a placeholder to a GifTextureView until the gif is loaded. Is there any option to do that?

**Comment by koral--** [comment]
Currently there is no such feature available.
Some kind of workaround may be to set `GifTextureView` transparent (`setOpaque(false)` - this is set by default) and set background (in the same way as in any Android `View`). 
But background will be stretched to the entire View size and GIF cannot contain transparency.

I'm marking this issue as feature-request.

**Comment by alexb-geronimo** [comment]
Thank @koral--  I see that. I already did a workaround but I hoped that such an option.

**Comment by koral--** [comment]
Done, sample is also added to sample project: https://github.com/koral--/android-gif-drawable/blob/aa0938b51be65f71a9429bf5f9983fda76d37e34/sample/src/main/java/pl/droidsonroids/gif/sample/TexturePlaceholderFragment.java#L46-L50
