### ISSUE TITLE
GifTextureView pauses and wont resume?

### ISSUE THREAD

**Issue by jrattray13** [koral--/android-gif-drawable#356]
I cant seem to get a good experience using GifTextureView, as when i pause activity and return (using android home button etc) the GifTextureView stays paused. If I have two GifTextureView in the same activity (using same resource) 1 wont ever play? Finally in a recyclerview as soon as you let one get out the view and back in it is paused... how do you force it to start again onBind()? Any help would be greatly appreciated.

**Comment by koral--** [comment]
I guess you mean `GifImageView` (not `GifTextureView`) because it uses drawables.
If you want to use single `Drawable` with multiple `View`s you need to use custom callback. There is one shipped with library called `MultiCallback`.
There is an example in readme: https://github.com/koral--/android-gif-drawable#associating-single-gifdrawable-instance-with-multiple-views
Does it answer your issue?

**Comment by jrattray13** [comment]
No i'm using:

gifTextureView.setInputSource(new InputSource.ResourcesSource(holder.itemView.getResources(), R.drawable.cat));

am i supposed to be doing something else?

**Comment by koral--** [comment]
OK, your source setting looks good. I have never tried using `TextureView` inside `RecyclerView` i need to investigate that case.

**Comment by koral--** [comment]
It seems that [`TextureView`](https://developer.android.com/reference/android/view/TextureView.html) which is base class of `GifTextureView` is not designed to work inside `RecyclerView`. When child view is scrolled away from visible space surface is abandoned and no callback from [`SurfaceTextureListener`](https://developer.android.com/reference/android/view/TextureView.SurfaceTextureListener.html) is invoked. After that it becomes unusable.
[There](https://groups.google.com/forum/#!topic/android-developers/zkdnM0G225I) is some info about `SurfaceView` but it is very similar to `TextureView`.

Here are example solutions for your issue:

1. call [`setIsRecyclable(true)`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ViewHolder.html#setIsRecyclable(boolean)) on your view holder containing `GifTextureView`. However recycling (main feature of `RecyclerView`) will be disabled for those holders.

2. Use `GifImageView` as described in README (linked in my previous post).

**Comment by jrattray13** [comment]
Yeah i'm happily using GifImageView now :) great job thanks for swift communication anyway.
