### ISSUE TITLE
Android 2.3.6 doesn't work. 

### ISSUE THREAD

**Issue by Revenge94** [koral--/android-gif-drawable#359]
When I run my app on android 2.3.6, it doesn't work and cause crash app. How I can solve this?

**Version :  1.2.2**

**Activity.java**
```
final GifImageView splashGif = (GifImageView)findViewById(R.id.splashGif);
splashGif.animate();

```
**layout.xml**
```
<pl.droidsonroids.gif.GifImageView
        android:id="@+id/splashGif"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:largeHeap="true"
        android:src="@raw/intro"
        android:visibility="gone" />
```

**Comment by koral--** [comment]
`ImageView#animate()` is available sicne API 12 (Android 3.0). It is not for GIF animation but for View propery animations.
You should remove this line:
`splashGif.animate();`
