### ISSUE TITLE
Infinite Repeat Gifs memory increase and "Too many open files"

### ISSUE THREAD

**Issue by mdev2048** [koral--/android-gif-drawable#362]
I've loaded GifImageButtons with GifDrawables into viewHolders via a custom RecycleAdapter. There's about 60 gifs, each between 200kb to 450kb being loaded from drawable resources. When the user is scrolled over the gifs, the memory rises steadily at around 10kb per section. Eventually, after scrolling back and forth about 8 times, I get a flood of the following error.

E/Parcel: dup() failed in Parcel::read, i is 0, fds[i] is -1, fd_count is 1, error: Too many open files

I call recycle on the drawable in the "onViewRecycled" call with the following. ((GifDrawable)viewHolder.centerGifButton.getDrawable()).recycle();

Has anyone else noticed this behavior?

**Comment by koral--** [comment]
There was an issue about `Too many open files`: #340. `GifDrawable` closes its file descriptor in `#recycle()` which is called also from finalizer.
If you are recycling `GifDrawable`s in `onViewRecycled` I assume that they are created somewhere from `onBindViewHolder()`, right? 
If limit of open file descriptors is exceeded and input source requires file descriptor `GifDrawable` constructor throws an exception. Is it happening in your case when `Too many open files` error is printed?

**Comment by mdev2048** [comment]
I preloaded all of the GifDrawables when initializing the adapter array (Each row has two GifDrawables). 

I'm not seeing an exception in the output when "Too many open files" is flooding but the Gifs on screen either starting tearing (white lines render over the gif) or simply don't appear at all.

**Comment by koral--** [comment]
> I preloaded all of the GifDrawables
Number of file descriptors opened at the same time is limited (on Android usually to 1024 per process). There are many classes using them eg. `GifDrawable` (created from file, resource or asset), `FileInputStream`, `AssetFileDescriptor` etc.
If you reach that limit then `Too many open files` errors will occur.

You have to either reduce number of objects using file descriptors at the same time (not necessarily `GifDrawable`s) or increase the limit (this won't help if there are descriptor leaks).
I see no library bug here.

**Comment by koral--** [comment]
I'll close this issue since there is no bug in library found. However new comments may still be added.
