### ISSUE TITLE
can't get gifDrawable to loop!

### ISSUE THREAD

**Issue by samTrent** [koral--/android-gif-drawable#363]
I know that this has been asked a billion times, but I have literally tried everything. I've tried every method I can think of to get this gif to loop but it doesn't work. 

Here's my code.

***** Inside my activity *****

 // creating our "gif" object
    GifDrawable gifAnim;

protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_workout_display);

        // check to see if the gif file exsists...
        try {

            //if successful, create the gif object with the gif file as a param
            gifAnim = new GifDrawable(getResources(), R.drawable.hammercurl)
            gifAnim.setLoopCount(0);  // tried setting the loopcount to 0.

        }
        catch (IOException e)
        {
            Log.e("make gif", "onCreate: could not generate gif", e);

            e.printStackTrace();
        }

        // tried using a listener, doesn't work
        gifAnim.addAnimationListener(new AnimationListener()
        {
            @Override
            public void onAnimationCompleted(int loopNumber) {
                gifAnim.setLoopCount(0);
                gifAnim.reset();
                Log.d("ayyy", "onAnimationCompleted: IN anin");
            }

        });

    }

What am I doing wrong???

**Comment by koral--** [comment]
`GifDrawable#setLoopCount(0)` sets loop count to inifinity.
Looping requires valid frames. If some malformed frame is detected then all further action are stopped.
Could you attach/link that GIF file here?

**Comment by samTrent** [comment]
Ya here's the Gif file that I'm trying to use. Thanks for getting back to me btw. @koral-- 
![hammercurl](https://cloud.githubusercontent.com/assets/22596215/20508152/c41379ae-b01c-11e6-9d12-45edcf8afc0c.gif)

**Comment by koral--** [comment]
OK I'll check that.

**Comment by koral--** [comment]
Setting loop count to 0 works for me. Here is modified sample project with that gif: https://github.com/koral--/android-gif-drawable/tree/example_%23363

In code which you have pasted you are not using `gifAnim` in any `View` if that's all the code it seems that you are watching some other drawable, not that one.
