### ISSUE TITLE
Cannot download it by gradle

### ISSUE THREAD

**Issue by LinLshare** [koral--/android-gif-drawable#365]
I have to change the command to 
`compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.3@aar`
and it work !

**Comment by koral--** [comment]
For this particular dependency notations with or without `@aar` suffix should be equivalent. If the latter does not work it seems to be caused by local gradle issue or internet connection problem.

**Comment by LinLshare** [comment]
Yes, I found a Easter egg :blush:
https://repo.jfrog.org/artifactory/libs-release-bintray/pl/droidsonroids/gif/android-gif-drawable/1.2.3/

![easter-eggs](https://cloud.githubusercontent.com/assets/11910355/21055687/7ac06ca8-be6d-11e6-994b-7658346fa170.jpg)
