### ISSUE TITLE
Animation is stopped after a second

### ISSUE THREAD

**Issue by moeintav** [koral--/android-gif-drawable#370]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        GifImageView gifImageView =(GifImageView) findViewById(R.id.gif);
        try {
            GifDrawable gifDrawable = new GifDrawable(getResources(), R.drawable.day);
            gifImageView.setImageDrawable(gifDrawable);

        } catch (Resources.NotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

**Comment by koral--** [comment]
It seems that GIF file has finite loop count. You can override that by calling `gifDrawable.setLoopCount(0);`.
If it is not a case please attach affected GIF file.

**Comment by moeintav** [comment]
Thankyou very much it is working perfectly.
