### ISSUE TITLE
black or white lines flashing in listview

### ISSUE THREAD

**Issue by 835127729** [koral--/android-gif-drawable#372]
I use gif-drawable in my listview,when there are more than two gif image, something look like black or white lines flash.And this problem becomes more seriously when more gif been added.

I make a gif to show this problem.
![gifddd](https://cloud.githubusercontent.com/assets/5118609/21744026/32f9eaf0-d549-11e6-94fd-527492290e33.gif)

**Comment by koral--** [comment]
It looks like the same issue as described here: https://github.com/koral--/android-gif-drawable/issues/162#issuecomment-99172799
Are there `Cannot generate texture from bitmap` logcat messages when flashing occurs?

**Comment by 835127729** [comment]
I didn't see the log you metion,but with some errors,like
` E/ThermalEngine: Failed to set desired CPU[1] frequency limit to 1190400
E/ThermalEngine: Failed to set desired CPU[2] frequency limit to 1190400`

I have seen the issue #162 ,but I still can't understand what happened.

hope for your help.

**Comment by koral--** [comment]
Issue #162 revealed that [Canvas](https://developer.android.com/reference/android/graphics/Canvas.html) (which is the only way to display content on regular Android Views) doesn't work well with large bitmaps and frequent updates. It seems that canvas has not been designed to support such use cases.
There is no known solution supporting all Drawable features.

To just display animation with basic control, classes other than `GifDrawable` eg. `GifTexImage2D` or `GifTextureView` can be used - they don't use Canvas.

`ThermalEngine` seems to be unrelated to graphics. If there is no messages related to textures it may be  different issue. Could you share those blinking GIFs? Ideally in minimal project which reproduces this issue.

**Comment by 835127729** [comment]
I use GfTextureView and it works fine.But I still hope to use imageview because I don't want to use different weight in listview item.
Thanks a lot.
