### ISSUE TITLE
How to load GIF from URI?

### ISSUE THREAD

**Issue by searchy2** [koral--/android-gif-drawable#373]
@koral-- You hinted this was possible from a comment in one of the previous issues. Unfortunately, there is no documentation for loading a GIF from a URI. Can you please tell me what the correct syntax is? Thank you!

**Comment by searchy2** [comment]
PR #374

**Comment by koral--** [comment]
Indeed there was no example in README.
Note: It is android.net.[Uri](https://developer.android.com/reference/android/net/Uri.html), not to be confused with java.net.[URI](https://developer.android.com/reference/java/net/URI.html)

PR merged with small addition.
Thanks.

**Comment by searchy2** [comment]
Thank you for the great library!
