### ISSUE TITLE
How to load the Gif  for network ?

### ISSUE THREAD

**Issue by 15189611** [koral--/android-gif-drawable#375]
How to load the Gif  for network ? 

Thanks

**Comment by 15189611** [comment]
Please help answer

**Comment by koral--** [comment]
You have to convert a URL to GIF to one of supported input sources. Some examples:
https://github.com/koral--/android-gif-drawable/issues/278#issuecomment-212223617
https://github.com/koral--/android-gif-drawable/blob/master/android-gif-drawable/src/androidTest/java/pl/droidsonroids/gif/InputStreamTest.java#L33-L35
https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/GifLoadTask.java + https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.java
The last one is located in sample project in this repo.

**Comment by kraghu** [comment]
none of the links work

**Comment by koral--** [comment]
Link from p. 2. works.
In p. 3. they are indeed outdated. I've just updated them.
