### ISSUE TITLE
Combine multiple gif's?

### ISSUE THREAD

**Issue by bbergshaven** [koral--/android-gif-drawable#376]
Hello.
Thanks for a great library!

I have a question regarding how to combine multiple gif's. I have approx. 20 gif's that I combine in different variations in different fragments. Could you recommend a way to do this? I manage to combine two gif's, but the problem arises when 3 or more needs to be combined.

        GifImageView gifImageView = (GifImageView)view.findViewById(R.id.globe);
        gifImageView.setImageResource(R.drawable.globe_loading_loop);
        GifDrawable globe = (GifDrawable) gifImageView.getDrawable();
        
        globe.addAnimationListener(new AnimationListener() {
            @Override
            public void onAnimationCompleted(int loopNumber) {
                // set next gif to be shown...
                gifImageView.setImageResource(R.drawable.globe_flag_start);
            }
        });

**Comment by koral--** [comment]
It seems that it can be done using [DrawableContainer](https://developer.android.com/reference/android/graphics/drawable/DrawableContainer.html).
Particular drawables can be added to [DrawableContainerState](https://developer.android.com/reference/android/graphics/drawable/DrawableContainer.DrawableContainerState.html) in appropriate order. Each one (from given container) can have the same animation listener which changes current drawable index. This can be encapsulated in custom `DrawableContainer` subclass, it can be associated with `ImageView` since it is also a `Drawable`.

**Comment by bbergshaven** [comment]
Thank you so much for the reply. I've been poking around the suggestions you made, but been unable to put it together. Would you mind posting an easy example / pseudo-code for this?
I also see this comment in the DrawableContainerState : "A ConstantState that can contain several Drawables. This class was made public to enable testing, and its visibility may change in a future release."

Reagards
Bernt-Johan

**Comment by koral--** [comment]
OK, I'll try to prepare some example.

**Comment by koral--** [comment]
I've managed to make it working without `DrawableContainerState`, look at the commit linked above.
Some important notes:
You may want to override more `Drawable` methods and propagate calls to child drawables. Eg. `#setVisible()`.
Current child drawable has to have callback set for animation to work, so `setAnimationEnabled()` in example above must me called *after* container has its callback set. If views displaying that drawable chain are changed at runtime (eg. they are inside `RecyclerView` or so) you have to refresh callback of current child.
When callback is removed from container, it is not reflected in children. You have to do it manually if needed.

**Comment by csmuthukuda** [comment]
hello @koral-- ,I am trying to implement the same behavior to a list of gifs to play one after another as a sequence video.I have used the above code but for some reason the animation getting stuck after few frames in first child .After doing some logging and debugging i have found out that the pro gramme is not going forward after draw method. any help appreciate..

**Comment by koral--** [comment]
OK, I'll respond in https://github.com/koral--/android-gif-drawable/issues/477 thread ASAP.
