### ISSUE TITLE
How do I get GIF to play only once

### ISSUE THREAD

**Issue by 15189611** [koral--/android-gif-drawable#377]
Gif time length is 300，
How do I get GIF to play only once。

**Comment by 15189611** [comment]
@koral--

**Comment by koral--** [comment]
Just [set loop count](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.4/pl/droidsonroids/gif/GifDrawable.html#setLoopCount-int-) to 1.

**Comment by japharr** [comment]
`<pl.droidsonroids.gif.GifImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:src="@drawable/src_anim"
    android:background="@drawable/bg_anim"
    app:loopCount="1"
    />`

**Comment by japharr** [comment]
```
<pl.droidsonroids.gif.GifImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:src="@drawable/src_anim"
    android:background="@drawable/bg_anim"
    />
```
