### ISSUE TITLE
How to listen to the GIF animation player finished ？

### ISSUE THREAD

**Issue by 15189611** [koral--/android-gif-drawable#378]
@koral-- 
How to listen to the GIF animation player finished ？
thanks

**Comment by koral--** [comment]
Add an [AnimationListener](http://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.4/pl/droidsonroids/gif/GifDrawable.html#addAnimationListener-pl.droidsonroids.gif.AnimationListener-).
