### ISSUE TITLE
there is a crash...

### ISSUE THREAD

**Issue by hpuhsp** [koral--/android-gif-drawable#379]
Caused by:
java.lang.IllegalStateException:Library libpl_droidsonroids_gif.so for supported ABIs not found in APK file

Phone:ZTE N909
Android OS 4.1.2
1GB

the cpu of phone is A5 architecture，but...
To meet the many libraries compatible and reduce the size of my Apk,i use blew
 ndk {
            abiFilters "armeabi" 
        }

How can I solve this problem？

**Comment by koral--** [comment]
I need to fix this case in library.

In the meantime workaround seems to be create an ABI splits, one for armeabi and second for armeabi-v7a. Another option  is to change abi filter to armeabi-v7a.

**Comment by koral--** [comment]
Fix available in version `1.2.5-SNAPSHOT`.
Thanks for the report.
