### ISSUE TITLE
Please review the License

### ISSUE THREAD

**Issue by EzequielAdrianM** [koral--/android-gif-drawable#380]
Hi, I was going to include the MIT license of this project when I realised something strange.
In the last line of your LICENSE file, I cannot see which type of license it has:
 
    memset32_neon.S:
    Copyright (c) 2009,2010, Code Aurora Forum. All rights reserved.

Could you please tell me? Or maybe clarify the File. Sorry, copyright matters for me. Thanks!

**Comment by koral--** [comment]
Indeed license type for that file it is missing in `LICENSE`, but it is located in that [file itself](https://github.com/koral--/android-gif-drawable/blob/master/android-gif-drawable/src/main/c/memset32_neon.S).
So it is BSD-style license and here is full text: https://github.com/koral--/android-gif-drawable/blob/master/LICENSE#L22.

I've added some clarifications in commit linked above. I hope that it is clear now.
