### ISSUE TITLE
Crash , happens reraly

### ISSUE THREAD

**Issue by EugineKidoz** [koral--/android-gif-drawable#385]
xception java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@1e298a42
android.graphics.Canvas.throwIfCannotDraw (Canvas.java:1225)
android.view.GLES20Canvas.drawBitmap (GLES20Canvas.java:600)
pl.droidsonroids.gif.GifDrawable.draw (GifDrawable.java:733)
android.widget.ImageView.onDraw (ImageView.java:1169)
android.view.View.draw (View.java:16186)
android.view.View.updateDisplayListIfDirty (View.java:15109)
android.view.View.getDisplayList (View.java:15132)
android.view.View.draw (View.java:15907)
android.view.ViewGroup.drawChild (ViewGroup.java:3703)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3497)
android.view.View.updateDisplayListIfDirty (View.java:15104)
android.view.View.getDisplayList (View.java:15132)
android.view.View.draw (View.java:15907)
android.view.ViewGroup.drawChild (ViewGroup.java:3703)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3497)
android.view.View.updateDisplayListIfDirty (View.java:15104)
android.view.View.getDisplayList (View.java:15132)
android.view.View.draw (View.java:15907)
android.view.ViewGroup.drawChild (ViewGroup.java:3703)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3497)
android.view.View.draw (View.java:16189)
android.view.View.updateDisplayListIfDirty (View.java:15109)
android.view.View.getDisplayList (View.java:15132)
android.view.View.draw (View.java:15907)
android.view.ViewGroup.drawChild (ViewGroup.java:3703)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3497)
android.view.View.updateDisplayListIfDirty (View.java:15104)
android.view.View.getDisplayList (View.java:15132)
android.view.View.draw (View.java:15907)
android.view.ViewGroup.drawChild (ViewGroup.java:3703)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3497)
android.view.View.updateDisplayListIfDirty (View.java:15104)
android.view.View.getDisplayList (View.java:15132)
android.view.View.draw (View.java:15907)
android.view.ViewGroup.drawChild (ViewGroup.java:3703)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3497)
android.view.View.draw (View.java:16189)
android.widget.FrameLayout.draw (FrameLayout.java:592)
com.android.internal.policy.impl.PhoneWindow$DecorView.draw (PhoneWindow.java:2923)
android.view.View.updateDisplayListIfDirty (View.java:15109)
android.view.View.getDisplayList (View.java:15132)
android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:275)
android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:281)
android.view.ThreadedRenderer.draw (ThreadedRenderer.java:320)
android.view.ViewRootImpl.draw (ViewRootImpl.java:2751)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2584)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2176)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1191)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6642)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:777)
android.view.Choreographer.doCallbacks (Choreographer.java:590)
android.view.Choreographer.doFrame (Choreographer.java:560)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:763)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:5938)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)

**Comment by koral--** [comment]
It seems that you are calling `Bitmap#recycle()` somewhere in your code. See https://github.com/koral--/android-gif-drawable/issues/316#issuecomment-231595088.
