### ISSUE TITLE
Animation listener to get current frame in order to stop animation at a given frame

### ISSUE THREAD

**Issue by allemattio** [koral--/android-gif-drawable#386]
Hi.
I need to stop my gif at a given frame.
Wouldn't it be nice to have an animation listener which give the information about the current frame?

Or at least It would be nice to have a method like _stopAtFrame(int frame)_ or _animateToFrame(int frame)_

**Comment by koral--** [comment]
In case of `GifDrawable` you can already achieve both features by subclassing and comparing current frame index in `draw()`.
Here is an example of `stopAtFrame(int frameIndex)`: https://github.com/koral--/android-gif-drawable/commit/de32ca263baafa125eb7129fa8f66ad08eeecc99

**Comment by koral--** [comment]
I'm closing this issue since those features can be easily added without changes in library.
