### ISSUE TITLE
different compile options cause different behavior in TextureView

### ISSUE THREAD

**Issue by JNYoung** [koral--/android-gif-drawable#389]
As I used GifTextureView in the ListView and found that may not work for some kinds of phones in release. It stops on the first frame.
After changed to the debug config it works fine, so I suspect the build config cause this problem.

And here is the CPU message for the unworking phone

Processor	: ARMv7 Processor rev 5 (v7l)
processor	: 0
BogoMIPS	: 12.80

processor	: 1
BogoMIPS	: 12.80

processor	: 2
BogoMIPS	: 12.80

processor	: 3
BogoMIPS	: 12.80

processor	: 4
BogoMIPS	: 38.40

processor	: 5
BogoMIPS	: 38.40

processor	: 6
BogoMIPS	: 38.40

processor	: 7
BogoMIPS	: 38.40

Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0 & 0x3
CPU part	: 0xc07 & 0xc0f
CPU revision	: 5 & 3

Hardware	: Kirin920
Revision	: 0000
Serial		: 0000000000000000

**Comment by koral--** [comment]
What is the API level (Android version) of that affected device?
Are you using proguard (`minifyEnabled true`) in release build?
If so what is your default proguard file (''proguard-android-optimize.txt'` or `'proguard-android.txt'`)?

**Comment by JNYoung** [comment]
the api level of device is 4.4 
the minifyEnabled is false

p.s: after changed Os to O0, it works fine
so I think is the c compiler problem

and which part may be affected by the option

**Comment by koral--** [comment]
OK, I'll try to reproduce it.

**Comment by koral--** [comment]
Indeed, even `-O1` causes this issue. I'll try to figure out ASAP what option exactly what exact option is the reason.

**Comment by koral--** [comment]
Optimization flags work in cmake build system. Commit with changes linked above.

**Comment by JNYoung** [comment]
thx， I'll try it

**Comment by koral--** [comment]
All ndk-build stuff has been ported to cmake in 34d4e76208eb94fd7f723634f48c836322ec1399
