### ISSUE TITLE
 BufferQueue has been abandoned!

### ISSUE THREAD

**Issue by vannt1991** [koral--/android-gif-drawable#392]
Error when re-call **setInputSource(@Nullable InputSource inputSource)** in GifTextureView

Step:
Down load image from url and call 
`GifTextureView.setInputSource(new InputSource.DirectByteBufferSource(buffer));` using the same with sample: **HttpFragment** 
After gif display and animate. i try to get another image from url and re call 
`GifTextureView.setInputSource(new InputSource.DirectByteBufferSource(buffer));` 
Gif image pause animate and Logcat throw many logs error:  **BufferQueue has been abandoned!**

i run on Samsumg S5 android version 7.1. Please help me check it, thanks!!!

**Comment by koral--** [comment]
Does it cause any issue apart from log messages?

**Comment by vannt1991** [comment]
i shared my code and leak found.
Please help me check it. Thanks
[https://drive.google.com/file/d/0B5pv5QKxAv59RjlMYUZPWmdDcUU/view?usp=sharing](url)

**Comment by koral--** [comment]
OK, I'll check that.

**Comment by koral--** [comment]
I was able to reproduce the bug and will fix it ASAP.
To be clear: `BufferQueue has been abandoned!` message in LogCat is not a library bug. It is just printed if a consumer is detached before a producer.
Animation stopping and resulting leak is a bug and will be fixed.

**Comment by koral--** [comment]
Fixed, in the `1.2.7-SNAPSHOT`, will be released soon.

**Comment by vannt1991** [comment]
Thanks for hard work (y)
