### ISSUE TITLE
Loading some GIF very slowly

### ISSUE THREAD

**Issue by Freshman111** [koral--/android-gif-drawable#394]
Hello I use android-gif-drawable in my project,it is really a very good library for display gif.But today I found it loading a GIF picture very slowly,almost 17 seconds long.Is the following GIF
![d2be762bba79abed3f2f26fc56a1a22a](https://cloud.githubusercontent.com/assets/9150631/24146559/24febe74-0e71-11e7-8a95-b581e0385d5f.gif)

**Comment by koral--** [comment]
OK, I'll check it ASAP.

**Comment by koral--** [comment]
Sorry about my slowness.
I was able to reproduce that bug. GIF is malformed but should not affect loading time so drastically.
I set deadline for this bug.

**Comment by Freshman111** [comment]
@koral-- Thank you very much.

**Comment by koral--** [comment]
Fix is available in `1.2.7-SNAPSHOT`.
