### ISSUE TITLE
https://github.com/koral--/android-gif-drawable/labels/bug

### ISSUE THREAD

**Issue by mitch081214** [koral--/android-gif-drawable#409]

**Comment by mitch081214** [comment]
https://github.com/koral--/android-gif-drawable/labels/bug" what's this"

**Comment by mitch081214** [comment]
What's thi

**Comment by koral--** [comment]
It is just a label for informational purposes. You can see it next to issue title and search for issues with that label.
I assign this label to issues which are bugs and need to be fixed immediately.
