### ISSUE TITLE
Pseudo-gif with a series of PNGs?

### ISSUE THREAD

**Issue by autonomousapps** [koral--/android-gif-drawable#411]
Sorry if this is the wrong place to ask this, but I really like how simple your library is to use and would like to use it, but I don't want to actually use gifs, as their color space is too small and they don't support transparency very well. I'd like to do something like specifying a series of pngs and then have them animated as if they were a gif. Is that possible?

**Comment by koral--** [comment]
It is totally possible.
I assume that you have a lot of PNGs (and/or they have huge sizes) and loading entire files to bitmaps is impossible.
If all the PNGs are equal-sized and use the same color depth it should be possible to use [BitmapFactory.Options#inBitmap](https://developer.android.com/reference/android/graphics/BitmapFactory.Options.html#inBitmap) and use it with custom animated drawable, everything in pure Java/Kotlin (without using native libraries).

It should be also possible to use code from this library namely, replace GIF decoding part with PNG equivalent (using libpng for example). However, it is tightly coupled with GIFs so it will require a significant amount of work.

**Comment by autonomousapps** [comment]
Thank you!
