### ISSUE TITLE
About gif sticker

### ISSUE THREAD

**Issue by Hellozhongxin** [koral--/android-gif-drawable#412]
Hello, I have to add some gif sticker on the video, and gif should be scaled or rotated。
I have used FFmpeg add gif on the video.But I do not know how to scale or roate gif.Can you help me ?Thans a lot!

**Comment by koral--** [comment]
For drawable you can apply [rotation](https://developer.android.com/reference/android/graphics/Canvas.html#rotate(float, float, float)) and [scaling](Canvas:https://developer.android.com/reference/android/graphics/Canvas.html#scale(float, float, float, float)) to [Canvas](https://developer.android.com/reference/android/graphics/Canvas.html). Subclass `GifDrawable` and override `draw()` method.

**Comment by Hellozhongxin** [comment]
How can I get the scaled and rotated result?Can I save it on the SDCARD?
When I want to add a picture or some text on the video,I could use ViewGroup.draw() to get the bitmap that has Viewgroup's Width and Height , and conver it to PNG on the SDCARD.then I adjust the size of PNG so that I can control  relative position. of picture or text,and add it on the video by useing FFmepg overlay option .
But I confused when  add some Gif. Please Help!Thanks a lot!

**Comment by koral--** [comment]
To get the final result you can use [drawing cache](https://developer.android.com/reference/android/view/View.html#getDrawingCache(boolean)). Cache has to be enabled.

Another option is to use OpenGL and `GifTexImage2D`. You can set rotation and scale on a matrix [like here](https://github.com/koral--/android-gif-drawable-sample/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/GifTexImage2DFragment.java#L151) and then use `glReadPixels` to get a result.
