### ISSUE TITLE
Sample for usage of seekToFrameGL

### ISSUE THREAD

**Issue by moshoujingli** [koral--/android-gif-drawable#413]
I think the method seekToFrameGL is used to let the frame seek to the specified index. But while I call this ,it just jump to the start of the gif and play.Would you like to offer a sample to help me find out the right way to use this method?

**Comment by koral--** [comment]
It seems that you have called `GifTexImage2D#startDecoderThread()` before, right?
In general, there are two modes in `GifTexImage2D`: you can either call `startDecoderThread()` and frames will be changed according to the timing information in GIF file or you may call `seekToFrameGL()` to extract particular frames with a particular timing.

If `seekToFrameGL()` is called when decoder thread is running then just sought frame can be changed immediately.

It is not well documented though. I'll mention this case in a documentation. Perhaps in `GifTexImage2D` Javadoc.

**Comment by moshoujingli** [comment]
Thank you for your help！

**Comment by koral--** [comment]
javadoc fixed
