### ISSUE TITLE
can we use android-gif-drawable load a picture from network?

### ISSUE THREAD

**Issue by Hellozhongxin** [koral--/android-gif-drawable#416]
how to set a url into android-gif-drawable?

**Comment by koral--** [comment]
Look at the sample project:
https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/GifLoadTask.java
and 
https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.java
