### ISSUE TITLE
A most GIF is not looping, put a live broadcast

### ISSUE THREAD

**Issue by junyao-yu** [koral--/android-gif-drawable#417]
<pl.droidsonroids.gif.GifImageView
        android:id="@+id/image1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/migration" />

gifDrawable1 = (GifDrawable) image1.getDrawable();
        if (!gifDrawable1.isPlaying()) {
            gifDrawable1.start();
        }

But a lot can only play a GIF，why?

**Comment by koral--** [comment]
It seems that that GIFs has loop count set to 1. You can call `gifDrawable1.setLoopCount(0)` to change it to infinity.
