### ISSUE TITLE
How to use getCurrentPosition()

### ISSUE THREAD

**Issue by CeJienAJPC** [koral--/android-gif-drawable#418]
Maybe a basic question. Hence bear with me. I want to display the elapsed time in TextView. Where should I use `getCurrentPosition()` to get the elapsed time? I mean this should be placed inside a listener right?

Also what is the difference between `isPlaying()` and `isRunning()`

Thanks

**Comment by koral--** [comment]
> Where should I use `getCurrentPosition()` to get the elapsed time? 

It is up to you. Currently, there is no explicit listener which fires on every frame change built-in into the library. However, you can use for example [Drawable.Callback](https://developer.android.com/reference/android/graphics/drawable/Drawable.Callback.html) optionally with [MultiCallback](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.7/pl/droidsonroids/gif/MultiCallback.html).

There is no difference. `isPlaying()` is an implementation method of [MediaController.MediaPlayerControl](https://developer.android.com/reference/android/widget/MediaController.MediaPlayerControl.html) while `isRunning()` is from [Animatable](https://developer.android.com/reference/android/graphics/drawable/Animatable.html).
