### ISSUE TITLE
the animation splash screen

### ISSUE THREAD

**Issue by junyao-yu** [koral--/android-gif-drawable#419]
Part of the mobile phone, the animation splash screen every few seconds，w h y?

**Comment by koral--** [comment]
Could you attach affected GIF file?

**Comment by junyao-yu** [comment]
http://docs.ylb.net/Public/images/loading_gif.gif   
This is just a GIf address, my side all GIf play is the problem?

**Comment by koral--** [comment]
Are effects similar to described in #267? Namely parts of 2 adjacent frames are visible at the same time?

**Comment by junyao-yu** [comment]
没有效果，播放的动画还是一跳一跳的，这是代码的问题还是Gif的问题呢？

**Comment by junyao-yu** [comment]
The animation to play doesn't work, or a jump jump, this is the problem that the code or Gif?

**Comment by junyao-yu** [comment]
I turn off the hardware acceleration, as if the problem settled, but can you tell me how to return a responsibility?

**Comment by koral--** [comment]
> I turn off the hardware acceleration, as if the problem settled, but can you tell me how to return a responsibility?

Sorry, I don't understand. Do you mean that it helps when hardware acceleration is turned off?

**Comment by junyao-yu** [comment]
Yes, close the hardware acceleration solved the problem, but I don't know why is this.

**Comment by koral--** [comment]
It seems that here is the explanation: https://github.com/koral--/android-gif-drawable/issues/162#issuecomment-99172799
Solution is not use drawables but `GifTextureView` or `GifTexImage2D`.
