### ISSUE TITLE
In view of the question 419

### ISSUE THREAD

**Issue by junyao-yu** [koral--/android-gif-drawable#423]
After I close the hardware acceleration, the animation not flash, but will be displayed on most mobile phone slowly slowly, I really don't know how to solve

**Comment by koral--** [comment]
As I said in #419 and linked #162, the only solution (known at the time of writing) is to use `GifTextureView` or `GifTexImage2D` (inside `GLSurfaceView`). 
Regular `View`s, using `Canvas` introduce artifacts with fast animations.
