### ISSUE TITLE
call GifTextureView.setInputSource() will stuck when it's playing

### ISSUE THREAD

**Issue by jalonray** [koral--/android-gif-drawable#429]
The code following:
`
new Handler().postDelayed(new Runnable() {
                @Override
                public void run() {
                    gifTextureView.setInputSource(new InputSource.AssetSource(getResources().getAssets(), "Animated-Flag-Greece.gif"));
                }
            }, 5_000L);
`
will cause the stuck -,-

**Comment by koral--** [comment]
I'll check that.

**Comment by koral--** [comment]
Fixed in `1.2.8-SNAPSHOT`. Thanks for the report.
