### ISSUE TITLE
Loading gif from URL

### ISSUE THREAD

**Issue by gabrieltintarescu** [koral--/android-gif-drawable#439]
Is it possible to load a gif from an url? ex: www.mysite.com/mygif.gif

**Comment by koral--** [comment]
Yes, there is an example in sample project:
https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.java
https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/GifLoadTask.java
