### ISSUE TITLE
Showing white edges on transparent gif

### ISSUE THREAD

**Issue by immujeeb** [koral--/android-gif-drawable#446]
Hi,

Why it's showing edges around the image? Please check the attachment.
I used this script

        <pl.droidsonroids.gif.GifImageView
            android:id="@+id/centerbtn"
            android:layout_centerHorizontal="true"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@drawable/logo_animated"
            />

![image](https://user-images.githubusercontent.com/5656189/29448815-ce3fdd68-8411-11e7-8112-8d66a92387a2.png)

**Comment by koral--** [comment]
Could you attach original GIF file (logo_animated)?

**Comment by immujeeb** [comment]
Thanks for the reply koral. 
Please check the attachment.

Thanks,
Mujeeb.

![logo_animated](https://user-images.githubusercontent.com/5656189/29452020-46723914-841e-11e7-8d1c-aff8670ccd3d.gif)

**Comment by koral--** [comment]
OK, I'll check that.

**Comment by koral--** [comment]
Sorry for the delay.
Those white edges are part of the GIF, there is no error here.
This is how that file appears on black background:
![image](https://user-images.githubusercontent.com/3340954/29754379-0f1a3198-8b84-11e7-81d3-806da1fc50e8.png)

Live demo: https://repl.it/K205
