### ISSUE TITLE
Please help, i want pause and play gif animation... programmatically

### ISSUE THREAD

**Issue by sazdahani** [koral--/android-gif-drawable#448]
hello
i want pause and play gif but i cant
i know i have to use mediacontroller but please give me a sample...
when media controller show i can by push pause button pause that, but i want do this programmatically...
i think it's impossible

**Comment by koral--** [comment]
`GifDrawable` has `pause()` and `play()` methods: https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.7/pl/droidsonroids/gif/GifDrawable.html#pause--
and here is a sample:
https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/AnimationControlFragment.kt

**Comment by sazdahani** [comment]
Hi friend,
i dont understad thats you sent me
please say simple, what i put in between this codes to i can pause
animation:
http://prntscr.com/gfiaun

**Comment by koral--** [comment]
To pause, call: `gifDrawable.pause()`.
to start: `gifDrawable.start()`

**Comment by sazdahani** [comment]
its my code please correct this:


protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.first_activity);


    int width = Resources.getSystem().getDisplayMetrics().widthPixels;

    top = (GifImageView) findViewById(R.id.giv);

    final MediaController mc = new MediaController(this);
    mc.setMediaPlayer((GifDrawable) top.getDrawable());
    mc.setAnchorView(top);

    final Button stop=(Button) findViewById(R.id.stop);
    stop.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            Toast.makeText(First.this, "stop ", Toast.LENGTH_SHORT).show();

            // ?????????

        }
    });

}

**Comment by koral--** [comment]
There should be`((GifDrawable) top.getDrawable()).stop();`

**Comment by sazdahani** [comment]
thanks dear friend,
i ow you ;)
