### ISSUE TITLE
Unable to work properly in ViewPager

### ISSUE THREAD

**Issue by 287257255** [koral--/android-gif-drawable#449]
Unable to work properly in ViewPager:
What I want to do is to execute the animation every time the page is selected, the default start position of the other,
However, in the method of onPagerSelected gets the GifDrawable for each item,
Calling GifDrawable these methods are not normal, even the interface cannot be drawn

Method:
reset
start
stop
Seek to

I even suspect that the drawable in the item is out of order

I don't know JNI. I don't know what to do

**Comment by koral--** [comment]
Could you share code which reproduces this issue?

**Comment by 287257255** [comment]
It's in the onPageChangedListener on ViewPager, in the method of onPageSelected:
forEach item gets the GifDrawable, the current position execution start, and the other execution seekto (0) and stop;
I can't provide the details until tomorrow, but that's roughly what I wrote...

**Comment by 287257255** [comment]
viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

            }

            @Override
            public void onPageSelected(int position) {
                for (int i = 0; i < viewPager.getChildCount(); i++) {
                    GifImageView child = (GifImageView) viewPager.getChildAt(position);
                    GifDrawable gifDrawable= (GifDrawable) child.getDrawable();
                    if (position==i&&!gifDrawable.isRunning()){
                        gifDrawable.start();
                    }else if (gifDrawable.isRunning()){
                        gifDrawable.seekTo(0);
                        gifDrawable.stop();
                    }
                }
            }

**Comment by koral--** [comment]
OK, I'll check that.

**Comment by 287257255** [comment]
I've determined that if you have multiple gifs on the current page, the gifdrawable will show confusion

**Comment by koral--** [comment]
If you want code like that to work you need to set appropriate offscreen page limit. See the documentation: https://developer.android.com/reference/android/support/v4/view/ViewPager.html#setOffscreenPageLimit(int)
E.g. if you have 10 pages you need to call `viewPager.setOffscreenPageLimit(9)` or more.
