### ISSUE TITLE
MediaController Not Working

### ISSUE THREAD

**Issue by johnwhitee** [koral--/android-gif-drawable#455]
Hi there,
First of all thanks for awesome library. I was not able to use commands like mGif.start(), mGif.stop().

@Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_game);
        mPlayPause = (Button) findViewById(R.id.activity_gif_playpause_button);
        mGif = (GifImageView) findViewById(R.id.activity_gif_gif);
        final MediaController mc = new MediaController(this);
        mc.setMediaPlayer((GifDrawable) mGif.getDrawable());
        mc.setAnchorView(mGif);

        mPlayPause.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mc.show();
                mGif.start(); // IT WILL SHOW ERROR and SAYS "Cannot resolve method"
            }
        });
        mGif.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mc.show();
            }
        });
    }
}
Please let me know how can I be able to use it.
Thanks!

**Comment by koral--** [comment]
Please attach complete stacktrace.
Are you using multidex?

**Comment by johnwhitee** [comment]
Umm I went through previous issues and found my answer. Thank you so much for your help!
