### ISSUE TITLE
Support set paint ANTI_ALIAS_FLAG

### ISSUE THREAD

**Issue by liufsd** [koral--/android-gif-drawable#456]
![401](https://user-images.githubusercontent.com/1910405/30432294-cd40e49c-9993-11e7-8e63-764f67fe25f1.gif)
![402](https://user-images.githubusercontent.com/1910405/30432295-cd4c37a2-9993-11e7-8845-f605f62674bc.gif)
![403](https://user-images.githubusercontent.com/1910405/30432297-cd717710-9993-11e7-9293-a26a8f8c8bc9.gif)
![404](https://user-images.githubusercontent.com/1910405/30432298-cd927280-9993-11e7-9ab9-5239159a66bd.gif)

How to show this gif ?
It will show white 'sawtooth'

**Comment by liufsd** [comment]
![image](https://user-images.githubusercontent.com/1910405/30508208-12e56ffa-9ac4-11e7-822c-3979598dbbc9.png)

**Comment by liufsd** [comment]
any solution for delete gif white round ?

**Comment by koral--** [comment]
You have to change white pixels in GIF file to transparent.
Here is how it looks on black background in HTML:
![image](https://user-images.githubusercontent.com/3340954/30511670-74ee67dc-9ade-11e7-80a4-aa8798cd34dd.png)
Live demo: https://repl.it/LLK3

**Comment by liufsd** [comment]
yes. i know that. But the emoji gif has this issue.

**Comment by koral--** [comment]
The best solution is to edit GIF file using tools like GIMP or imagemagick.
To do it in runtime you can use Transform similar to this:
```kotlin
gifDrawable.transform = object : Transform {
	val dstRect = Rect()

	override fun onBoundsChange(bounds: Rect) {
		dstRect.set(bounds)
	}

	override fun onDraw(canvas: Canvas, paint: Paint, buffer: Bitmap) {
		val centerX = dstRect.centerX().toDouble()
		val centerY = dstRect.centerY().toDouble()
		val r = dstRect.height() / 2
		val rMin = (r * 0.75).toInt()

		for (x in 1 until buffer.width - 1) {
			for (y in 1 until buffer.height - 1) {
				val d = Math.sqrt(Math.pow((x - centerX), 2.0) + Math.pow((y - centerY), 2.0)).toInt()
				val color = buffer.getPixel(x, y)
				if (d > rMin && Color.red(color) > 160 && Color.green(color) > 160 && Color.blue(color) > 160) {
					buffer.setPixel(x, y, Color.TRANSPARENT)
				}
			}
		}
		canvas.drawBitmap(buffer, null, dstRect, paint)
	}
}
```
The idea is to replace make pixel transparent if its color is similar to white (you can adjust value `160` to tune this) and it is located further than 75% of the half of height from the center (assumed that image is rectangular).

**Comment by liufsd** [comment]
wow, great~
Thanks.
