### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by VeiZhang** [koral--/android-gif-drawable#458]
I use the sugesstions:
* multiDexEnabled true 
* MultiDexApplication 
* proguard

But it still didn't work.
It was strange that it shows error happend on my xml and class, not gif view. My module also has *.so file. It shows my so file not found.
Pls tell me how to solve it?

**Comment by koral--** [comment]
Please attach complete stacktrace.

**Comment by koral--** [comment]
Closed due to inactivity, may be reopened if new info is posted.
