### ISSUE TITLE
Can not support gif from network.

### ISSUE THREAD

**Issue by babyboy18** [koral--/android-gif-drawable#459]
I have an url of gif from network. so how can i use android-gif-drawable to show the gif.

**Comment by koral--** [comment]
There is a sample project for that: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/GifLoadTask.kt
https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.kt
