### ISSUE TITLE
Glide+andoid-gif-drawable  :GIF in caton

### ISSUE THREAD

**Issue by TheMelody** [koral--/android-gif-drawable#460]
Hello I use "com.bumptech.glide" ,Glide library loading images matching your "android-gif-drawable", multiple fragments switch, fragments of list loading GIF, GIF caton, how do I solve?

**Comment by koral--** [comment]
Sorry, but I don't understand what you are saying.

**Comment by TheMelody** [comment]
# **小伙伴们技术交流请加群: 490113234**
>**## I have solved my problem！！！！**
I found a solution:[https://futurestud.io/tutorials/glide-callbacks-simpletarget-and-viewtarget-for-custom-view-classes](url)

> **public void onBindViewHolder(BaseHolder holder, int position)**
_for example_:

**//To prevent image dislocation(防止图片错位)**
 xxxIvCoverView.setImageDrawable(null);
 xxxIvCoverView.setTag(R.id.imageid,gifUrl);

**Set up ViewTarget.....**

>ViewTarget viewTarget=new ViewTarget<pl.droidsonroids.gif.GifImageView,com.bumptech.glide.load.resource.gif.GifDrawable>(xxxIvCoverView){
           @Override
            public void onResourceReady(GifDrawable resource, Transition<? super GifDrawable> 
                transition) {
           if(xxxIvCoverView.getTag(R.id.imageid)!=null&&gifUrl==xxxIvCoverView.getTag(R.id.imageid)) {
                    pl.droidsonroids.gif.GifDrawable gifFromBytes=null;
                    try {
                        gifFromBytes = new pl.droidsonroids.gif.GifDrawable(resource.getBuffer());
                        this.view.setImageDrawable(gifFromBytes);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }finally {
                        if(null==gifFromBytes){
                            this.view.setImageDrawable(resource);
                        }
                    }
                }
    }
}
>**At last**
GlideApp.with(mBaseFragment).asGif()
                    .load(gifUrl)
                    .into(viewTarget);
