### ISSUE TITLE
"Glide" How does the network image loading library work with GifDrawable?

### ISSUE THREAD

**Issue by TheMelody** [koral--/android-gif-drawable#461]
"Glide" network load library how to configure the combination of "android-gif-drawable" library.
>>>>>>
Now I use the "Glide" network to load the library, and then pass Gifdrawable the gifImageView, but the two fragment switch, at the same time, each fragment which has a list of loading gif picture, switch, the list of gif graphics display animation card pause.

**Comment by koral--** [comment]
Could you post some code snippet?

**Comment by TheMelody** [comment]
The first fragment of the adapter inside：
Two fragment of the adapter similar to the following:
**//Member variables**
private RequestBuilder<Drawable> requestBuilder;

**//Construct the method inside init Builder:**
requestBuilder = GlideApp.with(fragment)
                .asDrawable();

**//onBindViewHolder method:**
public void onBindViewHolder(BaseHolder holder, int position){
       //......
       **//itemBinding.iv169==> ImageView16_9 extends pl.droidsonroids.gif.GifImageView** 
        requestBuilder.load(gifUrl).into(itemBinding.iv169);
}

**Comment by koral--** [comment]
I still don't understand what is your issue.
Glide uses its own animated Drawables not compatible with GifDrawable.
If you want to display GIF from URL in GifDrawable you can do it like in sample: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.kt
Just create GifDrawable instead of InputSource: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.kt#L40

**Comment by TheMelody** [comment]
# **小伙伴们技术交流请加群: 490113234**
# **have solved my problem！！！！**
I found a solution:[https://futurestud.io/tutorials/glide-callbacks-simpletarget-and-viewtarget-for-custom-view-classes](url)

> **public void onBindViewHolder(BaseHolder holder, int position)**
_for example_:

**//To prevent image dislocation(防止图片错位)**
 xxxIvCoverView.setImageDrawable(null);
 xxxIvCoverView.setTag(R.id.imageid,gifUrl);

**Set up ViewTarget.....**

>ViewTarget viewTarget=new ViewTarget<pl.droidsonroids.gif.GifImageView,com.bumptech.glide.load.resource.gif.GifDrawable>(xxxIvCoverView){
           @Override
            public void onResourceReady(GifDrawable resource, Transition<? super GifDrawable> 
                transition) {
           if(xxxIvCoverView.getTag(R.id.imageid)!=null&&gifUrl==xxxIvCoverView.getTag(R.id.imageid)) {
                    pl.droidsonroids.gif.GifDrawable gifFromBytes=null;
                    try {
                        gifFromBytes = new pl.droidsonroids.gif.GifDrawable(resource.getBuffer());
                        this.view.setImageDrawable(gifFromBytes);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }finally {
                        if(null==gifFromBytes){
                            this.view.setImageDrawable(resource);
                        }
                    }
                }
    }
}
>**At last**
GlideApp.with(mBaseFragment).asGif()
                    .load(gifUrl)
                    .into(viewTarget);

**Comment by koral--** [comment]
👍
