### ISSUE TITLE
Didn't find class "pl.droidsonroids.gif.GifImageView" 

### ISSUE THREAD

**Issue by Erichkko** [koral--/android-gif-drawable#462]
Didn't find class "pl.droidsonroids.gif.GifImageView" 
on path: DexPathList[[zip file "/data/app/com.ebeitech.hlbowner-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.ebeitech.hlbowner-2, /system/lib]]

**Comment by koral--** [comment]
Looks like multidex misconfiguration, see #349

**Comment by Erichkko** [comment]
https://stackoverflow.com/questions/39834264/error-inflating-class-pl-droidsonroids-gif-gifimageview?answertab=active#tab-top

you can look this, can you help me resolve?

**Comment by koral--** [comment]
OK, let's continue on StcakOverflow.
