### ISSUE TITLE
Provide Scaling like in Bitmaps

### ISSUE THREAD

**Issue by loibi93** [koral--/android-gif-drawable#465]
Hi,

I am currently working on an Implementation of a Shoutbox where lots of gifs are loaded. I recently ran into memory issues for some users, so I decided to limit images to a maximum size. This is easy for static images since Android provides us with Bitmap.createScaledBitmap. Is it possible to do something similar with GifDrawables ? I am aware of drawable.setBounds, but that will not save memory.

**Comment by koral--** [comment]
You can set the sample size: https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.8/pl/droidsonroids/gif/GifOptions.html#setInSampleSize-int-
To use it, you can create `GifDrawable`s using [GifDrawableBuilder](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.8/pl/droidsonroids/gif/GifDrawableBuilder.html#GifDrawableBuilder--)

**Comment by loibi93** [comment]
Perfect, thank you very much :)
