### ISSUE TITLE
GIF Lagging while animating

### ISSUE THREAD

**Issue by kumarbhubnesh** [koral--/android-gif-drawable#467]
I have GIF image of 10 mb approx, when its loaded the animation is not smooth, same GIF is working fine in iOS.

**Comment by koral--** [comment]
Could you attach it here or send it via e-mail?

**Comment by kumarbhubnesh** [comment]
Please share your email Id.

**Comment by koral--** [comment]
karol.wrotniak@droidsonroids.pl
It is public in GitHub profile: https://github.com/koral--

**Comment by koral--** [comment]
Thanks, I will check that ASAP.

**Comment by kumarbhubnesh** [comment]
@koral-- Any update. thanks in advance.

**Comment by kumarbhubnesh** [comment]
Hi @koral-- , Have you found the same issue?

**Comment by koral--** [comment]
I received your e-mail but haven't checked this issue yet. Will try to do it this week.

**Comment by koral--** [comment]
For such large GIFs and framerates you can cache all the frames.
There is no out of the box solution built-in into this library however, you can implement it with few lines of code. 

Here is an example which I've just added: https://github.com/koral--/android-gif-drawable/blob/c851fda56fc15c184fead5b26d74b691088c3e56/sample/src/main/java/pl/droidsonroids/gif/sample/GifDecoderFragment.kt
