### ISSUE TITLE
Is there is any way to merge two gifs into one?

### ISSUE THREAD

**Issue by ajaystha005** [koral--/android-gif-drawable#468]
I tried using GIF decoder but it seems slow. I am looking for the efficient way

**Comment by koral--** [comment]
There is no GIF encoder in this library (there is plan for it but it is not yet ready - #292). What do you mean as encoder?

**Comment by ajaystha005** [comment]
Sorry for that. I am looking for Gif encoder where I can create a new GIF from existing two gifs.

**Comment by javaxu** [comment]
what about sending two gifs to server, then merge two gifs by ImageMagick?

发自我的 iPhone

**Comment by ajaystha005** [comment]
I need to do offline

**Comment by javaxu** [comment]
ImageMagick has IOS binary release. You can get some info here: http://www.imagemagick.org/script/download.php#iOS <http://www.imagemagick.org/script/download.php#iOS>

**Comment by koral--** [comment]
I would try FFmpeg. Here is the Android library: https://github.com/WritingMinds/ffmpeg-android-java
And concatenate documentation: https://trac.ffmpeg.org/wiki/Concatenate

**Comment by ajaystha005** [comment]
Thank you. I will try
