### ISSUE TITLE
TextView GIF drawables inside a recycler-view do not play 

### ISSUE THREAD

**Issue by jojo-majo** [koral--/android-gif-drawable#474]
I have a recycler-view with several text-views. Some of those text-views have GIF drawable-lefts.

These GIFs play when the view-holder is first bound, but after scrolling the item off the screen then scrolling it back the GIF is no longer playing.

**Comment by jojo-majo** [comment]
@koral-- Do I need to override the `freezesAnimation` thing somehow?

**Comment by koral--** [comment]
It was a bug and should be fixed in version `1.2.9-SNAPSHOT`, just uploaded to maven snapshot repo.
Thanks for the report.
