### ISSUE TITLE
Gifs in TextView and EditText with fromHtml

### ISSUE THREAD

**Issue by loibi93** [koral--/android-gif-drawable#481]
Hello,

I am currently working on a chat app which has smilies that are animated gifs. I use Html.fromHtml to set the text of a chat message. With an ImageGetter I then put the GifDrawables in there. The Gifs did not animate, but I noticed, that when I scroll in the Chat View, that they start to animate. So I did a workaround by attaching a thread to all visible textviews, that invalidates the views every 100ms. This works fine, also on older devices.

Now I am working on an update, which is incorporating the same functionality in the edittext for a new message. GifLoading and displaying works fine, but I also had the problem that the gifs are not animating. So I did the same trick with invalidating, but this time it did not work. I noticed that the gifs are animating when I type something in the edittext.

Do you have any suggestions why this could be ?

EDIT: When I use this instead of invalidate, the gifs are animated, but the cursor does not blink anymore, and if I press the caps button it is immediately set back to lower case:
getText().append(" ");
getText().replace(getText().length() - 1, getText().length(), "");

EDIT2: I now changed my Implementation to use the MultiCallback(true). The TextViews are now animating fine, but the EditText still refuses to animate. I noticed something interesting: When there is a TextView with smilie1 and smilie1 is also in the EditText it animates in both views. If it is only in the TextView it still animates fine, but when it is only in the edittext, it does not animate.

EDIT3: Ok, I figured it out myself, I found an old issue with the same problem, the solution was this:
https://github.com/koral--/SmileyDemo/commit/ad4a6aa57193905fcd2d400f7a898c981f6b467c

**Comment by koral--** [comment]
To sum up:
- Animated Drawable inside span (`Html.fromHtml` also produces spans) does not have a callback by default. Callback need to be set explicitly.
- Invalidation of selectable TextView (incl. EditText) does not work if layer type is other than software. Either layer type needs to be changed or some other workaround needs to be used e.g.:
https://github.com/koral--/android-gif-drawable/issues/234#issuecomment-163466447
