### ISSUE TITLE
Gif is not shown in layerlist

### ISSUE THREAD

**Issue by andreamorosi** [koral--/android-gif-drawable#487]
I tried to put a gif in an item of a layerlist, unfortunately gif is not displayed and the splash screen shows a black screen

`

           <layer-list xmlns:android="http://schemas.android.com/apk/res/android">
           <item>

                    <pl.droidsonroids.gif.GifImageView android:gravity="center"
                            android:layout_width="match_parent"
                            android:layout_height="match_parent"
                           android:src="@drawable/mygif"/>
            </item>
            </layer-list>

`

How can I fix it?

**Comment by astagi** [comment]
+1

**Comment by koral--** [comment]
There is no way to include custom (non-framework) drawables inside `layer-list` however, there are 2 alternatives to achieve the same result:

1. Create [LayerDrawable](https://developer.android.com/reference/android/graphics/drawable/LayerDrawable.html) from code, like this:
```kotlin
val layers = arrayOf(
	GifDrawable.createFromResource(resources, R.drawable.anim_flag_england),
	GifDrawable.createFromResource(resources, R.drawable.anim_flag_chile)
)
val layerDrawable = LayerDrawable(layers)
```

2. Subclass `LayerDrawable`, override `inflate` method and implement XML parsing. Then you will be able to replace `<layer-list>` with fully qualified class name of that drawable. This method works only on API 24 or newer and only inside your application (e.g. cannot be used as launcher icon etc.)

There is an analogous sample for `<selector>`/`StateListDrawable` in the sample project in this repo:

* https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/GifSelectorDrawable.kt
* https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/res/drawable-v24/selector.xml
