### ISSUE TITLE
请问如何循环播放gif图呢？现在播了一次就不播了

### ISSUE THREAD

**Issue by super-qc** [koral--/android-gif-drawable#493]

**Comment by koral--** [comment]
English please, we don't speak Chinese.

**Comment by super-qc** [comment]
Why gif just play once,How do I loop play the GIF?

**Comment by koral--** [comment]
That's because GIF file has loop count set to 1. You can override that by calling `GifDrawable.setLoopCount(0)` or setting `app:loopCount=0` attribute in XML.
0 means infinity.
