### ISSUE TITLE
GIF image is not animating????????? 

### ISSUE THREAD

**Issue by kawadkarrocky** [koral--/android-gif-drawable#499]
Hey Koral ,I am trying to load my URL image path in GifImageView by converting it to image bitmap but the problem is my GIF image not animating.any help would be appreciative, thanks!!!!

**Comment by koral--** [comment]
Bitmap contains only single frame. Generally you have to download/cache GIF file.
Look at the sample project to see how it can be done:
https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/HttpFragment.kt
https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/GifLoadTask.kt
