### ISSUE TITLE
Android Wear - gif animating slowly

### ISSUE THREAD

**Issue by artiomnist** [koral--/android-gif-drawable#501]
I am trying to load in a gif onto an Android Wear watchface (a class that extends `CanvasWatchFaceService.Engine`) My implementation is close to what is recommended in the android.deveoper.com guides.

I can load the gif successfuly, I'm doing that in the layout `layout/watchface.xml` and the gif appears 🎉 . However, the animation at which the gif plays is very slow... 😭  It seems to be animating every seconds tick (as in changes 1 frame per second). 

I've tried to call `setSpeed(3.0f)` but that doesn't increase the speed of the animation. 

Is this gif animation limited by the devices computational performance, or is there something obvious that I might be missing?

Any help would be much appreciated!

**Comment by koral--** [comment]
Is it reproducible on watch emulator?

**Comment by artiomnist** [comment]
Yes - it is reproducible on the watch emulator and a physical device.

**Comment by koral--** [comment]
OK, I'll check this ASAP.

**Comment by mn7676** [comment]
@koral--  The gifs are shown to me slowly on same activity

**Comment by koral--** [comment]
I could not reproduce that on emulated watch.
I've tried sample app from this repo on several AVDs with default settings and haven't noticed any performance issues.

@mn7676 @artiomnist could you post more information e.g. AVD configuration or share affected GIF files?

**Comment by artiomnist** [comment]
Some more info:

I am loading the GIF from `res/drawable/my-gif.gif` (Meaning, no network request should be being made)

**AVD:**

```
Android Wear Round Chin, 1.65 320x290 dpi.
Android 7.1.1 x86
Emulated performance: default (Graphics: automatic, Multi-Core CPU: 4)
Full network speed,
512MB RAM
32MB VM heap
```

**GIF:**

![dance_otter_dance](https://user-images.githubusercontent.com/20073559/34939613-54020fe6-f9e4-11e7-817a-a60b404c0b65.gif)

I've tried optimising the GIF, and manually removing frames, but still get a slow animated gif. 

Am I perhaps doing something wrong with the way I'm including it in my layout?

**Comment by koral--** [comment]
I'll retry to reproduce this issue.

**Comment by artiomnist** [comment]
To elaborate on this... this is the speed of the GIF on the emulator and physical device

![issue](https://user-images.githubusercontent.com/20073559/34954531-9fa2e1c6-fa18-11e7-8d59-b72d364200f7.gif):

**Comment by koral--** [comment]
Works for me in sample project from this repo:
![output](https://user-images.githubusercontent.com/3340954/35187062-4935d56e-fe1e-11e7-9316-df8fdd3cf1ad.gif)
Could you create repo with minimal reproducible sample?

**Comment by koral--** [comment]
It seems that watchface has limited refresh rate.
I'll check that ASAP.

**Comment by koral--** [comment]
That app has update rate set to 1 per second. More info added as comment: https://github.com/artiomnist/wearables-watchface-sample/commit/5d37936c17e8285cc31c3e8e3a36d965c43c077b#r27221203

**Comment by artiomnist** [comment]
Thank you so much for the help! @koral-- I'll make the changes within the `CanvasWatchFaceService` class accordingly! Awesome library, keep up the great work!
