### ISSUE TITLE
Plugin with id 'com.android.application' not found

### ISSUE THREAD

**Issue by BoomBoomBoom2017** [koral--/android-gif-drawable#505]
Hey,
Just wanted to play with Sample in version 1.2.7 (java version and not kotlin), but when loading the sample directory project into my android studio, gradle  returns to me this kind of error.

![image](https://user-images.githubusercontent.com/28981511/35672483-679104a2-0747-11e8-849f-bd057057e8bf.png)

What should i do?
10x

**Comment by BoomBoomBoom2017** [comment]
I resolve this issue. now my build gradle script looks like that. 

apply plugin: 'com.android.application'

buildscript {

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

ext {
    versions = [
            compileSdk        : 27,
            targetSdk         : 27,
            minSdk            : 14,
            buildTools        : '27.0.2',
            androidSupport    : '27.0.2',
            androidSupportTest: '1.0.1'
    ]
}


    android {
        compileSdkVersion versions.compileSdk
        buildToolsVersion versions.buildTools
        android.compileOptions.sourceCompatibility 1.8
        android.compileOptions.targetCompatibility 1.8

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }

        defaultConfig {
            versionName project.version
            minSdkVersion versions.minSdk
            targetSdkVersion versions.targetSdk
            versionCode 1
            applicationId 'pl.droidsonroids.gif.sample'
        }

        buildTypes {
            release {
                minifyEnabled true
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            }
            debug {
                jniDebuggable true
            }
        }
        lintOptions {
            disable 'AppCompatCustomView'
        }
    }

    dependencies {
        debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5.4'
        releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.4'
        compile "com.android.support:design:$versions.androidSupport"
        compile "com.android.support:appcompat-v7:$versions.androidSupport"
        //compile 'pl.droidsonroids.gif:android-gif-drawable:+'
    }

repositories {
    google()
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

but i have new errors appeared,

![image](https://user-images.githubusercontent.com/28981511/35675280-1a189b28-0750-11e8-8e6c-28fbb257a1f6.png)


Can someone share a working Java code sample with the newest android studio ??

10x

**Comment by koral--** [comment]
`//compile 'pl.droidsonroids.gif:android-gif-drawable:+'`
dependency is commented out. You need `compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.7'` if you want that version.
