### ISSUE TITLE
[Question] GifTexImage2D

### ISSUE THREAD

**Issue by benexus** [koral--/android-gif-drawable#506]
Is there any way to know when the gif reaches its end (just before looping) using GifTexImage2D ?

**Comment by koral--** [comment]
Currently there is no API for that in `GifTexImage2D`. However it is possible to add something.
What exactly do you need? Listener with callback called when loop has just finished? Ability to get current frame index?

**Comment by benexus** [comment]
Hi, thanks for your answer, great library btw
Ability to get current frame index would be cool
I'm applying some shaders to video using opengl, and I record the surface to create the output
I would like to do the same thing with GIF
 - Play the GIF on a surface
 - Apply some filter/effects
 - Record the surface as a new video
 - Convert the video to GIF
I know when the video stops playing, so I know when to stop recording. I tried to use duration and measure the time since I started paying the GIF, but the resulted video is not what I expect.
Knowing the current frame will allow me to stop recording

Thanks

**Comment by koral--** [comment]
OK, I'll try to add such feature.

**Comment by crlesage** [comment]
Hey, I appreciate this feature request, though I noticed the release build is v1.2.10 from Jan 1st. Is there an expected date for an update to this release build (notably that includes this new feature)? 

Thanks again for the awesome library!

**Comment by koral--** [comment]
Version `1.2.11-SNAPSHOT` is already available on maven snapshot repo.
I'll release `1.2.11` tomorrow.

**Comment by crlesage** [comment]
Thank you very much!

**Comment by koral--** [comment]
Version `1.2.11` is released to maven central.
