### ISSUE TITLE
Feat: Expose GifTexImage2D to setSpeed

### ISSUE THREAD

**Issue by crlesage** [koral--/android-gif-drawable#520]
Hey,

Love this project! I am using the GifTexImage2D with OpenGL though the GifTexImage2D class does not have access directly to the GifInfoHandle's setSpeed function. Could you create a method to control this in the GifTexImage2D class?

Thank you!

**Comment by koral--** [comment]
It shouldn't be an issue. I'll try to add such feature ASAP.
