### ISSUE TITLE
native crash

### ISSUE THREAD

**Issue by jasonross** [koral--/android-gif-drawable#522]
I am using android-gif-drawable:1.2.11, there are some online crashes on my app.

Phone: Xoom
Rom: motorola/tervigon
Android System Version: Android 4.1.2, level 16

SIGILL(ILL_ILLOPC)
1  pc 000058c4 /data/data/com.narvii.amino.master/lib/libpl_droidsonroids_gif.so [armeabi-v7a]
2 java:
3 pl.droidsonroids.gif.GifInfoHandle.renderFrame(Native Method)
4 pl.droidsonroids.gif.GifInfoHandle.renderFrame(GifInfoHandle.java:158)
5 pl.droidsonroids.gif.RenderTask.doWork(RenderTask.java:17)
6 pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:255)
7 pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:124)
8 pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:135)
9 pl.droidsonroids.gif.LGifDrawable.<init>(LGifDrawable.java:19)
10 com.narvii.util.gif.NVGifDrawable.<init>(NVGifDrawable.java:46)
11 com.narvii.util.gif.GifLoader$Session.update(GifLoader.java:119)
12 com.narvii.util.gif.GifLoader$WorkerDownload.run(GifLoader.java:656)

**Comment by koral--** [comment]
Fix is available in version `1.2.12-SNAPSHOT`.

**Comment by jasonross** [comment]
@koral-- when will you release a new version?

**Comment by koral--** [comment]
It should be ready until tomorrow (in GMT timezone).

**Comment by koral--** [comment]
Sorry for the little delay. I've just released version `1.2.12`.
