### ISSUE TITLE
 Failed to resolve: pl.droidsonroids.gif:android-gif-drawable:1.2.12 

### ISSUE THREAD

**Issue by surajnavkudkarglobant** [koral--/android-gif-drawable#527]
Unable to resolve the latest version. With old version ie: 1.2.11 I was able to compile

**Comment by koral--** [comment]
It looks like maven repository issue which I need to report to sonatype.
Workaround for now is to add `maven { url "https://oss.sonatype.org/content/repositories/releases" }` to `repositories` block in `build.gradle`.

**Comment by koral--** [comment]
Yep, it's a maven central repository issue and there are more affected artifacts. Here is the ticket: https://issues.sonatype.org/browse/OSSRH-38687

**Comment by koral--** [comment]
Maven central should work now.
