### ISSUE TITLE
Question: is it possible to crop a GIF animation, or at least show a specific rectangle of it?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [koral--/android-gif-drawable#532]
As the title says...

**Comment by koral--** [comment]
Yes, you can use [Transform](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.12/pl/droidsonroids/gif/transforms/Transform.html) for that.
E.g.
```kotlin
gifDrawable.transform = object : Transform {
            val destinationRect = Rect()
            val sourceRect = Rect(0, 0, 60, 60)
            override fun onBoundsChange(bounds: Rect) {
                destinationRect.set(bounds)
            }

            override fun onDraw(canvas: Canvas, paint: Paint, buffer: Bitmap) {
                canvas.drawBitmap(buffer, sourceRect, destinationRect, null)
            }

        }
```
This will show 60x60 px rectangle of a GIF.

**Comment by koral--** [comment]
Do you mean Android library? I haven't used any such library, maybe Glide does support that?
Outside Android world, imagemagick should be able to do that.

**Comment by AndroidDeveloperLB** [comment]
Yes, Android library here on Github...
Glide can crop images?
I thought it's only for viewing them...

**Comment by koral--** [comment]
It has transformations: https://github.com/bumptech/glide/wiki/Transformations

**Comment by JessonYue** [comment]
@koral--  gifDrawable.transform = object : Transform {
            val destinationRect = Rect()
            val sourceRect = Rect(0, 0, 60, 60)
            override fun onBoundsChange(bounds: Rect) {
                destinationRect.set(bounds)
            }

            override fun onDraw(canvas: Canvas, paint: Paint, buffer: Bitmap) {
                canvas.drawBitmap(buffer, sourceRect, destinationRect, null)
            }

        }
通过上面的代码，可以让gif进行区域现实，请问如何进行gifdrawable的保存呢？我想保存成gif到sdcard

**Comment by koral--** [comment]
@JessonYue please fill a new issue and write text in English.
