### ISSUE TITLE
Size of GIF

### ISSUE THREAD

**Issue by meshileya** [koral--/android-gif-drawable#533]
I have a gif of size 1081 x 1912, but whenever i use it in my xml layout, it tends to look so small, even though i make use of match parent for both height and width.

```
<pl.droidsonroids.gif.GifImageView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/icon_gif_two"
            />
```

**Comment by koral--** [comment]
Could you share code containing minimal reproducible sample?

**Comment by meshileya** [comment]
I only used it in my xml file that way.

Note: That's the only View on the xml file, wherein the parent layout is "match_parent" for both height and width.

**Comment by koral--** [comment]
What does it exactly mean `look so small`? Is it smaller than the same GIF in plain `ImageView`?

**Comment by meshileya** [comment]
yes

*MESHILEYA I. O*

08137065162

**Comment by koral--** [comment]
OK I will check that with GIF 1081 x 1912.

**Comment by koral--** [comment]
I could not reproduce this issue. Please share a project with minimal reproducible sample.

**Comment by meshileya** [comment]
https://github.com/meshileya/TestGif @koral--  This is a simple project that explains what the complaint is....the actual resolution 1081 x 1921 ...and it looks smaller on the layout even after using match parent for both width and height.

I sincerely do appreciate your time.

**Comment by koral--** [comment]
OK, thanks I'll check that.

**Comment by koral--** [comment]
That GIF has a lot of transparent pixels on borders.
![image](https://user-images.githubusercontent.com/3340954/39399419-92e93e3e-4b1d-11e8-965b-1a706da00d25.png)

You can either modify GIF file (reduce borders size) or set `android:scaleType="matrix"` and use appropriate matrix like this:
```java
        final ImageView imageView = findViewById(R.id.image);
        final Matrix matrix = new Matrix();
        final float dx = imageView.getDrawable().getIntrinsicWidth() / 4f;
        matrix.setTranslate(-dx, 0);
        matrix.postScale(0.7f, 0.7f);
        imageView.setImageMatrix(matrix);
```

There is no difference between `GifImageView` and `ImageView` in that matter.
