### ISSUE TITLE
There is a problem

### ISSUE THREAD

**Issue by 15915763299** [koral--/android-gif-drawable#535]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.enzhi.adminpay/com.enzhi.adminpay.activity.homepage.driving.ActDrivingLicense}: android.view.InflateException: Binary XML file line #16: Error inflating class

 line #16 is:
        <pl.droidsonroids.gif.GifImageView
            android:id="@+id/gif_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:src="@drawable/gif_id_card" />

and stack info is:
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327),android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389),android.app.ActivityThread.access$800(ActivityThread.java:153),android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305),android.os.Handler.dispatchMessage(Handler.java:102),android.os.Looper.loop(Looper.java:135),com.landicorp.idcard.reader.lib.IDCardReader$2$1.onLogin(Unknown Source),com.landicorp.idcard.reader.lib.connection.HttpRequest$OperatorAsynTask.onPostExecute(Unknown Source),com.landicorp.idcard.reader.lib.connection.HttpRequest$OperatorAsynTask.onPostExecute(Unknown Source),android.os.AsyncTask.finish(AsyncTask.java:636),android.os.AsyncTask.access$500(AsyncTask.java:177),android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653),android.os.Handler.dispatchMessage(Handler.java:102),android.os.Looper.loop(Looper.java:135),android.app.ActivityThread.main(ActivityThread.java:5271),java.lang.reflect.Method.invoke(Native Method),java.lang.reflect.Method.invoke(Method.java:372),com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902),com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

My English is not so good. Sorry.

**Comment by koral--** [comment]
> android:src=""

src cannot be empty. You have to provide valid resource id (drawable or raw).
