### ISSUE TITLE
Question: is it still better to use this library for Android 8.0 and above?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [koral--/android-gif-drawable#539]
I think Bitmaps are stored in native memory from Android 8.0, but not sure about GIF, and not sure how efficient it is.

That's why I've set a test for this.

Attached here 2 projects that show the same GIF.
[comparison.zip](https://github.com/koral--/android-gif-drawable/files/1932147/comparison.zip)

Sample Gif that I've tried can be downloaded here:
https://ufile.io/pmc7y

It seems that GifDrawable uses more CPU and has more frame drops, even though it is smaller in size of what to show:

GifDrawable:
![image](https://user-images.githubusercontent.com/5357526/39051671-173b5edc-44b2-11e8-953b-ec6b1ee31b7b.png)

Movie based solution:
![image](https://user-images.githubusercontent.com/5357526/39051634-ec4a9d8c-44b1-11e8-90a4-825ea29604e9.png)

**Comment by koral--** [comment]
> is it still better to use this library for Android 8.1 and above?

Better for what use case?

AFAIK `Movie` class had issues with hardware accelerated graphics and memory leaks. That's why this library is created.

**Comment by AndroidDeveloperLB** [comment]
@koral--  Better in all use cases.
Memory, CPU,...
If it has memory leaks, can you please show a sample where it happens? On which versions of Android ?
Maybe it got fixed on some API level?
Did you see a bug report of this?
If not, maybe it's time:
https://issuetracker.google.com/

**Comment by AndroidDeveloperLB** [comment]
Have you tried the sample GIF?
The GifDrawable shows it too slow compared to how it really is...

**Comment by koral--** [comment]
As a use case I mean't something like "just display small GIF file with default speed" or "display subsampled GIF having 10000 frames with half of the speed" or "grab frames as OpenGL textures", not the "CPU" etc.

Here is one of the occurences of hardware accelaration issues: https://stackoverflow.com/questions/29919873/android-error-signal-11-when-a-movie-draws-into-a-canvas
I'm not tracking Movie issues.

This library does not buffer all the frames but reads them when needed. So performance may be lower than solutions using different approaches.

**Comment by AndroidDeveloperLB** [comment]
I don't think it loads all into memory.
The GIF I've presented is quite large (chosen because I wanted to test it).
Can you please check it (library vs Movie) out on Android 8.0 and above?
Is it maybe possible to enable hardware acceleration on the library, and it might be better?

**Comment by AndroidDeveloperLB** [comment]
And by use case, I only showed playing of GIF animation. Isn't it what it's all about?

**Comment by koral--** [comment]
> Can you please check it (library vs Movie) out on Android 8.0 and above?

Sure, will do that ASAP.

> I only showed playing of GIF animation

Issue title does not clearly point this, but now I understand.

**Comment by AndroidDeveloperLB** [comment]
The library is about showing Gif animation as main priority, no?
This is the reason I wanted to try it out

**Comment by koral--** [comment]
> The library is about showing Gif animation as main priority, no?

Yes, but not only using Drawable/Canvas.

Here are my results of GPU profiling, with the same view sizes:
![comparison](https://user-images.githubusercontent.com/3340954/39408801-44bfa01c-4bdc-11e8-9ee7-e72ad629f066.gif)

**Comment by AndroidDeveloperLB** [comment]
What did you do to make it have the same size? can you please share the code?

Also, I'm not sure which is better. Both seem usually below the green line, while the GifDrawableTest doesn't get updated much. Could it mean that it doesn't update enough compared to the FPS the GIF needs? Or that the GifTest gets updated too much compared to the FPS the GIF needs?

**Comment by koral--** [comment]
> What did you do to make it have the same size? can you please share the code?

Here is the code:
`view.layoutParams = ViewGroup.LayoutParams(690, 388)`
690 x 388 is the size of a GIF in pixels. I've used it in both apps.

> GifTest gets updated too much compared to the FPS the GIF needs?

That's the proper answer. You are calling `invalidate()` from within `onDraw()` so a view is invalidated as fastest as possible. More frequent than needed.

**Comment by AndroidDeveloperLB** [comment]
About the size, I was hoping for a wrap-content one.

Not exactly me, as I've found those solutions somewhere else.
I've now tried to check if it's possible via the API to get the FPS of the file, and I don't see it.
Maybe parsing is needed to optimize it. The over-calling of invalidate does seem too much.

About the difference in animation, still I wasn't sure. Both seem to work well. Just the graph seems janky on the library (though maybe it's actually better) compared to the smooth one on the API. Maybe it psychologically made me think the animation at the top is better.

So I went to the profiler. This is of the library:

![image](https://user-images.githubusercontent.com/5357526/39412047-af50d3be-4c1e-11e8-863e-12e7386a9d83.png)

And this is of official API:

![image](https://user-images.githubusercontent.com/5357526/39412059-f357b5f0-4c1e-11e8-86dd-6b98382e5884.png)


In CPU usage, they are about the same (around 3%). The API might take a single percent less. 

However, in memory usage, the library takes a lot less (~168MB vs ~59MB). What causes it to be this different?

And, what would you advice to use in case I want to show it in a live wallpaper?

**Comment by koral--** [comment]
> However, in memory usage, the library takes a lot less (~168MB vs ~59MB). What causes it to be this different?

Maybe they are preloading more frames to memory? This library decodes keeps given frames only if they are needed.

> And, what would you advice to use in case I want to show it in a live wallpaper?

I don't have much experience with wallpapers. In this library there is no API dedicated for wallpapers.  However some people implemented that with `GifDrawable`: https://github.com/koral--/android-gif-drawable/issues/267

**Comment by AndroidDeveloperLB** [comment]
So maybe there is some advantage? Maybe more memory means less usage of storage?
Or actually that's just the throughput ? 
Maybe seeing them use more memory doesn't mean I should avoid using them?

**Comment by koral--** [comment]
You can try to check source code of `Movie` and its dependencies. It may be easier using services like xref: http://androidxref.com/

**Comment by koral--** [comment]
It is slightly modified, mostly by removing support for features never used by library e.g. pixel aspect ratio.

**Comment by AndroidDeveloperLB** [comment]
I see. Thanks.
