### ISSUE TITLE
About running the GIF.

### ISSUE THREAD

**Issue by BeatGeneration** [koral--/android-gif-drawable#543]
Hello, I would like to ask you a question. Flash problems occur when I run my GIF. What could possibly be the cause? What do I need to do? Thank you!

**Comment by BeatGeneration** [comment]
I saw the link you provided and used the method, but it didn't work.

**Comment by koral--** [comment]
Thanks for the GIF, I will try to reproduce this issue.
Could you provide some some info what exactly from this library are you using (`GifDrawable`, `GifImageView` etc.)? Preferably as a code snippet.

> My project is running on the Android PAD

Does issue happen only on that device?

**Comment by BeatGeneration** [comment]
`try {
            ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);
            mGifDrawable = new GifDrawableBuilder().taskExecutor(executor).from(getResources(), resources).build();
            mGifImageView.setImageDrawable(mGifDrawable);
        } catch (IOException e) {
            e.printStackTrace();
        }`

This is my code. This GIF is set to run 20 times and stop. It's normal to run on my phone. Maybe my PAD is a low-end device. The problem of using setSpeed() to speed up the flash of a GIF is even more obvious.

**Comment by koral--** [comment]
Thanks, I will to reproduce that.

**Comment by koral--** [comment]
Sorry, for the delay.
I couldn't manage to reproduce any flashing on devices I'm using. However, there was/is one similar issue: https://github.com/koral--/android-gif-drawable/issues/162#issuecomment-99172799

In a nutshell:
If drawing operations go through Android's Canvas and it is updated frequently and/or bitmaps drawn are  large enough then flashing may occur. Exact frequency and bitmap size varies depending on device and Android version. Maybe you have reached those limits on PAD device?

Workaround is to use something else than Drawable. For example `GifTextureView` or `GifTexImage2D`. They don't use Canvas.
