### ISSUE TITLE
GifImageView gif only runs one time after load gif resource

### ISSUE THREAD

**Issue by VW-LAMANDO** [koral--/android-gif-drawable#544]
i use `GifImagerView` with following the example, but the gif only run one time.
even though i set the loop number in the view attribute of xml, it didn't work.
please help to check this. why this happened, is there any relation with the gif resource?

<attr name="loopCount" format="integer"/>
app:loopCount="100",  then call api `getLoopCount` ,result is `1`.
if i use api `setLoopCount(100)`, it works well, why ?

**Comment by koral--** [comment]
Looks like a bug, I'll check that.

**Comment by koral--** [comment]
I could not reproduce that. 
Loop count is set from the `GifImageView` constructor assuming that  GIF is also set in XML as src or background. Loop count is not remembered inside the view, so if you set the drawable later it will have its default loop count.
