### ISSUE TITLE
making Gif run only a particular number of time

### ISSUE THREAD

**Issue by smw7156** [koral--/android-gif-drawable#548]
I have 3 Gif, I want the 1st one to run only one time(i.e. completing only one loop), 2nd one only 3 time and the 3rd one only one time.
How can I do that using this library. (i.. controlling the no. of time Gif played)

**Comment by koral--** [comment]
You can use [#setLoopCount()](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.12/pl/droidsonroids/gif/GifDrawable.html#setLoopCount-int-) method.
