### ISSUE TITLE
setloopcount not working

### ISSUE THREAD

**Issue by dondeepak** [koral--/android-gif-drawable#549]
ive setLoopCount =1 but gif not stoping  also tried to using AnimationListener and GifDrawable.stop(); but not working what i am doing wrong??
            try {
                gifDrawable  = new GifDrawable( getResources(), R.drawable.fdsg );

            } catch (IOException e) {
                e.printStackTrace();
            }

            gifDrawable.setLoopCount(1);

            gifDrawable.addAnimationListener(new AnimationListener() {
                @Override
                public void onAnimationCompleted(int loopNumber) {
                    gifDrawable.stop();
                }
            });

///
xml:
   <pl.droidsonroids.gif.GifImageView
        android:id="@+id/gifImageView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="fitXY"
       android:src="@drawable/fdsg" />

**Comment by koral--** [comment]
Do you set `gifDrawable` in `gifImageView`?
Something like this: `gifImageView.setImageDrawable(gifDrawable);` is missing in your snippet.

**Comment by dondeepak** [comment]
yes ive set gifDrawable in gifImageView but after many attempt i solved it

thanks for the reply @koral-- 

java:
GifImageView gifImageView = (GifImageView) findViewById(R.id.gifImageView);
 gifDrawable = (GifDrawable) gifImageView.getDrawable();
 gifDrawable.setLoopCount(1);
xml:
   <pl.droidsonroids.gif.GifImageView
        android:id="@+id/gifIma geView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:src="@drawable/fdsg"
        android:scaleType="fitXY"
        />

**Comment by koral--** [comment]
There is an easier way to do that:
```xml
<pl.droidsonroids.gif.GifImageView
android:id="@+id/gifIma geView"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:src="@'drawable/fdsg"
android:scaleType="fitXY"
app:loopCount="1"
/>
```
