### ISSUE TITLE
使用GifImageView加载一次后，怎样关闭该动画（即：想dialog）

### ISSUE THREAD

**Issue by qianzhihe86** [koral--/android-gif-drawable#551]
使用GifImageView加载一次后，怎样关闭该动画（即：像dialog一样dismiss掉）

**Comment by koral--** [comment]
I don't speak Chinese, however from the automatic translation I understand that you want to play the animation only once.
To do so you need to put `app:loopCount="1"` attribute into your `<GifImageView>` tag (if GIF is set using `android:src`) or call `gifDrawable.setLoopCount(1)` (optionally obtaining it using `gifImageView.getDrawable()` first).

If it doesn't answer your question please write a comment in English.
