### ISSUE TITLE
The reason this library efficient than Movie class

### ISSUE THREAD

**Issue by rhonyabdullah** [koral--/android-gif-drawable#553]
Hello koral,
This library is awesome, but i need to know why you claimed this library is more efficient rather than using Movie class from android graphics ? Thanks.

And btw, i try to use `GifTextureView` class to load png file and it doesn't work, is this class only works with *.gif only ?

**Comment by koral--** [comment]
Movie was not releasing allocated resources properly. AFAIK it was fixed a long time ago after releasing this library. Additionally Movie can only draw on Canvas. With `GifTextureView` and `GifTexImage2D` you can draw directly on surface or GL texture with lesser overhead. Movie does not support subsampling.

> And btw, i try to use GifTextureView class to load png file and it doesn't work, is this class only works with *.gif only ?

Exactly, `GifTextureView` supports only GIFs.
