### ISSUE TITLE
Gif listener

### ISSUE THREAD

**Issue by ardakaplan** [koral--/android-gif-drawable#554]
Hi, I use gittextview like this,

 <pl.droidsonroids.gif.GifTextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/tenor" />

I want to know when gif stops,playing, repeating? Is there any listener for this?

**Comment by koral--** [comment]
You can obtain `GifDrawable` instance using `getBackground()` then you can add listener using [addAnimationListener()](https://static.javadoc.io/pl.droidsonroids.gif/android-gif-drawable/1.2.12/pl/droidsonroids/gif/GifDrawable.html#addAnimationListener-pl.droidsonroids.gif.AnimationListener-) method.
