### ISSUE TITLE
Gradle issue in New Release(v1.2.13)

### ISSUE THREAD

**Issue by balrampandey19** [koral--/android-gif-drawable#560]
Hi, seams like some issue in new realease not able to Build project.
`
A problem occurred configuring project ':app'. > Could not resolve all dependencies for configuration ':app:_DebugApkCopy'. > Could not find android-gif-drawable:android-gif-drawable-native-armeabi:unspecified. Required by: project :app > pl.droidsonroids.gif:android-gif-drawable:1.2.13
`

**Comment by koral--** [comment]
Sorry for that faulty release. For now workaround is to exclude that invalid dependency:
```
  implementation ("pl.droidsonroids.gif:android-gif-drawable:1.2.13") {
    exclude(module: 'android-gif-drawable-native-armeabi')
  }
```
I'll release fixed version ASAP.

**Comment by koral--** [comment]
Version 1.2.14 has just been released. It should appear on maven central within 2 hours. Sorry for the inconvenience.
