### ISSUE TITLE
Why do you play it smart once?How can I loop it?

### ISSUE THREAD

**Issue by fangxiaole** [koral--/android-gif-drawable#564]
Why do you play it smart once?How can I loop it?

**Comment by koral--** [comment]
Loop count can be set in each GIF file. By default this library respects it.
You can however override that by calling `GifDrawable#setLoopCount(0)` or `app:loopCount="0"` in XML. 0 is a special value meaning infinite loop count.

**Comment by fangxiaole** [comment]
Thank you, the problem is solved.
