### ISSUE TITLE
Not working on API 22

### ISSUE THREAD

**Issue by joaogouveia89** [koral--/android-gif-drawable#567]
In a device with API 26 is working well, but when I try to run in a API 22 device the gif is unanimated.

I'm using data binding and my code is:

XML file:
`<pl.droidsonroids.gif.GifTextView
            android:id="@+id/gif_butterfly"
            android:layout_width="120dp"
            android:layout_height="112dp"
            android:visibility="gone"
            android:background="@drawable/butterfly"/>`

Java file:
`.setLayerType(View.LAYER_TYPE_SOFTWARE, null);`

In API 22 device, I got the log

`W/linker: libpl_droidsonroids_gif.so: unused DT entry: type 0x6ffffffe arg 0x19ec
    libpl_droidsonroids_gif.so: unused DT entry: type 0x6fffffff arg 0x1`

Do you have any idea what is going on?

**Comment by koral--** [comment]
Looks like a bug.
Could you attach `butterfly.gif` here or send it via email?

**Comment by joaogouveia89** [comment]
sure... here it is

Thank you very much

![butterfly](https://user-images.githubusercontent.com/10503530/42484219-4765cf16-83c8-11e8-8b0c-be599da41635.gif)

**Comment by dipen-apptrait** [comment]
same problem...

**Comment by koral--** [comment]
I've tried on Samung J5 with API 22 and I could not reproduce this issue. The GIF is animating properly.
Which device are you using?

**Comment by joaogouveia89** [comment]
I was using Asus Zenfone 2 laser

https://www.androidcentral.com/asus-zenfone-2-laser-ze551kl-specs

but updated to Android 5.1(API 22)

**Comment by koral--** [comment]
Could you share a minimal reproducible sample code?

**Comment by koral--** [comment]
Closed due to inactivity, may be reopened when new info is provided.
