### ISSUE TITLE
it may be a bug

### ISSUE THREAD

**Issue by weiyuxu** [koral--/android-gif-drawable#574]
When same GIF used in list it may stop play.
Thank you!

**Comment by koral--** [comment]
Look here: https://github.com/koral--/android-gif-drawable/issues/295
If that is not your issue please provide more info. Preferably a sample project reproducing your issue.

I'll close this ticket for now, but it may be reopened if more info is provided.

**Comment by weiyuxu** [comment]
Thank you very much for answering me！My English is not very good。 When i remove an item from a RecyclerView the playing GIF below the item stopped.

**Comment by koral--** [comment]
Do items use the same drawable instance?

**Comment by weiyuxu** [comment]
No,they are different. When i remove an item from a RecyclerView the method of convert called then the gifDrawable set to gifImageView again and GIF stopped.when i  postDelayed set  gifDrawable set to gifImageView it works

**Comment by koral--** [comment]
Could you attach a piece of code which is reproducing that issue?

**Comment by weiyuxu** [comment]
private void handleGif(final NewsFlowItem newsFlowItem) {  
      ......
      if (GifDrawableUtil.isInCache(displayUrl)) {
            if (newsFlowItem.gifRadio > 0) {
                resizeImageView(R.id.gif_img_big_layout, newsFlowItem.gifRadio);
            }
            GifDrawable gifDrawable = GifDrawableUtil.getFromCache(displayUrl);
            gifImageView.setImageDrawable(gifDrawable);
           ......
        } else {....}
        ...
}

**Comment by weiyuxu** [comment]
@Override
    public void convert(BaseFlowItem item, boolean isNightMode) {
....
handleGif(item);
.....
}

**Comment by koral--** [comment]
What is BaseFlowItem? Could you share a project containing minimal reproducible sample.
