### ISSUE TITLE
Does the WebP branch work?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [koral--/android-gif-drawable#577]
For some reason I've failed to import it correctly:

![image](https://user-images.githubusercontent.com/5357526/44296471-84349e80-a2c8-11e8-89af-81dddd4497b6.png)

Even after I've updated all that I can, I get this error:

![image](https://user-images.githubusercontent.com/5357526/44296320-729dc780-a2c5-11e8-90c5-58caf6b2ee40.png)

Is it possible to use it , or is it completely unusable for now?

**Comment by koral--** [comment]
It wasn't updated for a long time but it should work AFAIR. I'll check that. Thanks for the report.

**Comment by AndroidDeveloperLB** [comment]
In which state does it stay?
How close is it to be on release branch of the repository?
Is it possible to use it via gradle ?

**Comment by koral--** [comment]
Sorry for the delay.
The latest commit on that branch indeed does not compile. However this one works (4 commits before a latest one): 022e5af9c994087cf349b869b79986e6e0316888

> In which state does it stay?

It is work in progress, not yet usable.

> How close is it to be on release branch of the repository?

It is not close, there is a lot of work to do.

> Is it possible to use it via gradle ?

Do you mean including it as a gradle dependency? I haven't published it any maven repo.

**Comment by AndroidDeveloperLB** [comment]
Which features/functions work, and which don't (choose the smaller group in order to type less, if you wish) ?

**Comment by koral--** [comment]
- only sources which can be read as `FileDescriptor` source are supported, so no support for arrays, byte buffers, input streams
- only way to transfer pixels is `glTexSubimage2D` (like in `GifTexImage2D`), no support for `Drawable` and `TextureView`
- apart from that only supported operations are: getting canvas dimensions and disposing, no support for actions like
- WebP backgroud color is not read
- WebP metadata e.g. EXIF is not read

**Comment by AndroidDeveloperLB** [comment]
I see. Thanks.

**Comment by koral--** [comment]
It seems that there is no more unanswered questions so I'm closing this ticket.
