### ISSUE TITLE
[Q] About FileDescriptor leaks

### ISSUE THREAD

**Issue by Guang1234567** [koral--/android-gif-drawable#578]
Hello koral:

**Lib version:  '1.1.7'**

**Test1**
I  get into trouble that pass a PNG (R.raw.testpng)  to `GifImageView`.  Then cause a `GifError 103 : data is not the gif` and make the `fd leaks` that not release after gc !

**Test2**
I pass a GIF (R.raw.realgif) to `GifImageView` .  Then increase the number of fd that can release after gc ! 

How to print fds ?

```bash

ls -lt /proc/your_app_pid/fd | grep your_app_pid_name -c

```

**Comment by koral--** [comment]
Cool, so I'm closing this issue 😄

**Comment by Guang1234567** [comment]
Hello koral:

I just want to realize the reason that why fd leaks in version 1.1.7?

Because i check the java code, `AssetFileDescriptor` has closed when exception happen.  Is some thing wrong in the native code?

```java
static GifInfoHandle openAssetFileDescriptor(AssetFileDescriptor afd, boolean justDecodeMetaData) throws
            IOException {
        try {
            return openFd(afd.getFileDescriptor(), afd.getStartOffset(), justDecodeMetaData);
        } finally {
            afd.close();
        }
    }
```

**Comment by koral--** [comment]
Yep, here was the missing file descriptor close: https://github.com/koral--/android-gif-drawable/commit/cd8152a79dcad787c35d5c95c9befcbea325fa68#diff-50a21419cc7d37727f18ec6d64c91080R318

**Comment by Guang1234567** [comment]
Thanks a lot. O(∩_∩)O
