### ISSUE TITLE
Device crashing when using GifImageView

### ISSUE THREAD

**Issue by kenshin171** [koral--/android-gif-drawable#579]
Hi, first of all great lib for gif, really appreciate your work on this library.

My issue is that, occasionally i get a application crash with these logs while going to an actiivty with GifImageDrawable in the layout. 
```
 IMGSRV  E  :0: RGXSubmitTA: Failed to submit kick to kernel (1)
                         E  :0: RGXKickTA: RGXSubmitTA failed (0x1)
                         E  :0: DoKickTA: RGXKickTA() failed with error 1
                         E  :0: FlushRenderSurface: ScheduleTA did not work properly on the attachment
                         E  :0: RGXSubmitTA: Failed to submit kick to kernel (1)
                         E  :0: RGXKickTA: RGXSubmitTA failed (0x1)
                         E  :0: DoKickTA: RGXKickTA() failed with error 1
                         E  :0: FlushRenderSurface: ScheduleTA did not work properly on the attachment
                         E  :0: RGXSubmitTA: Failed to submit kick to kernel (1)
                         E  :0: RGXKickTA: RGXSubmitTA failed (0x1)
                         E  :0: DoKickTA: RGXKickTA() failed with error 1
                         E  :0: FlushRenderSurface: ScheduleTA did not work properly on the attachment
                         E  :0: RGXSubmitTA: Failed to submit kick to kernel (1)
                         E  :0: RGXKickTA: RGXSubmitTA failed (0x1)
                         E  :0: DoKickTA: RGXKickTA() failed with error 1
                         E  :0: FlushRenderSurface: ScheduleTA did not work properly on the attachment
```

The device i am using is 

Asus Zenfone2 ZE551ML
Android 5.0 API 21
CPU = Intel Atom Z3580
GPU = PowerVR G6430

Seems like a GPU issue

**Comment by koral--** [comment]
Hi, unfortunately I can't do much having only that fragment of the log.
Is there any stacktrace?

**Comment by koral--** [comment]
OK, I'll try to grab some device with powerVR GPU and investigate this.

**Comment by koral--** [comment]
I've tried on Samsung Galaxy S (GT-i9000) with unofficial Android 4.4 (which has PowerVR SGX540 on board) and haven't noticed any issue. Also I have no idea what I can do with this issue even theoretically having only info from this thread.

I'll close this issue for now. It may be reopened if there will be any suggestion what can be changed here.

**Comment by kenshin171** [comment]
If the GPU is not the issue then maybe its the intel CPU, well i guess since the intel mobile CPUs are not being produced anymore, hopefully its a non-issue. Thanks for your time in looking into this.
