### ISSUE TITLE
crash stack

### ISSUE THREAD

**Issue by niplus** [koral--/android-gif-drawable#581]
08-27 15:15:49.872 29674-29674/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-27 15:15:49.872 29674-29674/? A/DEBUG: Build fingerprint: 'OnePlus/OnePlus5T/OnePlus5T:8.1.0/OPM1.171019.011/1807181208:user/release-keys'
08-27 15:15:49.872 29674-29674/? A/DEBUG: Revision: '0'
08-27 15:15:49.872 29674-29674/? A/DEBUG: ABI: 'arm64'
08-27 15:15:49.872 29674-29674/? A/DEBUG: pid: 29533, tid: 29533, name: om.taiyun.zgtop  >>> com.taiyun.zgtop <<<
08-27 15:15:49.872 29674-29674/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-27 15:15:49.878 29674-29674/? A/DEBUG: Abort message: 'Could not write wake signal to fd 56: Invalid argument'
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x0   0000000000000000  x1   000000000000735d  x2   0000000000000006  x3   0000000000000008
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x4   fefeff729e76893f  x5   fefeff729e76893f  x6   fefeff729e76893f  x7   7f7f7f7fff7fff7f
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x8   0000000000000083  x9   ee25345ad6ae6aec  x10  0000000000000000  x11  0000000000000001
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x12  ffffffffffffffff  x13  ffffffffffffffff  x14  ffffffffff000000  x15  ffffffffffffffff
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x16  00000001c9ecffa8  x17  000000739e131598  x18  0000000000000008  x19  000000000000735d
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x20  000000000000735d  x21  000000731aac3a00  x22  0000007fc8a55a8c  x23  000000731879ae88
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x24  0000000000000008  x25  000000739f778a40  x26  000000731aac3aa0  x27  0000000000000002
08-27 15:15:49.878 29674-29674/? A/DEBUG:     x28  0000000000000000  x29  0000007fc8a55290  x30  000000739e0e6df8
08-27 15:15:49.878 29674-29674/? A/DEBUG:     sp   0000007fc8a55250  pc   000000739e0e6e14  pstate 0000000060000000
08-27 15:15:50.099 29674-29674/? A/DEBUG: backtrace:
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #00 pc 000000000001de14  /system/lib64/libc.so (abort+104)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #01 pc 0000000000008134  /system/lib64/liblog.so (__android_log_assert+304)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #02 pc 0000000000015b80  /system/lib64/libutils.so (android::Looper::wake()+192)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #03 pc 0000000000631158  /system/framework/arm64/boot-framework.oat (offset 0x630000) (android.os.Binder.restoreCallingIdentity [DEDUPED]+152)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #04 pc 000000000054864c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #05 pc 00000000000dcfb0  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+260)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #06 pc 000000000029a188  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #07 pc 0000000000294770  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+696)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #08 pc 000000000053189c  /system/lib64/libart.so (MterpInvokeStatic+224)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #09 pc 000000000053a214  /system/lib64/libart.so (ExecuteMterpImpl+14612)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #10 pc 0000000000274bd4  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #11 pc 000000000027a7dc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #12 pc 0000000000294750  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+664)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #13 pc 0000000000530528  /system/lib64/libart.so (MterpInvokeVirtual+612)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #14 pc 000000000053a094  /system/lib64/libart.so (ExecuteMterpImpl+14228)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #15 pc 0000000000274bd4  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #16 pc 000000000027a7dc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #17 pc 0000000000294750  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+664)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #18 pc 0000000000530528  /system/lib64/libart.so (MterpInvokeVirtual+612)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #19 pc 000000000053a094  /system/lib64/libart.so (ExecuteMterpImpl+14228)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #20 pc 0000000000274bd4  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #21 pc 000000000027a7dc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #22 pc 0000000000294750  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+664)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #23 pc 0000000000530528  /system/lib64/libart.so (MterpInvokeVirtual+612)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #24 pc 000000000053a094  /system/lib64/libart.so (ExecuteMterpImpl+14228)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #25 pc 0000000000274bd4  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #26 pc 000000000027a7dc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #27 pc 0000000000294750  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+664)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #28 pc 000000000053189c  /system/lib64/libart.so (MterpInvokeStatic+224)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #29 pc 000000000053a214  /system/lib64/libart.so (ExecuteMterpImpl+14612)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #30 pc 0000000000274bd4  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #31 pc 000000000027a7dc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #32 pc 0000000000294750  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+664)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #33 pc 000000000053189c  /system/lib64/libart.so (MterpInvokeStatic+224)
08-27 15:15:50.099 29674-29674/? A/DEBUG:     #34 pc 000000000053a214  /system/lib64/libart.so (ExecuteMterpImpl+14612)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #35 pc 0000000000274bd4  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #36 pc 000000000027a7dc  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame*, art::JValue*)+216)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #37 pc 0000000000294750  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+664)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #38 pc 0000000000531474  /system/lib64/libart.so (MterpInvokeInterface+1528)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #39 pc 000000000053a294  /system/lib64/libart.so (ExecuteMterpImpl+14740)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #40 pc 0000000000274bd4  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue, bool)+444)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #41 pc 0000000000523104  /system/lib64/libart.so (artQuickToInterpreterBridge+1052)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #42 pc 000000000055150c  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #43 pc 0000000000548388  /system/lib64/libart.so (art_quick_invoke_stub+584)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #44 pc 00000000000dcf74  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #45 pc 000000000046c65c  /system/lib64/libart.so (art::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::ArgArray*, art::JValue*, char const*)+100)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #46 pc 000000000046dae4  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+440)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #47 pc 0000000000351b24  /system/lib64/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+624)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #48 pc 0000000000111264  /system/lib64/libart.so (art::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primitive::Type, art::InvokeType)+2664)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #49 pc 00000000000ff54c  /system/lib64/libart.so (art::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+92)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #50 pc 00000000000ba888  /system/lib64/libandroid_runtime.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+120)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #51 pc 0000000000169f48  /system/lib64/libandroid_runtime.so ((anonymous namespace)::Receiver::handleEvent(int, int, void*)+544)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #52 pc 0000000000015fd0  /system/lib64/libutils.so (android::Looper::pollInner(int)+856)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #53 pc 0000000000015bf0  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+108)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #54 pc 0000000000111960  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #55 pc 000000000081a9ac  /system/framework/arm64/boot-framework.oat (offset 0x630000) (android.app.NativeActivity.onWindowFocusChangedNative [DEDUPED]+140)
08-27 15:15:50.100 29674-29674/? A/DEBUG:     #56 pc 000000000000c4a8  /dev/ashmem/dalvik-jit-code-cache (deleted)

**Comment by koral--** [comment]
Could you post some more info? Repro steps, sample code? This stacktrace does not contain anything from this library, so I cannot do anything having only it.

**Comment by koral--** [comment]
Seems to be the same as #581.

**Comment by niplus** [comment]
sorry,I didn't see the reply. My error message is no longer available, but I can describe the scene. When I start the application, load a GIF image as the startup diagram. Sometimes it leads to crashes. My English is not very good, and the translation software is used.

**Comment by koral--** [comment]
Could you provide sample code?

**Comment by niplus** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if(!this.isTaskRoot()) {
            Intent startIntent=getIntent();
            String action=startIntent.getAction();
            if(startIntent.hasCategory(Intent.CATEGORY_LAUNCHER) && action.equals(Intent.ACTION_MAIN)) {
                BuglyLog.e("zgtop", "startactivity has exits");
                finish();
                return;
            }
        }

        setContentView(getLayoutId());

        unbinder = ButterKnife.bind(this);

        initData();

        try {
            GifDrawable gifDrawable = new GifDrawable(getResources(), R.drawable.start);
            gifDrawable.setLoopCount(1);
            gifDrawable.addAnimationListener(new AnimationListener() {
                @Override
                public void onAnimationCompleted(int loopNumber) {
                    handler.sendEmptyMessageDelayed(0, 500);
                }
            });

            ivStart.setImageDrawable(gifDrawable);

            Glide
                    .with(StartActivity.this)
                    .load("http://zg-top.oss-cn-hangzhou.aliyuncs.com/slash/ad.png?v=11")
                    .diskCacheStrategy(DiskCacheStrategy.NONE)
                    .into(new GlideDrawableImageViewTarget(ivPoster){
                        @Override
                        public void onLoadFailed(Exception e, Drawable errorDrawable) {
                            super.onLoadFailed(e, errorDrawable);
                            loadPosterFailed = true;
                        }
                    });


        } catch (IOException e) {
            e.printStackTrace();
        }
    }

ln launch activity

**Comment by koral--** [comment]
Thanks, I'll check that.

**Comment by nuoyan2** [comment]
I'm really sorry that I didn't see this news until the nature of work. I found you should be my friend in hangzhou, China. my qq is 519719668 Thank you! I also used translation software because my English was poor

**Comment by nuoyan2** [comment]
Can I make a suggestion? I hope you can use AS to compile the code. I have not used eclipse for 3 years
Because AS has too many advantages, I'm very sorry. I know this suggestion is not very good, which will cause you a lot of work in the early stage. However, I believe that you will be more and more relaxed in the later stage. My English is not very good using translation software.

**Comment by koral--** [comment]
@nuoyan2 I don't understand how your comment is related to this issue and what is your problem. Please create a separate issue.

**Comment by nuoyan2** [comment]
很抱歉 我可能理解错了 我的意思是  请求对方提供下gif图片我这边尝试下 是在抱歉 可能我不太会规则的说话  我英语不好 我使用了翻译软件
I'm really sorry that I may have misunderstood what I said. What I meant was that I asked the other party to provide the GIF image  
I'm not good at English. I used the translation software

**Comment by koral--** [comment]
@niplus I could not reproduce this issue, but I've corrected a link in https://github.com/koral--/android-gif-drawable/issues/581#issuecomment-416978353 it should point to #582
It seems to be the same kind of issue.
@nuoyan2 I still don't understand what is your problem. Please write it again in a new thread.
