### ISSUE TITLE
Bug: in sample app, losing focus on live wallpaper screen will make it blank

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [koral--/android-gif-drawable#586]
Steps:
1. press on the "gif live wallpaper preview"
2. press recent tasks
3. go back to task

The bug:
it becomes black.

Attached video to show issue.

[device-2018-09-09-170439.zip](https://github.com/koral--/android-gif-drawable/files/2364312/device-2018-09-09-170439.zip)

**Comment by koral--** [comment]
Thanks for the report, I'll check it.

**Comment by koral--** [comment]
It looks like a bug in Android Pie.
Built-in live wallpapers are affected by the same issue.

**Comment by AndroidDeveloperLB** [comment]
Seems as such. Reported here:
https://issuetracker.google.com/issues/116257078

**Comment by koral--** [comment]
Thanks for reporting. I've added also a comment there.

I've tried to find some workaround but haven't discovered anything working.
`Surface` coming from `Engine` becomes unusable after those steps.
