### ISSUE TITLE
Minor: Configuration 'compile' is obsolete and has been replaced with 'implementation'

### ISSUE THREAD

**Issue by Annegrim** [koral--/android-gif-drawable#587]
In the readme it says to include the library like this:

dependencies {
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.15'
}

but in android studio it is:

dependencies {
    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.15'
}

**Comment by koral--** [comment]
Thanks, for spotting that.
I'll update the readme.
