### ISSUE TITLE
Animation Controls

### ISSUE THREAD

**Issue by faizanhaidarkhan** [koral--/android-gif-drawable#588]
Unable to use controls like stop(), isRunning, etc. Please guide how to use them.

**Comment by koral--** [comment]
Hi, there is an example in sample project inside this repo: https://github.com/koral--/android-gif-drawable/blob/dev/sample/src/main/java/pl/droidsonroids/gif/sample/AnimationControlFragment.kt

If something is unclear please ask concrete question, preferably with snippet of your code.
