### ISSUE TITLE
Doesn't work with Android 6.0

### ISSUE THREAD

**Issue by DominusDRR** [koral--/android-gif-drawable#591]
Error:
android.view.InflateException: Binary XML file line #69: Binary XML file line #69: Error inflating class pl.droidsonroids.gif.GifImageView

Grandle app:
compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.+'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "net.sicoy.sicoybox"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 4
        versionName "1.0.4"
        multiDexEnabled true 
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

**Comment by koral--** [comment]
Could you post complete stacktrace?

**Comment by koral--** [comment]
No problem :)
