### ISSUE TITLE
Missing free of info buffer

### ISSUE THREAD

**Issue by MarcSchoenefeld** [koral--/android-gif-drawable#595]
https://github.com/koral--/android-gif-drawable/blob/8b83ceff3e2ad19c88f06f6529c18cd1fe479b90/android-gif-drawable/src/main/c/init.c#L20-L24

Should call free(info) in this block to avoid mem leak . Also for the early return in block starting L51 .

**Comment by koral--** [comment]
Good catch. Thanks for the report I'll fix this ASAP.
