### ISSUE TITLE
Cloning drawable

### ISSUE THREAD

**Issue by kanytu** [koral--/android-gif-drawable#596]
Is there any way to clone a `GifDrawable` without having to decode the source all over again?

I'm wondering how to do this since when, integrated with **Glide**, the object will always be the same for the same source (URL in this case). Which means that an adapter displaying the same resource will have the same drawable. When stopping one, as of now, all others will stop too. However, I want to clone the resource (or create a new one with the same content), before displaying it to the `ImageView`.

Is there anyway of achieving this?

**Comment by koral--** [comment]
I'm not familiar with Glide. It seems that there is no such feature available directly here.
Something similar is possible using `GifDrawableBuilder`. You can create one instance of `InputSource` (e.g. from resources) and use it to create multiple `GfiDrawable`s.
