### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Could not read from eventfd Bad file descriptor

### ISSUE THREAD

**Issue by kenshin171** [koral--/android-gif-drawable#597]
i am getting this crash log in my crashlytics console

devices that this is occuring on

Galaxy A3 and motorola g4 plus both running on android 7

```
Fatal Exception: java.lang.RuntimeException: Could not read from eventfd Bad file descriptor
       at pl.droidsonroids.gif.GifInfoHandle.bindSurface(SourceFile)
       at pl.droidsonroids.gif.GifInfoHandle.getNativeFileDescriptor(SourceFile:199)
       at pl.droidsonroids.gif.GifTextureView$RenderThread.run(SourceFile:225)
```

i am using `gifTextureView`, any idea on why this would happen?

**Comment by koral--** [comment]
Either something else (outside this library) in your app's process is closing file descriptor used by `GifTextureView` (it's just an integer) or there is a bug in library.
If issue occurs only on some devices (tested on the same app and the same GIF) it looks like the 1st case. However, I'll try to grab one of those devices and check that.

**Comment by kenshin171** [comment]
@koral-- An update, more devices are appearing on crashlytics.

Huawei ANE-LX2 (p20 LITE) (), android 8.0.0
Huawei CLT29 (P20 Pro), android 8.1.0
Galaxy Note 3, android 5.0
OnePlus A3003 (3T), android 8.0.0
Vivo V3Max, android 5.1.1

And a little more info, unfortunately this stack trace does not show me the exact part where the crash is happening, but i can provide a little more information as to where i am using gifTexTureView. I am using it as a circular inderterminate progress spinner, so depending on the operation it is waiting for, it will be displayed for unknown amount of time. i can link the gifs i am using for the progress spinner for your reference.

![spinner](https://user-images.githubusercontent.com/6202427/47196331-8c758c80-d392-11e8-84dc-e683f5f25017.gif)

![spinner](https://user-images.githubusercontent.com/6202427/47196339-9ac3a880-d392-11e8-9b08-4375cd6521da.gif)

**Comment by koral--** [comment]
OK, thanks.

**Comment by kenshin171** [comment]
will `GifTexImage2D` potentially encounter this issue too? Does `GifTexImage2D` utilise `GifInfoHandle.bindSurface` too?

**Comment by koral--** [comment]
No, `GifTexImage2D` is not using `GifInfoHandle.bindSurface`.

**Comment by koral--** [comment]
Fix for #600 should also fix this issue.

**Comment by kenshin171** [comment]
When will this fix be released?

**Comment by koral--** [comment]
It is planned to November 18th (Sunday).

**Comment by koral--** [comment]
Sorry for the delay. There are issues with CI, I'll try to resolve them until tomorrow.

**Comment by koral--** [comment]
Version 1.2.16 has been released. It should be available within few hours on maven central.

**Comment by kenshin171** [comment]
awesome thanks
