### ISSUE TITLE
Gif animation start delay in several views

### ISSUE THREAD

**Issue by kaershushu** [koral--/android-gif-drawable#599]

**Comment by koral--** [comment]
Please describe your issue. After you edit description I'll reopen this ticket.

**Comment by kaershushu** [comment]
I have several GifImageViews in the same Layout,and I want every GifImageView to start one by one with time delay.But I find that all the GifImageViews executed without time delayed. I thinke maybe its a bug

**Comment by kaershushu** [comment]
> Please describe your issue. After you edit description I'll reopen this ticket.

Got it.

**Comment by koral--** [comment]
I don't think that lack of a delay when populating GifImageView is a bug.
If you want delays you need to introduce them yourself. For example using `delay()` from kotlin coroutines or `Handler.postDelayed()`.

**Comment by koral--** [comment]
Please post your code.

**Comment by kaershushu** [comment]
**This is the Java code.**
`final GifDrawable gifDrawable = new GifDrawable(App.getInstance().getAssets(),"gif.gif");
            findViewById(R.id.img).postDelayed(() -> mImageView.setImageDrawable(gifDrawable),300);
            final GifDrawable gifDrawable1 = new GifDrawable(App.getInstance().getAssets(),"gif.gif");
            findViewById(R.id.img1).postDelayed(() -> mImageView1.setImageDrawable(gifDrawable1),2000);
            final GifDrawable gifDrawable2 = new GifDrawable(App.getInstance().getAssets(),"gif.gif");
            findViewById(R.id.img2).postDelayed(() -> mImageView2.setImageDrawable(gifDrawable2),4000);`

**This is the layout.**
`<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">


    <pl.droidsonroids.gif.GifImageView
        android:id="@+id/img"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_gravity="right"
        android:gravity="center"
        android:visibility="visible"
         />

    <pl.droidsonroids.gif.GifImageView

        android:id="@+id/img1"
        android:layout_width="0dp"
        app:layout_constraintTop_toBottomOf="@+id/img"
        android:layout_height="wrap_content"
        android:layout_gravity="right"
        android:gravity="center"
        android:visibility="visible"
        />

    <pl.droidsonroids.gif.GifImageView
        android:id="@+id/img2"
        android:layout_width="0dp"
        app:layout_constraintTop_toBottomOf="@+id/img1"
        android:layout_height="wrap_content"
        android:layout_gravity="right"
        android:gravity="center"
        android:visibility="visible"
        />





</android.support.constraint.ConstraintLayout>`

**Comment by kaershushu** [comment]
**This is java code.**

    final GifDrawable gifDrawable = new GifDrawable(App.getInstance().getAssets(),"gif.gif");
    findViewById(R.id.img).postDelayed(() -> mImageView.setImageDrawable(gifDrawable),300);
    
    final GifDrawable gifDrawable1 = new GifDrawable(App.getInstance().getAssets(),"gif.gif");
    findViewById(R.id.img1).postDelayed(() -> mImageView1.setImageDrawable(gifDrawable1),2000);
    
    final GifDrawable gifDrawable2 = new GifDrawable(App.getInstance().getAssets(),"gif.gif");
    findViewById(R.id.img2).postDelayed(() -> mImageView2.setImageDrawable(gifDrawable2),4000);
![This is the layout.](https://user-images.githubusercontent.com/2417202/46986148-6b0d6a00-d120-11e8-9ab2-1156a331b1b2.jpeg)

**Comment by kaershushu** [comment]
![g](https://user-images.githubusercontent.com/2417202/46997455-521dac80-d152-11e8-9628-749101fb9722.gif)

maybe this gif is more clear.
