### ISSUE TITLE
Flashing

### ISSUE THREAD

**Issue by ming838395826** [koral--/android-gif-drawable#604]
i use it  for my project The size of GIF is 2M and it always flashing  why? i use it in fragment
GifDrawable gifFromResDrawable = new GifDrawable(getResources().getAssets(), "test.gif");
mGifView.setImageDrawable(gifFromResDrawable);

**Comment by koral--** [comment]
Is it the same issue as https://github.com/koral--/android-gif-drawable/issues/267#issuecomment-206962158 ?

**Comment by ming838395826** [comment]
![test](https://user-images.githubusercontent.com/12120962/47761522-a3ea3900-dcf3-11e8-9a8c-bcc3d5098838.gif)
this dimensions is 522*564px,and i see the comment ,and try to set android:hardwareAccelerated="false" or true. but it still flashing.is this gif too big? if work in surfaceview ,Will it be better?have some way to work in surfaceview?

**Comment by koral--** [comment]
Yeah, it looks like too much data for drawable. You can find example with SurfaceView in sample project. Another simpler option is `GifTextureView`. Here is sample project: https://github.com/koral--/android-gif-drawable/tree/dev/sample/src/main/java/pl/droidsonroids/gif/sample
