### ISSUE TITLE
Animation not starting?

### ISSUE THREAD

**Issue by mario** [koral--/android-gif-drawable#61]
Using ProGuard, and have -keep public class pl.droidsonroids.gif.GifIOException{*;} as suggested.

**Comment by liufsd** [comment]
@mario 
@koral-- 
Hi. not working with Dexguard.
How to fix it ?
I have add this :

#droidsonroids gif
-keep public class pl.droidsonroids.gif.GifIOException{<init>(int, java.lang.String);}
-keep public class pl.droidsonroids.gif.GifInfoHandle{<init>(long,int,int,int);}

**Comment by koral--** [comment]
I would ask dexguard support.

**Comment by mario** [comment]
This includes some additional stuff, but it works ;)

-keepresourcexmlattributenames **pl.droidsonroids.gif.GifImageView/*

-keep,allowshrinking class pl.droidsonroids.gif.**

-keep class pl.droidsonroids.gif.GifIOException {
    <init>(int);
}

-keepclassmembers class * {
    int descriptor;
}

-keepclassmembers class * {
    void mark(int);
    int read(byte[], int, int);
    void reset();
    void close();
}

-keep class org.sqlite.** {
  public protected private *;
}

-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int i(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
}

-keepclassmembers public class * extends android.view.View {
   void set*(***);
   *** get*();
}

-adaptresourcefilecontents **/*.xml

**Comment by liufsd** [comment]
wow, thanks. i test it now.

**Comment by liufsd** [comment]
I have use GifTextView, and set background on xml. only work not use dexguard or proguard. 
So ,i think the problem maybe is 'keepresourcexmlattributenames' ?
@mario @koral--

**Comment by mario** [comment]
This works 100% :)

For build.gradle, make sure that you add the necessary configuration from the DexGuard manual > Gradle build; notably the default configuration.

**Comment by liufsd** [comment]
ok, i will clean it , and build again.

**Comment by liufsd** [comment]
# Android-gif-drawable.
-dontnote pl.droidsonroids.gif.GifImageView
-keep,allowshrinking class pl.droidsonroids.gif.GifImageView

-dontnote pl.droidsonroids.gif.GifTextView
-keep,allowshrinking class pl.droidsonroids.gif.GifTextView

-dontnote pl.droidsonroids.gif.GifIOException
-keep class pl.droidsonroids.gif.GifIOException{*;}

-dontnote pl.droidsonroids.gif.GifInfoHandle
-keep class pl.droidsonroids.gif.GifInfoHandle {
    <init>(long,int,int,int);
}
-keepresourcexmlattributenames **pl.droidsonroids.gif.GifTextView/*
-keepresourcexmlattributenames **pl.droidsonroids.gif.GifImageView/*

-keep,allowshrinking class pl.droidsonroids.gif.**

-keepclassmembers class * {
int descriptor;
}

**Comment by liufsd** [comment]
Not working.
Sorry.

**Comment by liufsd** [comment]
<com.demo.widget.CustomTextView
            android:id="@+id/tv_chatcontent"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@drawable/live_bubble_txt_otherside_selecter"/>


CustomTextView extends GifTextView

**Comment by liufsd** [comment]
which  gif library version do you used ?

**Comment by liufsd** [comment]
oh,yes .done. work now.
i have move the configs to dexguard.txt , not in proguard.txt.

**Comment by mario** [comment]
Of course :)

**Comment by liufsd** [comment]
Thanks~>~ 
Good night.

**Comment by mario** [comment]
Night

**Comment by FelipeGAlmeida** [comment]
Sorry be commenting here but, @mario or @koral--  could you please share the configuration that worked with DexGuard?

> I'm using like this:
   <pl.droidsonroids.gif.GifImageView
            android:layout_width="45dp"
            android:layout_height="45dp"
            android:layout_gravity="center_vertical"
            android:layout_marginEnd="24dp"
            android:src="@raw/gif_connecting" />

I think the above configurations missed some characters due to the GitHub Markdown styling.
Also, it would be nice if these configs were added in a dexguard.txt file. I tryed the [consumer configuration](https://github.com/koral--/android-gif-drawable/blob/dev/android-gif-drawable/consumer-proguard-rules.pro) but with no success.

Thanks in advance.

**Comment by koral--** [comment]
I haven't participated in this issue except directing OP to dexguard support.
Feel free to create a PR with dexguard.txt

**Comment by FelipeGAlmeida** [comment]
Ok, thanks, I'll contact them
