### ISSUE TITLE
How I can get event When GifImageView finished?

### ISSUE THREAD

**Issue by thangkho** [koral--/android-gif-drawable#620]
I used:
` <pl.droidsonroids.gif.GifImageView
        android:id="@+id/gifImg"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/color_white"
        android:src="@drawable/splash"
        app:loopCount="1" />` 
I need check when gif run finished to next activity.
I see in your document have isRunning() method but I can't implement it.
How I can't do it?
p/s now I use handler to next activity but some time it working not perfect.

**Comment by Glennmen** [comment]
You can use the AnimationListener (I haven't used it myself) but you will need to add the GifDrawable to your GifImageView in code, not XML:

```java
gifDrawable.addAnimationListener(new AnimationListener() {
                        @Override
                        public void onAnimationCompleted(int loopNumber) {
                            //run code
                        }
                    });
```

**Comment by koral--** [comment]
It's correct that you can use `AnimationListener`. See sample project: https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/AnimationControlFragment.kt

However, you don't need to assign drawable in java/kotlin code. You can leave your XML as is and only get drawable in code: https://github.com/koral--/android-gif-drawable/blob/master/sample/src/main/java/pl/droidsonroids/gif/sample/AnimationControlFragment.kt#L36

**Comment by thangkho** [comment]
@Glennmen  tks you so much. I did it!
