### ISSUE TITLE
Does this library work fine with apps targeting Android Oreo?

### ISSUE THREAD

**Issue by rk8339811** [koral--/android-gif-drawable#622]
Hi am pretty new to Android development and I am planning to update the `TargetSdkVersion `of my app to Android Oreo due to the new Play Store compliance which requires an app to target Android Oreo to update the app in the Play Store.

I think one of the changes in Android Nougat is that the App should pack its NDK libraries within the app APK.

I think(but not sure) that this library uses NDK libraries.

Hence does this library work with app targeting Android Oreo.

This is how I am importing the library

`compile 'pl.droidsonroids.gif:android-gif-drawable:1.1.+'`

I know the best option would be to try it myself but I am not sure how it would respond in different devices running on the same Android version. Hence any clarification would be really grateful.

I have been using this library and love its utility. Thanks for the library!.

**Comment by koral--** [comment]
Native libraries produced by NDK are by default packed with your app.

**Comment by rk8339811** [comment]
@koral-- Thanks for the clarification.
