### ISSUE TITLE
clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by wsch88888** [koral--/android-gif-drawable#625]
when i try to build apk by andorid studio with the latest sample code,i got the message:

* What went wrong:
Execution failed for task ':android-gif-drawable:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\LaoC\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\AndroidStudioProjects\android-gif-drawable\android-gif-drawable\.externalNativeBuild\cmake\debug\x86 --target pl_droidsonroids_gif}
  [1/1] Linking C shared library D:\AndroidStudioProjects\android-gif-drawable\android-gif-drawable\build\intermediates\cmake\debug\obj\x86\libpl_droidsonroids_gif.so
  FAILED: cmd.exe /C "cd . && C:\Users\LaoC\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe  --target=i686-none-linux-android --gcc-toolchain=C:/Users/LaoC/AppData/Local/Android/Sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/LaoC/AppData/Local/Android/Sdk/ndk-bundle/sysroot -fPIC -isystem C:/Users/LaoC/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=17 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c11 -Weverything -Wall -DNDEBUG -Os -g0 -fvisibility=hidden -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a --sysroot C:/Users/LaoC/AppData/Local/Android/Sdk/ndk-bundle/platforms/android-17/arch-x86 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libpl_droidsonroids_gif.so -o D:\AndroidStudioProjects\android-gif-drawable\android-gif-drawable\build\intermediates\cmake\debug\obj\x86\libpl_droidsonroids_gif.so CMakeFiles/pl_droidsonroids_gif.dir/bitmap.c.o CMakeFiles/pl_droidsonroids_gif.dir/control.c.o CMakeFiles/pl_droidsonroids_gif.dir/decoding.c.o CMakeFiles/pl_droidsonroids_gif.dir/dispose.c.o CMakeFiles/pl_droidsonroids_gif.dir/drawing.c.o CMakeFiles/pl_droidsonroids_gif.dir/exception.c.o CMakeFiles/pl_droidsonroids_gif.dir/gif.c.o CMakeFiles/pl_droidsonroids_gif.dir/giflib/dgif_lib.c.o CMakeFiles/pl_droidsonroids_gif.dir/giflib/gifalloc.c.o CMakeFiles/pl_droidsonroids_gif.dir/giflib/openbsd-reallocarray.c.o CMakeFiles/pl_droidsonroids_gif.dir/init.c.o CMakeFiles/pl_droidsonroids_gif.dir/jni.c.o CMakeFiles/pl_droidsonroids_gif.dir/metadata.c.o CMakeFiles/pl_droidsonroids_gif.dir/opengl.c.o CMakeFiles/pl_droidsonroids_gif.dir/surface.c.o CMakeFiles/pl_droidsonroids_gif.dir/time.c.o  -ljnigraphics -landroid -lGLESv2 -llog -lm && cd ."
  CMakeFiles/pl_droidsonroids_gif.dir/gif.c.o:D:\AndroidStudioProjects\android-gif-drawable\android-gif-drawable\src\main\c\gif.c:function Java_pl_droidsonroids_gif_GifInfoHandle_openFile: error: undefined reference to 'stat64'
  CMakeFiles/pl_droidsonroids_gif.dir/gif.c.o:D:\AndroidStudioProjects\android-gif-drawable\android-gif-drawable\src\main\c\gif.c:function Java_pl_droidsonroids_gif_GifInfoHandle_openNativeFileDescriptor: error: undefined reference to 'fstat64'
  clang.exe: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
38 actionable tasks: 4 executed, 34 up-to-date

**Comment by koral--** [comment]
Which NDK version are you using?

**Comment by wsch88888** [comment]
NDK vertion used to be 15.2.4203891,then i found the update.after i update NDK to the latest vertion(18.1.5063045),all problems are done.
Thank you so much!!!!
