### ISSUE TITLE
GifTextureView play very slow than its original speed.

### ISSUE THREAD

**Issue by manish9161** [koral--/android-gif-drawable#628]

**Comment by koral--** [comment]
Could you attach affected GIF here?

**Comment by manish9161** [comment]
Hello 

I have checked with sample application also.
In GifImageView play with gliches. 
In GifTextureView play slow.

Please refer following link for GIF :

https://drive.google.com/open?id=1HMIYFjTpEQ25r_Fx2PsFwsFiMJcsyZVk

https://drive.google.com/open?id=1Gkwxq2cKHeCvrcZTYrXE3jQYgOx7TaBA

Thanks

**Comment by koral--** [comment]
OK, thanks. I'll check that.

**Comment by koral--** [comment]
There is no silver bullet for cases like this.
You can try `GifTexImage2D` and `GLSurfaceView` to increase framerate.

In general this library decodes subsequent GIF frames when they are needed without buffering so memory consumption is lower but performance is worse in comparison with frames buffering.
