### ISSUE TITLE
Maven build with c++_shared STL

### ISSUE THREAD

**Issue by VladOstrovski** [koral--/android-gif-drawable#634]
If you got more than one native lib in your app, you have to use a shared STL lib. By default (and with the current library cmake config) it's being build with a static one.
I've built the library with c++_shared STL myself and all is working well. But I think users will benefit from pulling a shared version from maven. (proper library updates and versioning etc..).

It basically sums up to adding this to the build file:
`cmake {
...
                arguments "-DANDROID_STL=c++_shared"
...
			}`

You can read here why it is needed:
https://developer.android.com/ndk/guides/cpp-support

What do you think?

**Comment by VladOstrovski** [comment]
It's more of a request than a question.

**Comment by koral--** [comment]
Could you elaborate on that? There is no C++ code in this library. So it seems that setting STL to `none` is the best option.

**Comment by VladOstrovski** [comment]
You might be right. I didn't think this through.. I guess the standard c stuff are not implemented in the STL

**Comment by koral--** [comment]
Sorry for my slow responsiveness. 
So it seems that we should change STL to `none`. I'll apply this change ASAP.
