### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "app_lib/libpl_droidsonroids_gif.so1.2.15" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by cfJand** [koral--/android-gif-drawable#636]
hi:
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.baiwan.pk/app_lib/libpl_droidsonroids_gif.so1.2.15" is 32-bit instead of 64-bit
    at java.lang.Runtime.load(Runtime.java:332)
    at java.lang.System.load(System.java:1069)
    at pl.droidsonroids.gif.ReLinker.loadLibrary(ReLinker.java:59)
    at pl.droidsonroids.gif.LibraryLoader.loadLibrary(LibraryLoader.java:50)
    at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:25)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:158)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:158)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:93)
    at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:93)
    at com.xgame.home2.views.GamesNoticeView.setGifInNotice(GamesNoticeView.java:59)

**Comment by koral--** [comment]
What is the device model and Android version?
Are you using app bundles?

**Comment by gauravg2606** [comment]
@koral-- I was also facing the same issue https://github.com/koral--/android-gif-drawable/issues/649
and no we r not using app bundle and also we added this through gradle dependency
`    implementation "pl.droidsonroids.gif:android-gif-drawable:1.2.16"
`
It is occuring on various number of devices, not only on some specifici one and on various android versions, 6, 8.

**Comment by koral--** [comment]
Could you point out few devices and Android versions?

**Comment by gauravg2606** [comment]
@koral--  few device which i'm seeing of fabrics have most of the crashes
GIONEE F103 PRO , OS = 6, 8
GIONEE S Plus, OS = 6
INTEX Aqua Strong 5.1 
LAVA X81
and there are also some lenevo and other devices as well.

**Comment by koral--** [comment]
Thanks, I'll try to repro that.
In the meantime, could you try setting `android:extractNativeLibs` to `false`?
Documentation: https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs
Possible side effects: https://stackoverflow.com/questions/42998083/setting-androidextractnativelibs-false-to-reduce-app-size

**Comment by gauravg2606** [comment]
@koral-- As we cannot go with increase in apk size of app, is there any other workaround to fix ?

**Comment by gauravg2606** [comment]
@koral-- hey buddy, any update with the issue, crashes are increasing for our application

**Comment by gauravg2606** [comment]
@cfJand hey buddy, have u found any solution for this issue ?? it'll great if u can share it.

**Comment by koral--** [comment]
I've found possible solution. I'll push a snapshot version ASAP.

**Comment by koral--** [comment]
I could not reproduce this issue, but possible fix is available in version `1.2.17-SNAPSHOT`.

**Comment by tibbi** [comment]
1.2.17-SNAPSHOT is not found, do I need to change anything else?

**Comment by koral--** [comment]
It is located on maven snapshot repo: https://github.com/koral--/android-gif-drawable#gradle-snapshot-repository

**Comment by koral--** [comment]
Sorry my slowness. Version 1.2.17 has just been released to maven central
