### ISSUE TITLE
Help with reset method

### ISSUE THREAD

**Issue by Zaffner** [koral--/android-gif-drawable#638]
I'm pretty new with Android programming, and I've ran into a problem concerning the reset() method. Since I'm not very familiar with the language I've had a hard time figuring out a solution to this problem. 

So i have a animation (gif) that i want to reset by pressing a button. I figured this might work by giving the button onClick property in my xml page linking it to a method called resetAnimation (see code below)

```
public void resetAnimation(android.view.View v){

    }
```

This is said in the github: "GifDrawable implements an Animatable and MediaPlayerControl so you can use its methods and more:" and "reset() - rewinds the animation, does not restart stopped one" how do i call reset()?

These are my imports:

```
import androidx.appcompat.app.AppCompatActivity;

import pl.droidsonroids.gif.GifDrawable;
import pl.droidsonroids.gif.AnimationListener;
import pl.droidsonroids.gif.GifImageView;

import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.drawable.Animatable;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.MediaController;
import android.widget.TextView;
import java.util.Calendar;
import java.sql.Time;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;
```

**Comment by koral--** [comment]
Just call `reset()` on `GifDrawable` instance which you want to reset. You can obtain it using `getDrawable()` or `getBackground()` if it is set in XML.

**Comment by Zaffner** [comment]
I'm very sorry but my knowledge in java isn't good enough to fully understand what you mean. Could you be so nice and explain a bit more thoroughly. Maybe with some code example?

**Comment by Zaffner** [comment]
For reference, this is the xml for the specific button:

```
<pl.droidsonroids.gif.GifImageView
                android:id="@+id/poof"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:onClick="resetAnimation"
                android:scaleType="centerCrop"
                android:src="@drawable/poofonce" />
```

And the full code:

```
package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;

import pl.droidsonroids.gif.GifDrawable;
import pl.droidsonroids.gif.AnimationListener;
import pl.droidsonroids.gif.GifImageView;

import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.drawable.Animatable;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.MediaController;
import android.widget.TextView;
import java.util.Calendar;
import java.sql.Time;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;


public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Calendar calendar = Calendar.getInstance();
        Calendar time = Calendar.getInstance();
        SimpleDateFormat mdformat = new SimpleDateFormat("HH:mm");
        String strDate = mdformat.format(calendar.getTime());
        String currentDate = DateFormat.getDateInstance().format(calendar.getTime());

        TextView textViewdate = findViewById(R.id.text_view_date);
        textViewdate.setText(currentDate+", kl "+strDate);

        SharedPreferences prefs = getSharedPreferences("MY_DATA",MODE_PRIVATE);

        String namn2 = prefs.getString("MY_NAME", "inget namn");
        String med2 = prefs.getString("MY_MED","inget meddelande");
        int nummer2 = prefs.getInt("MY_TEL",0);
        int summa2 = prefs.getInt("MY_SUMMA", 0);

        ((TextView)findViewById(R.id.outputNamn)).setText(namn2);
        ((TextView)findViewById(R.id.outputMed)).setText(med2);
        ((TextView)findViewById(R.id.outputNummer)).setText(nummer2+"");
        ((TextView)findViewById(R.id.outputSumma)).setText(summa2+" kr");

    }

    public void page(android.view.View v){
        startActivity(new Intent(getApplicationContext(),SecondActivity.class));
    }

    public void resetAnimation(android.view.View v){


    }



}
```

So my plan is whenever the button is clicked i want it to use the method resetAnimation and reset the gif.

**Comment by koral--** [comment]
Could you create a repository with minimal project which reproduces your issue?
Your snippets don't show in which view you have GifDrawable.

**Comment by Zaffner** [comment]
It should be posted now on my profile (note: this is my first time posting a repository). 

Link: https://github.com/Zaffner/HelpNeeded

**Comment by Zaffner** [comment]
Okay, I've done some more testing and researching, it seems like i should have something like this:

```
public void resetAnimation(android.view.View n) {

        GifDrawable reset = new GifDrawable();
        reset.reset();

    }
```

However this gives me a red error under () saying "Cannot resolve constructor 'GifDrawable()'"

**Comment by koral--** [comment]
You need something like this:
`GifDrawable reset = (GifDrawable) ((ImageView) n).getDrawable();`

**Comment by Zaffner** [comment]
Cheers, that's one step forward. One problem is that it restart the whole app now.

**Comment by Zaffner** [comment]
I assume it should be like this:

```
    public void resetAnimation(android.view.View n) {

        GifDrawable reset = (GifDrawable) ((ImageView) n).getDrawable();

        reset.reset();

    }

```

**Comment by Zaffner** [comment]
Could it be messing up since the gif is in the xml file? If i've understood it correctly the reset() method needs something to reset, correct?

**Comment by koral--** [comment]
> One problem is that it restart the whole app now, not just the specific gif.

I don't understand what do you mean by `restart the whole app`.

> I assume it should be like this:

Correct.

> Could it be messing up since the gif is in the xml file? 

I don't understand what is messed up.

> If i've understood it correctly the reset() method needs something to reset, correct?

Correct you need to have a drawable instance. That one which you want to reset.

**Comment by Zaffner** [comment]
I'm not sure if it crashes or just refreshes everything and sends me to my first page SecondActivity but it doesn't just refresh the specific gif. 

How to i create the drawable instance? Is it just: 

```
`GifDrawable reset = (GifDrawable) ((ImageView) n).getDrawable();
` 
``` ?
Don't i need to give the code the specific name of the gif I want it to refresh?

**Comment by Zaffner** [comment]
This is what it looks like:

https://imgur.com/4GBxkyc

My plan is to have the exploding particle gif (poofonce.gif) refresh when i press it. However now it refreshes everything or crashes.

**Comment by koral--** [comment]
Sorry, it should be background, not drawable.

`GifDrawable reset = (GifDrawable) ((ImageView) n).getBackground();`

**Comment by Zaffner** [comment]
Cheers mate, thanks a lot! Works flawlessly now
