### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by davidmind** [koral--/android-gif-drawable#646]
Hi @MichaelEvans @Wavesonics @mmin18 I am a graphics designer, I will like to know if you want me to create a new logo for your project.

**Comment by koral--** [comment]
You are welcome to submit a PR with logo.

**Comment by davidmind** [comment]
Ok, I will go and work on my sketch while I give you feed back.

**Comment by davidmind** [comment]
@koral-- after making my sketch this what I later come up with, you are free to make suggestion on color an design. And if you like it, please let me know the color you want so that I can proceed to make different icon sizes.
![PRESENTATION-2-1.png](https://cdn.steemitimages.com/DQmS9GL2vEHCyoNSSe1LPkRPMCoRZDC37ntxrsX2MGNipf5/PRESENTATION-2-1.png)

**Comment by koral--** [comment]
Looks very good :)
I would go with option 1.

**Comment by Wavesonics** [comment]
looks nice, I also like option 1 FWIW

**Comment by davidmind** [comment]
Am glad you like it, I will make all necessary size for option 1 and make a pull request. I will also submit a link to all vector file.

**Comment by davidmind** [comment]
@koral--  I have made a pull request and this is a link to all the editable files **[ Here](https://drive.google.com/folderview?id=1kSgyDm56J7dLehk3L8lTE8Jd5zrg4u8-)**

**Comment by koral--** [comment]
PR merged, thanks!
