### ISSUE TITLE
How to make gif animation

### ISSUE THREAD

**Issue by hafiz013** [koral--/android-gif-drawable#647]
My question is that how to make animation gift (before click button) and another animation gift (after click button) presume that i have two gift first i make background (first gift) then after click i change background to second gift

**Comment by koral--** [comment]
If I understand correctly, you need to just change drawable and/or background resource to the second drawable. Use setBackgroundResource method.

**Comment by hafiz013** [comment]
I did change background resources but the animations (gif) stop play after change. Please help me..

**Comment by koral--** [comment]
Could you attach your code snippet?

**Comment by hafiz013** [comment]
Below here code xml :

`<pl.droidsonroids.gif.GifTextView
        android:id="@+id/btnBid"
        android:layout_width="25dp"
        android:layout_height="25dp"
        android:layout_marginRight="45dp"
        android:layout_marginTop="5dp"
        android:background="@drawable/ic_coin"
        app:layout_constraintTop_toTopOf="@+id/layoutBtm"
        app:layout_constraintEnd_toEndOf="parent" />`

java code sample as following below : -

`btnBid = v.findViewById(R.id.btnBid);
        //btnBid.setGifFromResource(R.mipmap.btn_bid1);
        btnBid.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getAction() == MotionEvent.ACTION_BUTTON_PRESS || event.getAction() == MotionEvent.ACTION_DOWN) {          
                    btnBid.setBackground(ContextCompat.getDrawable(context, R.mipmap.btn_bid2));             
                }else if(event.getAction() == MotionEvent.ACTION_BUTTON_RELEASE || event.getAction() == MotionEvent.ACTION_UP){                   
                    btnBid.setBackground(ContextCompat.getDrawable(context, R.mipmap.btn_bid1));        
                }
                return false;
            }
        });`

as alternative I try drawable selector : -

`<?xml version="1.0" encoding="utf-8"?>
  <item android:drawable="@drawable/btn_bid2" android:state_selected="true"></item>
    <item android:drawable="@drawable/btn_bid2" android:state_pressed="true"></item>
    <item android:drawable="@drawable/btn_bid1"></item>`

both way work like charm change background however, it stop play gif once change background.
I also attach two file gif for u reference.
![btn_bid1](https://user-images.githubusercontent.com/6707224/56481235-b1d58580-64f0-11e9-82cd-6a3774054889.gif)
![btn_bid2](https://user-images.githubusercontent.com/6707224/56481239-b863fd00-64f0-11e9-8536-3ad37c63a01d.gif)

**Comment by koral--** [comment]
`ContextCompat.getDrawable`
will return (not animated) `BitmapDrawable` from GIF files.
You have to replace:
`btnBid.setBackground(ContextCompat.getDrawable(context, <id>));`
with
`btnBid.setBackgroundResource(<id>);

**Comment by hafiz013** [comment]
Actually, u are worng because setbackground still can but other way around to do it. Below here sample code fix for my issue :

First create giftDrawable :  

` GifDrawable gifDrawable1 = new GifDrawable(getResources(), R.mipmap.btn_biddes);
   GifDrawable gifDrawable2 = new GifDrawable(getResources(), R.mipmap.btn_biddes2);`

Then, replacing background here:

`btnBid.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getAction() == MotionEvent.ACTION_BUTTON_PRESS || event.getAction() == MotionEvent.ACTION_DOWN) {
                    // Here I would like to stop the animation
                    // I want to display the same image but without animating
                    btnBid.setBackground(gifDrawable2);

                }else if(event.getAction() == MotionEvent.ACTION_BUTTON_RELEASE || event.getAction() == MotionEvent.ACTION_UP){
                    btnBid.setBackground(gifDrawable1);
                }
                return false;
            }
        });`

That's all work like charm.
