### ISSUE TITLE
Add synchronized seekTo() method

### ISSUE THREAD

**Issue by marcin-adamczewski** [koral--/android-gif-drawable#650]
Hi @koral-- 

First off, thanks for the lib

I'd need to be able to synchronously seek to some specific time.
Currently, there is the `seekTo(position)` method however, it seeks asynchronously. 
I could use `seekToPositionAndGet` but it unnecessarily creates bitmaps which in my case might cause memory issue.

Here is the specific case why I need it. Basically, I have a bunch of gifs and images which I compose final gif from. So I iterate over those items and draw them for each frame like this:

```
  finalStickers.forEach { entity ->
            if (entity is GifEntity) {
                entity.gifDrawable.seekTo((frameMs % entity.gifDrawable.duration).toInt())
            }
            entity.draw(canvas) // when drawing here, gif might not be seeked yet
        }
```

If you have no time I can create PR.

EDIT
Actually I've just created one
https://github.com/koral--/android-gif-drawable/pull/651

**Comment by koral--** [comment]
PR merged, thanks.
