### ISSUE TITLE
[Security] Static Scan Issues

### ISSUE THREAD

**Issue by KumariAnjuThakur** [koral--/android-gif-drawable#656]
Hi 
We are facing the following issues in this library in static security scan :
Vera Code : 
Incorrect Permission for critical resources

MobSF Scan :
The App uses Java Hash Code. It's a weak hash function and should never be used in Secure Crypto

Could you guys help us to resolve these issues.

**Comment by koral--** [comment]
Could you post more info what is your use case and what to you want to achieve?

`Incorrect Permission for critical resources`
What permission and what resources?

`The App uses Java Hash Code. It's a weak hash function and should never be used in Secure Crypto`
This library does not use hash code for any "crypto".

**Comment by KumariAnjuThakur** [comment]
Hi Koral
Thanks for responding !!!
We are running a static security scan on our application using various software and trying to resolve the security flaws.

Incorrect Permission for critical resources
What permission and what resources? >>> We cannot tell what permission exactly you are using but for your reference, I am attaching screenshots for both the issues. 
Please have a look and help us to resolve these issues.

![hash](https://user-images.githubusercontent.com/11975990/56941029-61cd7300-6b2f-11e9-9323-69c89413f0ee.PNG)
![critical resource](https://user-images.githubusercontent.com/11975990/56941036-6bef7180-6b2f-11e9-8d83-4b4116f61912.png)

Thanks in Advance.

**Comment by koral--** [comment]
Regarding `hashCode`, it is used here: https://github.com/koral--/android-gif-drawable/blob/dev/android-gif-drawable/src/main/java/pl/droidsonroids/gif/MultiCallback.java
`equals()` is overridden on purpose, so `hashCode()` also should be.

Regarding permissions I guess that it is triggered by this method: https://github.com/koral--/android-gif-drawable/blob/dev/android-gif-drawable/src/main/java/pl/droidsonroids/gif/ReLinker.java#L189
It is also intended workaround for native library loading issues, executed only when normal way fails.
More info here: https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db
Workaround sets the same file permissions as package installer.

It seems that none of those warnings can be avoided. However, if you any ideas about that feel free to submit a PR.
