### ISSUE TITLE
Animation is not playing after returning from another activity. 

### ISSUE THREAD

**Issue by alla-dubovska** [koral--/android-gif-drawable#660]
I use `GifTextureView` to display animation from file like this:

`readmojiView.setInputSource(InputSource.FileSource(file))`

But when open a new ativity and then return back to first one animation view is empty.

**Comment by koral--** [comment]
Sorry for the long delay, but I could not reproduce that.
Could provide a complete sample project which reproduces this issue?

**Comment by koral--** [comment]
Closing due to lack of steps to reproduce.
