### ISSUE TITLE
Arm 64 bit native libs required according to https://developer.android.com/distribute/best-practices/develop/64-bit

### ISSUE THREAD

**Issue by gouravd** [koral--/android-gif-drawable#661]

**Comment by koral--** [comment]
Native libraries for all supported platforms are present in AAR.
What is your issue?

**Comment by vandep** [comment]
AAR just contains armeabi-v7a, need add  arm64-v8a to compliance google play

**Comment by koral--** [comment]
Where do you find AAR without `arm64-v8a`?

**Comment by vandep** [comment]
my fault，I didn't investigate it carefully

**Comment by koral--** [comment]
OK, so I'm closing this issue.
