### ISSUE TITLE
Do you have any plan for supporting arm64-v8a?

### ISSUE THREAD

**Issue by liuyx** [koral--/android-gif-drawable#662]

**Comment by koral--** [comment]
arm64-v8a is supported. 
What is your issue?

**Comment by courseIcan** [comment]
> arm64-v8a is supported.
> What is your issue?

Google Play needs 64-bit version.

**Comment by courseIcan** [comment]
> arm64-v8a is supported.
> What is your issue?

![image](https://user-images.githubusercontent.com/8438338/59319918-fe725b80-8cfe-11e9-939c-3f65992c618f.png)
Now only 64-bit version of .so files are available.

**Comment by koral--** [comment]
This library (and maven artifacts published on Maven Central) provides .so files for all architectures supported by current NDK version: armeabi-v7a, arm-64-v8a, x86 and x86_64.
If you are using maven/gradle dependency and don't have all of them in your APK it seems that something is preventing keeping them eg. `abiFilters` in your `build.gradle`.
