### ISSUE TITLE
Gifdecoder decoder wrong frame

### ISSUE THREAD

**Issue by iBotasky** [koral--/android-gif-drawable#663]
@Wavesonics 
Hi, I use `GifDecoder` to decoder the frames of a gif file.
Bug some of frames are wrong except the first frame.
I got not idea to solve this problem, How can i solve this?
This is first frame is correct.
![WX20190617-162954](https://user-images.githubusercontent.com/13627665/59590115-ea26c800-911d-11e9-992a-2b150b4390ef.png)
And the other is wrong:
![WX20190617-163017](https://user-images.githubusercontent.com/13627665/59590201-19d5d000-911e-11e9-9db1-5fc97ad9103a.png)

This is one of the gif resource. I got many gif file occur this issue.
![20190515878515_JpuYKd](https://user-images.githubusercontent.com/13627665/59590298-4ee22280-911e-11e9-9c60-2d37d7028740.gif)

And here is my code:
```kotlin
                    val path = fileParsePath + File.separator + String.format("%02d", i) + ".png"
                    val outputStream = FileOutputStream(path)
                    val frame = Bitmap.createBitmap(gifDecoder.width, gifDecoder.height, Bitmap.Config.ARGB_8888)
                    gifDecoder.seekToFrame(i, frame)
                    framesDurationList.add(gifDecoder.getFrameDuration(i))
                    frame.compress(Bitmap.CompressFormat.PNG, 100, outputStream)
                    outputStream.flush()
                    outputStream.close()
```

**Comment by koral--** [comment]
It looks like the first frame uses `None` vel `as is` disposal method (see http://www.imagemagick.org/Usage/anim_basics/#none for more info).
In such case 2nd frame retrieved in your way is only a difference between 1st and 2nd frame in GIF file.

To retrieve a "full" 2nd frame you need to use the same bitmap for both `seekToFrame` calls. Eg. declare bitmap before loop.

**Comment by iBotasky** [comment]
@koral-- 
WaWo~
Thanks a lot.
This method is solve my issue though I don't know the detail of a gif file.
Thanks.
