### ISSUE TITLE
Error 107 on constructor for some gif

### ISSUE THREAD

**Issue by Hobyrr** [koral--/android-gif-drawable#667]
I made some gifs with Giffle, and for some of them, i got error 107 when i tried to put them in a GifDrawable: 
![image](https://user-images.githubusercontent.com/37924392/61870785-43cd9f80-aedf-11e9-97ad-5fe0effd80f7.png)

Where fd is a FileDescriptor. I tried to put the gif in R.drawable but i got the same error... Any idea ?

**Comment by koral--** [comment]
Could you attach that GIF here (or sent me via email if it is private)?

**Comment by Hobyrr** [comment]
Nothing to hide ! Here it is ! 
![htextview_evaporate_mt](https://user-images.githubusercontent.com/37924392/61874826-a330ad00-aee9-11e9-802f-4f3bc1048b72.gif)

**Comment by Hobyrr** [comment]
Nothing to hide ! Here it is : 

Well, i tried some things, and i got that : I used exactly the same code to create this 2 gifs, I just changed the text. The first one cannot be disassemble, but the second have no problem............. I tryed to remake 5 time each gif, never got another result...


![line_mt2](https://user-images.githubusercontent.com/37924392/61877431-4a641300-aeef-11e9-991e-27bd9e7f70ac.gif)
![line_mt](https://user-images.githubusercontent.com/37924392/61877433-4a641300-aeef-11e9-8164-e51ab956b1f3.gif)

**Comment by koral--** [comment]
Thanks, I'll check that.

**Comment by koral--** [comment]
The first GIF contains record of type `0x00` which is unknown. Currently if such record is encountered, further file reading is stopped.
Most of the GIF viewers I've tried do the same.
However, if we ignore that record then next frames can be read normally. It should be easy to add handling of such case.
