### ISSUE TITLE
Making mBuffer protected

### ISSUE THREAD

**Issue by marcin-adamczewski** [koral--/android-gif-drawable#668]
Hi :)

I have a feature in the app the combines video with GIF. So for each video frame I fetch appropriate GIF frame by seeking GifDrawable and calling `getCurrentFrame()` method and I combine it with the video frame.
Unfortunately for this case, the `getCurrentFrame()` method creates a new Bitmap every time.
It'd like to be able to use my Bitmap from some BitmapPool to create current frame Bitmap.
It would let me avoid constantly creating and releasing new Bitmaps.

In order to achieve that I extended GifDrawable class and overridden `getCurrentFrame(): Bitmap` method. Unfortunately, there is no access to `mBuffer: Bitmap` field as it is private.

Would it be possible making it protected? I can create PR if you don't mind.

So I would override it in such way:

```
  override fun getCurrentFrame(): Bitmap {
        val currentFrame = pool.getBitmap()
        Canvas(currentFrame).run { drawBitmap(mBuffer, 0, 0, mPaint) }
        return currentFrame
    }
```

**Comment by koral--** [comment]
For now `mBuffer` in `GifDrawable` is an implementation detail and is private on purpose. It is used in many places including recycling in another `GifDrawable` instance. If it is modified in a wrong way many things may break.

I don't know what is your use case, but there is `GifDecoder` which allows to provide own Bitmaps.

**Comment by marcin-adamczewski** [comment]
I understand that exposing `mBuffer` might be risky. 
I've checked quickly the GifDecoder class and it looks promising. With some modifiations, It may be what I need.
Thank you for pointing that, I will get back to you soon.

**Comment by koral--** [comment]
OK, I'm closing this issue for now but feel free to comment.

**Comment by marcin-adamczewski** [comment]
@koral-- Just wanted to let you know that the GifDecoder satisfied my requirements. Thanks again :)
