### ISSUE TITLE
1.2.17 contanis androidx

### ISSUE THREAD

**Issue by shuimuqinghua** [koral--/android-gif-drawable#671]
Hi:
   Failed to generate signed apk using the latest version 1.2.17，but using 1.2.15 is a success。
   Is it because 1.2.17 uses androidx?
![image](https://user-images.githubusercontent.com/7427087/62447068-0dbdd480-b797-11e9-85d6-de16aafec35f.png)

**Comment by koral--** [comment]
Could you post all the log lines starting with `Warning:`?

**Comment by shuimuqinghua** [comment]
OK
![image](https://user-images.githubusercontent.com/7427087/62450321-aa37a500-b79e-11e9-9072-559b7e910a68.png)
![image](https://user-images.githubusercontent.com/7427087/62450345-b7549400-b79e-11e9-8aac-44b4f64b1130.png)

**Comment by shuimuqinghua** [comment]
> Could you post all the log lines starting with `Warning:`?

![image](https://user-images.githubusercontent.com/7427087/62450425-de12ca80-b79e-11e9-839f-4e8381dfc331.png)
![image](https://user-images.githubusercontent.com/7427087/62450433-e539d880-b79e-11e9-9e68-ce8a42eb7407.png)

**Comment by koral--** [comment]
OK, thanks for the report.
AndroidX annotations are used but in `compileOnly` scope so they are not transitive and not packaged with the library.
That is purposeful configuration - consumers may use old support library (or nothing at all) and may not want AndroidX dependencies.

However this uncovers another issue. If consumer doesn't use AndroidX proguard/R8 will complain about missing classes.

Quick workaround is to add:
`-dontwarn androidx.annotation.**` to your proguard rules file.

The proper fix seems to be to add such line to consumer proguard rules in library.
I'll keep this issue open until it is done.

**Comment by shuimuqinghua** [comment]
> OK, thanks for the report.
> AndroidX annotations are used but in `compileOnly` scope so they are not transitive and not packaged with the library.
> That is purposeful configuration - consumers may use old support library (or nothing at all) and may not want AndroidX dependencies.
> 
> However this uncovers another issue. If consumer doesn't use AndroidX proguard/R8 will complain about missing classes.
> 
> Quick workaround is to add:
> `-dontwarn androidx.annotation.**` to your proguard rules file.
> 
> The proper fix seems to be to add such line to consumer proguard rules in library.
> I'll keep this issue open until it is done.

Ok, Thanks
