### ISSUE TITLE
Could you please provide an example on how to use the isRunning(), start(), stop() methods?

### ISSUE THREAD

**Issue by ManasMalla** [koral--/android-gif-drawable#672]
Could you please provide an example on how to use the isRunning(), start(), stop() methods? in java?? 
ASAP

**Comment by AlexTam930** [comment]
Hi, perhaps it may help you. You can try to define it in XML layout file like this:

`
<pl.droidsonroids.gif.GifImageView
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:src="@drawable/testImage"
  />
`

And acquire GifDrawable through GifImageView:

`
GifImageView gifImageView = (GifImageView) findViewById(R.id.gifImageView);
GifDrawable gifDrawable = (GifDrawable) gifImageView.getDrawable();
`

Consequently, please feel free to invoke any methods you need.

`
gifDrawable.start(); 
gifDrawable.stop(); 
gifDrawable.reset(); 
gifDrawable.isRunning(); 
gifDrawable.setLoopCount( 3 ); 
gifDrawable.getCurrentLoop()； 
gifDrawable.getCurrentPosition ; 
gifDrawable.getDuration() ;
 `

**Comment by koral--** [comment]
Here is java sample project: https://github.com/koral--/android-gif-drawable/tree/492b9404582a5c8e1c1adacb859ea4818d9ba136/sample/src/main/java/pl/droidsonroids/gif/sample
