### ISSUE TITLE
not animate through drawable resource get from attr

### ISSUE THREAD

**Issue by lein05** [koral--/android-gif-drawable#680]
i used different resId of gif when using different theme，so i organized them under an attr,
then neither setImageResource（R.attr.id） nor setImageDrawable(getDrawable(R.attr.id)) could play an animated gif but a static one, setImageDrawable(new GifDrawable(getResources, R.attr.id)) not work either， and i noticed that the id args in all the mentioned mentioned actually refers  not to attrId but resId , so is there a way to set the resource of the GifImageView by the attrId?
Thanks in advance!

**Comment by koral--** [comment]
`Resources.getDrawable(R.attr.id)` will never create `GifDrawable`.
You need to obtain resource id and then create GifDrawable from it. eg. 

```
new GifDrawable(getResources(), getResourceIdOrThrow(R.styleable.id))) 
```
