### ISSUE TITLE
is any possible support armeabi again?

### ISSUE THREAD

**Issue by liuchao0206** [koral--/android-gif-drawable#681]
> **Upgrading from 1.2.15**
> Minimum SDK version changed
> Minimum API level is now 17 (Android 4.2). `armeabi` (arm v5 and v6) is no longer supported.

`armeabi` is no longer support after version 1.2.15. Is any possible support armeabi again?

**Comment by koral--** [comment]
You can compile native code yourself using older NDK (older than r17).
