### ISSUE TITLE
Animation Blinking

### ISSUE THREAD

**Issue by Usmanalipurelogics** [koral--/android-gif-drawable#682]
i am using library which working perfectly fine with respect to my requirements. but facing blinking effect on while animation playing. can please guide me.?

**Comment by koral--** [comment]
Could you attach the affected GIF? See also https://github.com/koral--/android-gif-drawable/issues/604#issuecomment-435242129

**Comment by PradeepAmradi** [comment]
I am facing a similar issue, animation is blinking.
Sample https://gph.is/g/E0XGybE

**Comment by koral--** [comment]
I could not reproduce this so it looks like this is the same issue as described in #604.

**Comment by PradeepAmradi** [comment]
@koral-- sample video where this happens.. https://photos.app.goo.gl/uXbACZbqXjUkyDAa7
@Usmanalipurelogics would request to re-open this issue.
