### ISSUE TITLE
 UI thread stucks when I create GifDrawable(byteBuffer ByteBuffer)

### ISSUE THREAD

**Issue by DFGDEN** [koral--/android-gif-drawable#685]
I use text with a lot of(30+ items) ImageSpans with gifs. And UI thread stucks about 200-300ms when I create GifDrawables. Can you fix it? For example using optional placeholder.

**Comment by koral--** [comment]
Could you paste your code related to this issue?

**Comment by koral--** [comment]
Closing due to lack of steps to reproduce.
