### ISSUE TITLE
How to save Gif Drawable file to cache directory

### ISSUE THREAD

**Issue by FazalHussain** [koral--/android-gif-drawable#695]
I have sub-sampled my large image now I want to save in internal storage to get every time sub-sampled gif drawable. I have saved the bitmap but it is in PNG format
```

val file = File(getCacheDir(),"/loading.png")
    val outputStream = FileOutputStream(file)
    val bmp = (subsampledDrawable).seekToFrameAndGet(0)
    bmp.compress(Bitmap.CompressFormat.PNG, 100, outputStream)
    outputStream.flush()
    outputStream.close()
```

Is there any way to save gif files to internal storage?

**Comment by koral--** [comment]
Unfortunately this library does not support any kind of saving GIF files.
