### ISSUE TITLE
PARSE ERROR: unsupported class file version 52.0

### ISSUE THREAD

**Issue by XingSpace** [koral--/android-gif-drawable#702]
i got a error when build APK.

>Error converting bytecode to dex: Cause: Dex cannot parse version 52 byte code. This is caused by library dependencies that have been compiled using Java 8 or above

> PARSE ERROR:
unsupported class file version 52.0
...while parsing pl/droidsonroids/gif/BuildConfig.class

**Comment by XingSpace** [comment]
my project is normal when that run `compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.2'`,but when i change version from 1.2.2 to 1.2.18, the error is happened!

**Comment by koral--** [comment]
Which Android Gradle Plugin version are you using?

**Comment by XingSpace** [comment]
My Gradle Plugin version is `classpath 'com.android.tools.build:gradle:2.3.3'`

**Comment by XingSpace** [comment]
And my Java version is `1.8.0_201`

**Comment by XingSpace** [comment]
I upgrade my Gradle version to `com.android.tools.build:gradle:3.1.0`, the error is gone!!!Thank you so much!
