### ISSUE TITLE
How to add to proguard?

### ISSUE THREAD

**Issue by giga89** [koral--/android-gif-drawable#712]
I have this error on release with proguard enabled (minify and shrink enabled)

Caused by java.lang.UnsatisfiedLinkError
No implementation found for long pl.droidsonroids.gif.f.a(java.io.FileDescriptor, long) (tried Java_pl_droidsonroids_gif_f_a and Java_pl_droidsonroids_gif_f_a__Ljava_io_FileDescriptor_2J)

How to resolve?

I add -keep class pl.droidsonroids.gif.GifImageView { *; } but it doesnt work

Thanks

**Comment by koral--** [comment]
You should add something like this:
```
-keepclasseswithmembernames class * {
    native <methods>;
}
``` 
It is included if you use one of the default proguard files provided by Android SDK `getDefaultProguardFile("proguard-android-optimize.txt")` `proguard-android`
