### ISSUE TITLE
Veracode issue ReLinker.java

### ISSUE THREAD

**Issue by robimoltewhp** [koral--/android-gif-drawable#715]
Hello,

I am using Veracode Tool for code static analysis
https://www.veracode.com
and I am facing one security issue on your component

The issue says:

ReLinker.java: 187

Description: The method java.io.File.setReadable() is writing data in an unsafe manner, bypassing security mechanisms that would normally prevent unauthorized access.
Remediation: Write data to storage using appropriate security mechanisms. Remove references to world readable and world writable flags. Architect the application to have appropriate authentication and authorization routines for all stored data.

**Comment by koral--** [comment]
It is intended workaround.
See https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db and articles/bugs linked there for more details.

Feel free to open a PR if you have better idea.
