### ISSUE TITLE
miss armeabi library again

### ISSUE THREAD

**Issue by zhangli1845** [koral--/android-gif-drawable#722]
hi buddy:

        i think you missing libpl_droidsonroids_gif.so  for supported armeabi in latest version 1.2.19.
like https://github.com/koral--/android-gif-drawable/issues/494 this issue,.

**Comment by koral--** [comment]
Armeabi is not supported by NDK since 2017.
What is your use case?

**Comment by zhangli1845** [comment]
got it , i will change version to 1.2.10,thanks
