### ISSUE TITLE
this is a question: when I use RecylerView+GifImageView to load a lot gif,it will be slow and caton,how?

### ISSUE THREAD

**Issue by yun392898203521** [koral--/android-gif-drawable#724]
this is a question:
when I use RecylerView+GifImageView to load a lot gif,it will be slow and caton,how?

**Comment by koral--** [comment]
It depends on how you will implement that.
Sample code with RecyclerView is available in this repo: https://github.com/koral--/android-gif-drawable/tree/dev/sample/src/main/java/pl/droidsonroids/gif/sample/sources
