### ISSUE TITLE
Cannot build. NDK is old than mine

### ISSUE THREAD

**Issue by AlexzPurewoko** [koral--/android-gif-drawable#731]
While i want to build my projects, the gradle shows the error :

`
No version of NDK matched the requested version 20.0.5594570. 
Versions available locally: 20.1.5948944
Install NDK '20.0.5594570' and sync project
`

I think your NDK is old than me (my version 20.1.3948944), should i downgrade the NDKs or upgrade or keep it with change the configuration? If I should keep my NDK version, please tell me the configuration to ignore gradle error.

My Android Studio version : 3.6.1
Gradle tools version : 3.6.2
buildToolsVersion : 29.0.3

Thanks :+1:

**Comment by koral--** [comment]
I recommend updating it to the newest stable version locally. At the time of writing it is `21.0.6113669`.
I'll update it in repo soon.

**Comment by AlexzPurewoko** [comment]
I'll wait for an update. Nowadays, my inet is so slow. So i have to clone your repo. Thanks

_Sent from my Galaxy J2 Prime using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by koral--** [comment]
Updated on dev branch to `21.1.6352462`
