### ISSUE TITLE
GIFs with transparent background flicker

### ISSUE THREAD

**Issue by MaurizioMacri** [koral--/android-gif-drawable#732]
I'm using this library to show GIFs from giphy. It works good with normal GIFs but if you use GIFs with transparent background, like giphy stickers, they have flickering

![untitled](https://user-images.githubusercontent.com/5893005/79221619-7301b380-7e56-11ea-940a-ea78fd81aadc.gif)

**Comment by koral--** [comment]
What is the size of that file in pixels?

**Comment by MaurizioMacri** [comment]
It is 500 x 600, but I dont think it's a matter of size cause the issue happens whatever gif you download from Giphy that has transaprent background.
![source](https://user-images.githubusercontent.com/5893005/80292620-e01b2000-8757-11ea-8d81-54d44d4f4d17.gif)

**Comment by koral--** [comment]
Sorry for the delay.
It seems to be the same issue as: https://github.com/koral--/android-gif-drawable/issues/744#issuecomment-703180529

Workaround is to not use drawable but eg. GifTextureView or GifTexImage2D.
