### ISSUE TITLE
MavenCentral meta data character encoding

### ISSUE THREAD

**Issue by marcauberer** [koral--/android-gif-drawable#733]
Hi,
first of all: Thanks for your awesome lib!
Maybe you already saw the discussion [here](https://github.com/mikepenz/AboutLibraries/issues/459)
Would appreciate a fix for this. Thank you!

**Comment by koral--** [comment]
Thanks for the report I'll fix this at the nearest release.

**Comment by marcauberer** [comment]
Okay, thank you. I leave this open until it is fixed

**Comment by koral--** [comment]
I forgot to close this issue. However, it is fixed now. Since v1.2.20 [shipkit](https://github.com/mockito/shipkit) is used.
https://search.maven.org/artifact/pl.droidsonroids.gif/android-gif-drawable/1.2.20/aar
