### ISSUE TITLE
Does it support loading webp animation？

### ISSUE THREAD

**Issue by douya-labs** [koral--/android-gif-drawable#738]

**Comment by koral--** [comment]
At the time of writing no, it does not.

**Comment by AndroidDeveloperLB** [comment]
Any news about this? Maybe an alternative repository?

**Comment by koral--** [comment]
There is a draft of webp support on [webp](https://github.com/koral--/android-gif-drawable/tree/webp) branch.
For now I have no plans on actively working on that.
But I can review and merge a PR if provided.

**Comment by AndroidDeveloperLB** [comment]
@koral-- How did you find it? Does it work? Maybe you could put it in a new repository that's just for WEBP ?

**Comment by koral--** [comment]
It is an early draft which I have added. Feel free to fork and enhance that code. The idea was to reuse as much common code (for GIF and WEBP) as possible.
