### ISSUE TITLE
Remove animation on `GifTextureView`

### ISSUE THREAD

**Issue by archie94** [koral--/android-gif-drawable#745]
The documentation says 
```
Sets the source of the animation. Pass {@code null} to remove current source.
Equivalent of {@code setInputSource(inputSource, null)}.
```

However the Texture view seems to persist the last frame of the animation. Is this the intended behavior? 

On a `GifImageView` doing
```
gifImageView.setImageDrawable(null)
```
removes the animation completely. It would be nice if we can have consistent behavior across the two Gif views.
Excited to know your thoughts on the same.

[Reproducible commit](https://github.com/archie94/android-gif-drawable/commit/994bff1b8af227eb89a2e75fbcc151e016483e60)

Thanks!

**Comment by koral--** [comment]
Good catch.
AFAIR at the time of writing neither behavior was explicitly intended. The purpose of removing the input source was to free the related resources.
I think that it is a good idea to clear the texture.
Wanna make a PR?

**Comment by archie94** [comment]
Yes. Will send out a fix.
