### ISSUE TITLE
GifError 102: Failed to read from given input

### ISSUE THREAD

**Issue by manitozhang** [koral--/android-gif-drawable#750]
GifError 102: Failed to read from given input

**Comment by manitozhang** [comment]
GifError 102: Failed to read from given input

I'm put this gif to mipmap. then use GifImageView in layout, and set Attributes src

**Comment by koral--** [comment]
I cannot reproduce this issue.
So a few questions:
Could you attach that GIF or better a complete sample project which reproduces this issue?
On which Android version you are testing?
Is this GIF working as expected when is loaded from source other than mipmap?

**Comment by manitozhang** [comment]
Thank you. It's settled
