### ISSUE TITLE
Android gif drawable doesn't align to the center of the screen

### ISSUE THREAD

**Issue by AnatolijRojs** [koral--/android-gif-drawable#755]
How can I align a gif image to the center of the activity if it is a fixed size? (300dp to 300dp)?

The following commands do not give any result:
android:layout_centerHorizontal="true"
android:layout_centerVertical="true"
android:layout_gravity="center"

I attach the code of my activity

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#00a89b"
    android:orientation="vertical"
    tools:context=".MainActivity">

    <pl.droidsonroids.gif.GifImageView
        android:id="@+id/gifImageView"
        android:layout_width="300dp"
        android:layout_height="300dp"
        android:background="@drawable/splash_screen"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by AnatolijRojs** [comment]
Anyone can help?

**Comment by koral--** [comment]
`layout_centerHorizontal` attribute is for `RelativeLayout`, not for `ConstraintLayout`.
The easiest way in your case seems to be using a `FrameLayout` and set `android:layout_gravity="center"`.
