### ISSUE TITLE
Not showing .gif uri 

### ISSUE THREAD

**Issue by Sohit-Sharma** [koral--/android-gif-drawable#759]
Hi, 

I am facing issue for showing .gif string url/uri in this library. I tried from last 2 days but could not set the gif. Please help me for this or guide me how to setup the .gif url/uri in this library.

Thanks

**Comment by koral--** [comment]
URI is needed by library only to load a GIF, it is not preserved anywhere.
If you want to show it somewhere you have to handle that yourself.
