### ISSUE TITLE
"/lib/arm/libpl_droidsonroids_gif.so" crash in Android R, warnning in Android Q

### ISSUE THREAD

**Issue by bengele** [koral--/android-gif-drawable#763]
ABI: 'arm'
SYSVMTYPE: Maple
APPVMTYPE: Unknown
Timestamp: 2021-01-29 15:00:15+0800

uid: 10199
signal 35 (<debuggerd signal="signal"></debuggerd>), code -1 (SI_QUEUE), fault addr --------
Abort message: 'attempted to close file descriptor 428, expected to be unowned, actually owned by FILE* 0xe7b84108'
    r0  00000000  r1  00000d7b  r2  00000023  r3  ffd83120
    r4  e5a6d17c  r5  ffd83134  r6  ffd83120  r7  0000016b
    r8  ffd82f18  r9  00000014  r10 00000d7b  r11 e7bf9e00
    ip  00000d7b  sp  ffd82f10  lr  e5a18b2b  pc  e5a18b3e

backtrace:
      #00 pc 00056b3e  /apex/com.android.runtime/lib/bionic/libc.so (fdsan_error(char const*, ...)+278) (BuildId: fc1a7f107c69283e5e2e3f151f978619)
      #01 pc 0005693d  /apex/com.android.runtime/lib/bionic/libc.so (android_fdsan_close_with_tag+420) (BuildId: fc1a7f107c69283e5e2e3f151f978619)
      #02 pc 00057031  /apex/com.android.runtime/lib/bionic/libc.so (close+6) (BuildId: fc1a7f107c69283e5e2e3f151f978619)
      #03 pc 0000401d  /data/app/com.benew.ntt-uF_jA4BxkrD8fYEPHkIPHw==/lib/arm/libpl_droidsonroids_gif.so (Java_pl_droidsonroids_gif_GifInfoHandle_openNativeFileDescriptor+100) (BuildId: e98156fc7b7e2f32d8bba1195894be9014ed750e)
      #04 pc 000e6519  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+40) (BuildId: 9da4d7ce8f677f56c6af9c29c50adae0)
      #05 pc 000e1bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 9da4d7ce8f677f56c6af9c29c50adae0)
      #06 pc 00450d8f  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+246) (BuildId: 9da4d7ce8f677f56c6af9c29c50adae0)
      #07 pc 000ea009  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+180) (BuildId: 9da4d7ce8f677f56c6af9c29c50adae0)

**Comment by koral--** [comment]
What library version are you using?

**Comment by liulq315** [comment]
Version 1.2.6 crashes in Android R, but there is no error when it is updated to 1.2.23

**Comment by koral--** [comment]
OK, so I'm closing this issue.
