### ISSUE TITLE
GifView not supported below android 6

### ISSUE THREAD

**Issue by surajsahani** [koral--/android-gif-drawable#764]
App keep crashing below android 6 Unable to Inflate Binary XML layout

**Comment by koral--** [comment]
There is no GifView in this library.

**Comment by surajsahani** [comment]
i am using this library to display animation on my android application

**Comment by koral--** [comment]
Sorry, your information are very laconic and inconsistent.
If you believe that you are using this library please provide a reproducible example and the full stacktrace you are getting.

**Comment by surajsahani** [comment]
`   <pl.droidsonroids.gif.GifImageView
        android:id="@+id/ivlogo"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.39"
        android:src="@drawable/ssafeoutslogoanimation"/>`

**Comment by surajsahani** [comment]
> ` <pl.droidsonroids.gif.GifImageView android:id="@+id/ivlogo" android:layout_width="0dp" android:layout_height="0dp" app:layout_constraintBottom_toBottomOf="parent" app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent" app:layout_constraintTop_toTopOf="parent" app:layout_constraintVertical_bias="0.39" android:src="@drawable/ssafeoutslogoanimation"/>`

this is my xml file i am using

**Comment by surajsahani** [comment]
![Screenshot from 2021-02-19 22-37-19](https://user-images.githubusercontent.com/22853459/108537202-58fcf100-7303-11eb-94ef-d6df9633dccb.png)

**Comment by koral--** [comment]
@surajsahani please create a github project with complete sample app which reproduces the issue.
