### ISSUE TITLE
A/libc: exiting due to SIG_DFL handler for signal 11

### ISSUE THREAD

**Issue by LeeTheOne** [koral--/android-gif-drawable#771]
![33396c218bf9820136d0c074796215a4](https://user-images.githubusercontent.com/4384948/124476444-6360e880-ddd5-11eb-8063-2f72fcf6b04a.gif)
Please help me! My app crashed on this GIF every time,  version 1.2.18.

**Comment by koral--** [comment]
Does it work on the latest version (1.2.23)?

**Comment by koral--** [comment]
I could not reproduce this issue on 1.2.23.
