### ISSUE TITLE
InflateException: Binary XML file line #10: Error inflating class pl.droidsonroids.gif.GifImageView

### ISSUE THREAD

**Issue by Faizan-Pf** [koral--/android-gif-drawable#776]
I am facing this issue on devices that have **android version 5.1.1**
I faced this issue on Huawei, Samsung devices with the version 5.1.1
Unable to track the issue.

**Exception is:** 
`java.lang.RuntimeException: Unable to start activity ComponentInfo{project.Activity.Home}: android.view.InflateException: Binary XML file line #10: Error inflating class pl.droidsonroids.gif.GifImageView`

**StackTrace is:**
```
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
android.app.ActivityThread.access$800(ActivityThread.java:156)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:135)
android.app.ActivityThread.main(ActivityThread.java:5314)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:374)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by koral--** [comment]
You need to provide more data. A minimum reproducible code sample preferably.

**Comment by Faizan-Pf** [comment]
I am using your library to load gif in xml file **like this:**

`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".SignUpModule.SplashScreen">

    <pl.droidsonroids.gif.GifImageView
        android:id="@+id/splashScreen_ImgView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@drawable/splash_gif"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</FrameLayout>`


In java class when I am loading xml, it is crashing app. **Java class code is:**

`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_splash_screen, container, false);  **// This line is crashing app**
}`

This issue is occured on some devices that have **android version 5.1.1**


**Fingerprints of devices on which I faced this issue are:**

1. vivo/andromeda/andromeda:5.1.1/LMY47D/5080180:user/release-keys (harware: vmi)
2. Xiaomi/cepheus/cepheus:8.1.1/LMY47D/5080180:user/release-keys (harware: trend)
3. generic/crosshatch/crosshatch:9/PPRL.190801.002/05190150:userdebug/test-keys (harware: ranchu)
4. Samsung/norma/norma:5.1.1/LMY47D/5080180:user/release-keys (harware: vmi)
5. Huawei/mensa/mensa:5.1.1/LMY47D/5080180:user/release-keys (harware: vmi)
6. Android-x86/android_x86_64/x86_64:8.1.0/OPM8.190605.003/cwhuang0613:userdebug/test-keys (harware: android_x86_64)

**Comment by yaroslav-v** [comment]
Hi there!

Any thoughts? I have a similar problem for a couple of users. Unfortunately, I can't provide a code sample because I see the issue in Firebase reports only. Any local tests pass normally.

In my case it happens on OPPO A7 with Andorid 8.1.0 on board.

Here is an additional stack trace:

```
Fatal Exception: android.view.InflateException
Binary XML file line #68: Binary XML file line #68: Error inflating class pl.droidsonroids.gif.GifImageView

...

Caused by java.lang.UnsatisfiedLinkError
dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/data/com.safelagoon.parentini/app_lib/libpl_droidsonroids_gif.so"
pl.droidsonroids.relinker.SystemLibraryLoader.loadPath

java.lang.Runtime.load0 (Runtime.java:928)
java.lang.System.load (System.java:1621)
pl.droidsonroids.relinker.SystemLibraryLoader.loadPath (SystemLibraryLoader.java:29)
pl.droidsonroids.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:204)
pl.droidsonroids.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
pl.droidsonroids.relinker.ReLinker.loadLibrary (ReLinker.java:70)
pl.droidsonroids.relinker.ReLinker.loadLibrary (ReLinker.java:51)
pl.droidsonroids.gif.LibraryLoader.loadLibrary (LibraryLoader.java:52)
pl.droidsonroids.gif.GifInfoHandle.<clinit> (GifInfoHandle.java:27)
pl.droidsonroids.gif.GifDrawable.<init> (GifDrawable.java:161)
pl.droidsonroids.gif.GifDrawable.<init> (GifDrawable.java:96)
pl.droidsonroids.gif.GifViewUtils.setResource (GifViewUtils.java:55)
pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.getResourceId (GifViewUtils.java:138)
pl.droidsonroids.gif.GifViewUtils$GifImageViewAttributes.<init> (GifViewUtils.java:124)
pl.droidsonroids.gif.GifViewUtils.initImageView (GifViewUtils.java:29)
pl.droidsonroids.gif.GifImageView.<init> (GifImageView.java:41)
java.lang.reflect.Constructor.newInstance0 (Constructor.java)
android.view.LayoutInflater.inflate (LayoutInflater.java:423)
```

**Comment by koral--** [comment]
@Faizan-Pf could you post a complete stacktrace like @yaroslav-v did?

@yaroslav-v 
> dlopen failed: cannot find "" from verneed[0] in DT_NEEDED list for "/data/data/com.safelagoon.parentini/app_lib/libpl_droidsonroids_gif.so"

That's the key point.

Do you have `extractNativeLibs` set to false?
https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs

**Comment by yaroslav-v** [comment]
Nope.

It's not set anywhere, minSdkVersion = 21 and targetSdkVersion = 30. So, it should be true by default according to the docs.

P.S. The user base of the app I'm working on is relatively high, but the number of exceptions isn't really significant. I believe it might be some device specific problem?!

**Comment by koral--** [comment]
Yeah, it looks like a device-specific issue.
This library already falls back to using ReLinker if normal shared library loading fails.
I don't have any other ideas what more can be done.
If I will have that specific device model in my hands and will be able to repro this issue I can then investigate that.
