### ISSUE TITLE
error with scoped storage

### ISSUE THREAD

**Issue by CNMonkeyDLuffy** [koral--/android-gif-drawable#787]
hi ，in my project ，configure targetSdk 30 ，app will crash when i use “gifview”，cause by pl.droidsonroids.gif.GifInfoHandle.openFileDescriptor(GifInfoHandle.java:85)，maybe because of scoped storage in android10，The official advice is shown below， if it's right ,can you fix it

![image](https://user-images.githubusercontent.com/23278391/146479359-120963e5-8aa7-4e76-84ee-8b505de167a9.png)

**Comment by koral--** [comment]
It is your (app) responsibility to request permissions and obtain appropriate Uris.
Such Uri can be passed to methods from this library.
