### ISSUE TITLE
seekToFrameAndGet with subsampling returns blank bitmap

### ISSUE THREAD

**Issue by crowbarsolutions** [koral--/android-gif-drawable#797]
Using version 1.2.24

```
GifDrawableBuilder builder = new GifDrawableBuilder();
builder.sampleSize(2);
builder.from(methodThatReturnsBufferedInputStream());       
GifDrawable gifFromBytes = builder.build();
Bitmap bs = gifFromBytes.seekToFrameAndGet(0);
gifFromBytes.recycle();
```

The resulting bitmap is blank (all black) when I use `sampleSize` with any parameter greater than 1. With `sampleSize` set to 1 I am getting the correct bitmap. I am using this GIF to test with: https://crowbarsolutions.com/test/content/test.gif

This issue doesn't happen when using version 1.2.19 but happens when you use any version after that.

**Comment by koral--** [comment]
Thanks for the report, I was able to reproduce that.
It seems that subsampling gets broken at all.
Will try to fix it ASAP.
