### ISSUE TITLE
GifError 101: Failed to open given input: Permission denied

### ISSUE THREAD

**Issue by miaowmiaow** [koral--/android-gif-drawable#804]
It runs normally on the Android API 30, but throws an exception on the Android API 29.
I'm sure I've applied for permission.

This is my development environment:
gradle_version = "7.1.2"
kotlin_version = '1.6.21'
Android Studio Bumblebee | 2021.1.1

**Comment by koral--** [comment]
Please attach a project which reproduces this issue.

**Comment by miaowmiaow** [comment]
Thank, This is my project.
[fragmject.zip](https://github.com/koral--/android-gif-drawable/files/9313494/fragmject.zip)
![20220812112522](https://user-images.githubusercontent.com/13847718/184280050-d8fa0bfb-6afb-46c4-a522-44535d99f680.png)
![20220812112922](https://user-images.githubusercontent.com/13847718/184280060-e54e22ab-bce9-495e-9913-ed999d523491.png)
