### ISSUE TITLE
ANR_EXCEPTION

### ISSUE THREAD

**Issue by a365344743s** [koral--/android-gif-drawable#805]
ROM: vivo/FUNTOUCH Android 11, level 30 arm64-v8a
SDKVersion: 1.2.22

# main(1)

ANR_EXCEPTION
Find process anr, but unable to get anr message.

1 sun.misc.Unsafe.park(Native Method)
2 java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
3 java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:868)
4 java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:902)
5 java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1227)
6 java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:216)
7 java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:294)
8 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.remove(ScheduledThreadPoolExecutor.java:996)
9 java.util.concurrent.ThreadPoolExecutor.remove(ThreadPoolExecutor.java:1785)
10 pl.droidsonroids.gif.GifDrawable.scheduleNextRender(GifDrawable.java:801)
11 pl.droidsonroids.gif.GifDrawable.invalidateSelf(GifDrawable.java:289)
12 pl.droidsonroids.gif.InvalidationHandler.handleMessage(InvalidationHandler.java:29)
13 android.os.Handler.dispatchMessage(Handler.java:106)
14 android.os.Looper.loop(Looper.java:257)
15 android.app.ActivityThread.main(ActivityThread.java:8399)
16 java.lang.reflect.Method.invoke(Native Method)
17 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
18 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by koral--** [comment]
Please attach the sample project which reproduces this issue.

**Comment by koral--** [comment]
Closed due to inactivity
