### ISSUE TITLE
Unsupported still image

### ISSUE THREAD

**Issue by hgourvest** [koral--/android-gif-drawable#830]
this file is not decoded, it's a gif image with a single frame
![ga840101](https://github.com/koral--/android-gif-drawable/assets/1659652/74714692-dc1e-46ed-984b-54c0a45b5f68)

**Comment by hgourvest** [comment]
After investigating, it is an expected behaviour, I would like to know why.

**Comment by hgourvest** [comment]
I removed the limitation commenting code in seekToFrame jni method and it works as expected.
I am missing something ?

**Comment by koral--** [comment]
What does "not decoded" mean?
Share a reproducer project and describe the desired behavior.

**Comment by hgourvest** [comment]
I only use GifDecoder class. The bitmap stay black when there is only one frame.

`
try (final FileInputStream stream = new FileInputStream(cache)) {
  BufferedInputStream buffStream = new BufferedInputStream(stream);
  GifDecoder decoder = new GifDecoder(new InputSource.InputStreamSource(buffStream));
  int framesCount = decoder.getNumberOfFrames();
  if (framesCount > 0) {
    bmp = Bitmap.createBitmap(decoder.getWidth(), decoder.getHeight(), Bitmap.Config.ARGB_8888);
    for (int i = 0; i < framesCount; i++) {
    decoder.seekToFrame(i, bmp);
  }
  bmp.recycle();
 }
}
`

The problem is [here](https://github.com/koral--/android-gif-drawable/blob/c10c4f1fffa52cc958a9110914112adf4a5a9fbc/android-gif-drawable/src/main/c/control.c#L116)

**Comment by koral--** [comment]
Thanks, now I get it.
AFAIK that check was one of optimizations for GifDrawable as it naturally always points to some frame and seeking in still images is no-op there.
Use case like yours was not anticipated.
I'll check that and update the code soon.

**Comment by hgourvest** [comment]
Thanks
