### ISSUE TITLE
FORTIFY enablement

### ISSUE THREAD

**Issue by repl-saijanani-s** [koral--/android-gif-drawable#843]
Hi, we have received a PenTest report that FORTIFY is not enabled in the library and that is reported as a vulnerability. We are currently using version 1.2.19 and it would be of great help if someone could let us know if FORTIFY has been enabled in any of the recent versions of the library?

<img width="975" alt="image" src="https://github.com/koral--/android-gif-drawable/assets/11546108/609120f9-0937-4764-8351-28a311ab40c2">

**Comment by koral--** [comment]
If you mean a `D_FORTIFY_SOURCE` compiler flag, it should be enabled in the recent library versions.
